[package]
name = "rustjvm-gc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Garbage collector and memory management for RustJVM"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
rustjvm-types = { path = "../types" }
parking_lot = "0.12"
tracing.workspace = true
rustc-hash = "1.1"

[dev-dependencies]
rustjvm-jit = { path = "../jit" }

[lints]
workspace = true
