#!/usr/bin/env bash
# Bit-exactness check for one resolution: render the same frame on HotSpot
# and on CratonVM's `--gpu` path, dump both, and diff them pixel by pixel.
#
# The interleaved timing harness deliberately does not do this -- it renders
# for the clock and never looks at the image -- so a resolution measured only
# there has its TIMING confirmed and its CORRECTNESS assumed. This closes
# that gap for any size, at the cost of two renders and 8 bytes of disk per
# pixel.
#
# Usage: verify-frame.sh <cratonvm.exe> <width> <height> [iters]
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HERE_W="$(cd "$HERE" && pwd -W)"
CV="${1:?usage: verify-frame.sh <cratonvm.exe> <width> <height> [iters]}"
W="${2:?width}"
H="${3:?height}"
ITERS="${4:-2}"

JDK="${JDK:-C:/Program Files/Eclipse Adoptium/jdk-25.0.3.9-hotspot}"
GPU_JAR="${GPU_JAR:?set GPU_JAR to the craton-gpu annotations jar}"
CP="$HERE_W;$GPU_JAR"
# `bench-gpu/results/dumps/` is already git-ignored: one 8K frame is 133 MB
# and it is regenerated by re-running this script.
OUT="${OUT:-$HERE/results/dumps}"
mkdir -p "$OUT"
OUT_W="$(cd "$OUT" && pwd -W)"

"$JDK/bin/javac" -cp "$GPU_JAR" -d "$HERE" \
  "$HERE/RayTracerKernel.java" "$HERE/FrameDiff.java" || exit 1

ref="$OUT_W/ref-${W}x${H}.bin"
cand="$OUT_W/craton-gpu-${W}x${H}.bin"

echo "== HotSpot reference =="
"$JDK/bin/java" -cp "$CP" RayTracerKernel "$W" "$H" "$ITERS" "$ref" | tail -1
echo "== CratonVM --gpu =="
"$CV" --java-home "$JDK" --gpu --gpu-min-work 1 --Xmx 6g -cp "$CP" \
  RayTracerKernel "$W" "$H" "$ITERS" "$cand" 2>/dev/null | tail -1
echo "== diff =="
"$JDK/bin/java" -cp "$CP" FrameDiff "$W" "$H" "$ref" "$cand"
