use strict;
use warnings;
my $file = '/data/data/cratonvm-hib-longtail-residuals-20260713-azure-002/vm/src/runtime/interpreter.rs';
open my $in, '<:raw', $file or die $!;
local $/;
my $text = <$in>;
close $in;
$text =~ s/#\[cfg\(target_os = "windows"\)\]\R\s*const JIT_ABI_REG_SLOTS: usize = 4;\R\s*#\[cfg\(not\(target_os = "windows"\)\)\]\R\s*const JIT_ABI_REG_SLOTS: usize = 6;/    const JIT_ABI_MAX_JAVA_ARGS: usize = 8;/g;
$text =~ s/JIT_ABI_REG_SLOTS/JIT_ABI_MAX_JAVA_ARGS/g;
$text =~ s/\r$//gm;
open my $out, '>:raw', $file or die $!;
print {$out} $text;
close $out;
