#!/usr/bin/env bash
# RJ.5 — regenerate `docs/jck-compliance.md` from a JavaTest-format
# JCK report.
#
# Input: the path to a JavaTest `summary.txt` produced by
# `jtharness` (the harness used by `ci/jck-runner.yml`). The file
# is one test per line, of the form:
#
#     api/java_lang/String/charAt#index001 Passed
#
# Output: Markdown matching `docs/jck-compliance.md` on stdout, with:
#   * one row per top-level `api/<X>` section,
#   * Pass% computed as passed / total,
#   * Open-bugs column left at `—` (populated by a second pass that
#     correlates roadmap items; we keep them separate so the harness
#     regeneration never silently wipes hand-curated bug tallies).
#
# Usage:
#   scripts/jck-matrix.sh /tmp/jck-work/report/summary.txt
#   scripts/jck-matrix.sh /tmp/jck-work/report/summary.txt \
#       --merge docs/jck-compliance.md        # preserve Open-bugs col
#
# Exit codes:
#   0 — matrix emitted
#   1 — summary.txt missing or unreadable
#   2 — no test lines matched the expected grammar (wrong file format)

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "usage: $0 <summary.txt> [--merge <existing.md>]" >&2
    exit 1
fi

SUMMARY="$1"
MERGE_SRC=""
if [[ "${2:-}" == "--merge" ]]; then
    MERGE_SRC="${3:-}"
fi

if [[ ! -s "$SUMMARY" ]]; then
    echo "$0: summary file missing or empty: $SUMMARY" >&2
    exit 1
fi

# Parse summary.txt → Section -> (Passed, Total).
# Use whichever python is on PATH (python3 on POSIX, python on Windows Git-Bash).
if command -v python3 >/dev/null 2>&1; then
    PY=python3
elif command -v python >/dev/null 2>&1; then
    PY=python
else
    echo "$0: python3 or python is required on PATH" >&2
    exit 1
fi
"$PY" - "$SUMMARY" "$MERGE_SRC" <<'PY'
import os
import re
import sys
from collections import defaultdict

summary_path = sys.argv[1]
merge_src = sys.argv[2] if len(sys.argv) > 2 else ""

line_re = re.compile(r'^(api/[a-z_0-9/]+(?:/[A-Za-z_0-9]+)?)\S*\s+(Passed|Failed|Error|Not Run|Not Applicable)\b')

passed = defaultdict(int)
total = defaultdict(int)
parsed = 0
with open(summary_path, 'r', encoding='utf-8') as f:
    for line in f:
        m = line_re.match(line)
        if not m:
            continue
        parsed += 1
        path, status = m.group(1), m.group(2)
        # Top-level section = first two path segments (e.g. api/java_lang).
        parts = path.split('/', 2)
        section = '/'.join(parts[:2]) if len(parts) >= 2 else path
        total[section] += 1
        if status == "Passed":
            passed[section] += 1

if parsed == 0:
    sys.stderr.write(f"{sys.argv[0]}: no matching test lines in {summary_path}\n")
    sys.exit(2)

# Inherit Open-bugs column from an existing matrix when --merge given.
open_bugs = {}
if merge_src and os.path.isfile(merge_src):
    with open(merge_src, 'r', encoding='utf-8') as f:
        for line in f:
            # rows look like: | `api/java_lang` | ... | 92% | 1 | ... |
            m = re.match(r'\|\s*`([^`]+)`\s*\|[^|]*\|\s*\*\*[0-9.]+%?\*\*\s*\|\s*([0-9]+|—)\s*\|', line)
            if m:
                open_bugs[m.group(1)] = m.group(2)

print("# JCK Compliance Matrix (auto-generated)")
print()
print(f"> Regenerated by `scripts/jck-matrix.sh` from `{summary_path}`.")
print(">")
print("> Hand-curated narrative lives in the non-auto section of")
print("> `docs/jck-compliance.md` — only the table below is replaced.")
print()
print("| Section | Pass % | Passed / Total | Open bugs |")
print("|---|---|---|---|")
for section in sorted(total):
    p = passed[section]
    t = total[section]
    pct = f"{100 * p / t:.0f}%" if t else "n/a"
    bugs = open_bugs.get(section, "—")
    print(f"| `{section}` | **{pct}** | {p} / {t} | {bugs} |")
print()
grand_p = sum(passed.values())
grand_t = sum(total.values())
grand_pct = f"{100 * grand_p / grand_t:.0f}%" if grand_t else "n/a"
print(f"**Workspace total:** {grand_p} / {grand_t} ({grand_pct})")
PY
