[package]
name = "cratonvm-native-collections"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Java collections native methods for CratonVM"
documentation = "https://docs.rs/cratonvm-native-collections"
readme = "../README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
synthetic-jdk = []

[dependencies]
cratonvm-types = { path = "../types" }
cratonvm-native-api = { path = "../native-api" }
parking_lot.workspace = true

[lints]
workspace = true
