#!/usr/bin/env python3
"""Generate SweepPhases.java: the RT-8 code-cache sweeper's soak workload.

    python tools/probes/gen-sweep-phases.py > /tmp/sp/SweepPhases.java
    javac -d /tmp/sp /tmp/sp/SweepPhases.java
    java -cp /tmp/sp SweepPhases > hotspot.txt 2>&1
    CRATONVM_JIT_CODE_CACHE_MAX_MB=1 \\
    CRATONVM_JIT=code-cache-sweep,entry-counter,print-compilation \\
        cratonvm -cp /tmp/sp SweepPhases > craton.txt 2>&1

Many distinct small methods in PHASES groups. Each phase makes its own group
hot and never calls the previous group again, so at a 1 MiB cap the cache fills
during phase 0 and everything after runs against a cache full of dead code --
the case the sweeper exists for. Two rounds, so the first round's bodies are
needed again after they were swept.

What to read (prints go to stderr, so they interleave with the JIT's lines):
  * the `round N phase P` checksums must equal HotSpot's (`tr -d '\\r'` first);
  * `code-cache sweep: withdrew ...` lines must keep appearing after phase 0;
  * compile lines (`c1`/`c2`) must keep appearing after the first sweep.

Before 2026-09-18 the second and third never happened -- see `NOTES-abi8.md`,
RT-8, "the soak".
"""
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 2400
PHASES = int(sys.argv[2]) if len(sys.argv) > 2 else 6
# Optional third argument: `package.ClassName`, for the checked-in test fixture
# `vm/tests/resources/cratonvm/CodeCacheSweepPhases.java`
# (`gen-sweep-phases.py 600 4 cratonvm.CodeCacheSweepPhases`).
QUALIFIED = sys.argv[3] if len(sys.argv) > 3 else "SweepPhases"
PACKAGE, _, CLASS = QUALIFIED.rpartition(".")

out = [" ".join(["// Generated by tools/probes/gen-sweep-phases.py", *sys.argv[1:],
                 "-- do not edit."])]
if PACKAGE:
    out.append(f"package {PACKAGE};")
out.append(f"public class {CLASS} {{")
for i in range(N):
    out.append(
        f"  static long m{i}(long x) {{ long s = x; for (int k = 0; k < 8; k++) "
        f"{{ s = s * {31 + i % 97} + (k ^ {i}); if ((s & {i % 13 + 1}) == 0) s += {i}; "
        f"s ^= (s >>> {i % 17 + 1}); }} return s; }}")
per = N // PHASES
for p in range(PHASES):
    out.append(f"  static long phase{p}(int reps) {{ long c = 0; for (int r = 0; r < reps; r++) {{")
    for i in range(p * per, (p + 1) * per):
        out.append(f"    c += m{i}(r + c);")
    out.append("  } return c; }")
out.append("  public static void main(String[] a) {")
out.append("    for (int round = 0; round < 2; round++) {")
for p in range(PHASES):
    out.append(f'      System.err.println("round " + round + " phase {p} " + phase{p}(3000));')
out.append("    }")
out.append("  }")
out.append("}")
print("\n".join(out))
