<#
.SYNOPSIS
  Spring Boot JUnit suite runner for CratonVM and HotSpot.

.DESCRIPTION
  Runs the compiled Spring Boot test classes (core/, module/, cli/,
  configuration-metadata/, loader/, test-support/ Gradle subtrees) one
  process per class through apps\spring-boot\sb-runner\SbRunner.class, a
  JUnit Platform launcher harness (mirrors apps\keycloak\kc-runner\KcRunner).
  Records per-class wall time, persists stdout/stderr logs, can select
  classes by category (passed vs all others), and can run JIT on/off x
  category combinations concurrently.

  Unlike the Maven-based Keycloak runner, Spring Boot's per-module test
  runtime classpath is generated by a Gradle init script
  (apps\spring-boot\cratonvm-test-cp.init.gradle) that writes
  <module>\build\cratonvm-test-cp.txt for every project with a `test`
  source set.
#>
[CmdletBinding()]
param(
  [ValidateSet('passed','others','failed','all')] [string]$Category = 'all',
  [ValidateSet('on','off')]                       [string]$Jit = 'on',
  [ValidateSet('craton','hotspot')]               [string]$Vm = 'craton',

  [int]$Start = 1,
  [int]$Count = 0,
  [int]$Parallel = 4,
  [int]$TimeoutSec = 300,

  [string]$RunName = '',
  [string]$ModeName = '',
  [string]$SpringBootRoot = '',
  [string]$WorkDir = '',
  [string]$RefCsv = '',
  # HotSpot results used to tell a CratonVM defect apart from a fixture or
  # upstream failure the reference VM shares. Defaults to the file a `-Vm
  # hotspot` run already writes: <work>/baseline/hotspot-baseline-latest.tsv.
  [string]$HotspotBaseline = '',
  [string]$ClassList = '',
  [string[]]$Subtrees = @('core','module','cli','configuration-metadata','loader','test-support'),
  [string]$Exe = '',
  [string]$JdkHome = '',
  [string]$MaxHeap = '2g',
  [string[]]$CratonArgs = @(),

  # The corrupt-`Value`-cell census is ARMED by default on craton runs. It
  # costs one extra stderr line per class and turns a heap-integrity guard hit
  # from an event nobody sees into one that names its own door, receiver and
  # Java stack the FIRST time it happens. A cell was observed once in this
  # suite on 2026-08-22 and has not been reproduced since; the whole reason it
  # is unexplained is that nothing was armed when it fired.
  [switch]$NoCorruptCellCensus,

  [switch]$RefreshLists,
  [switch]$RefreshClasspaths,
  [switch]$ListOnly,
  [switch]$AllModes,
  [switch]$Setup
)

$ErrorActionPreference = 'Stop'

function Write-Info([string]$Message) {
  Write-Host "[spring-boot-suite] $Message"
}

function Die([string]$Message) {
  Write-Error "[spring-boot-suite] $Message"
  exit 1
}

function Get-RepoRoot {
  try {
    $root = & git -C $PSScriptRoot rev-parse --show-toplevel 2>$null
    if ($LASTEXITCODE -eq 0 -and $root) { return $root.Trim() }
  } catch {}
  return (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent)
}

function Get-PowerShellExe {
  if ($PSHOME) {
    $candidate = Join-Path $PSHOME 'pwsh.exe'
    if (Test-Path $candidate) { return $candidate }
    $candidate = Join-Path $PSHOME 'powershell.exe'
    if (Test-Path $candidate) { return $candidate }
  }
  return 'powershell.exe'
}

function ConvertTo-SafeName([string]$Value) {
  return ($Value -replace '[^A-Za-z0-9_.-]', '_')
}

function ConvertTo-SafeFileStem([string]$Value, [int]$MaxLength = 96) {
  $safe = ConvertTo-SafeName $Value
  if ($MaxLength -lt 16) { $MaxLength = 16 }
  if ($safe.Length -le $MaxLength) { return $safe }
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($safe)
    $hash = ([System.BitConverter]::ToString($sha.ComputeHash($bytes)) -replace '-', '').Substring(0, 12).ToLowerInvariant()
  } finally {
    $sha.Dispose()
  }
  $prefixLength = $MaxLength - $hash.Length - 1
  return "$($safe.Substring(0, $prefixLength))-$hash"
}

function Get-Sha256Hex([string]$Value) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
    return (([System.BitConverter]::ToString($sha.ComputeHash($bytes))) -replace '-', '').ToLowerInvariant()
  } finally {
    $sha.Dispose()
  }
}

function ConvertTo-InvariantString([double]$Value) {
  return $Value.ToString('F3', [System.Globalization.CultureInfo]::InvariantCulture)
}

function ConvertFrom-InvariantString([string]$Value) {
  $parsed = 0.0
  if ([double]::TryParse($Value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
    return $parsed
  }
  return 0.0
}

function Quote-WindowsArgument([string]$Argument) {
  if ($null -eq $Argument) { return '""' }
  if ($Argument.Length -eq 0) { return '""' }
  if ($Argument -notmatch '[\s"]') { return $Argument }
  $result = New-Object System.Text.StringBuilder
  [void]$result.Append('"')
  $backslashes = 0
  foreach ($ch in $Argument.ToCharArray()) {
    if ($ch -eq '\') {
      $backslashes++
    } elseif ($ch -eq '"') {
      if ($backslashes -gt 0) { [void]$result.Append('\' * ($backslashes * 2)) }
      $backslashes = 0
      [void]$result.Append('\"')
    } else {
      if ($backslashes -gt 0) { [void]$result.Append('\' * $backslashes) }
      $backslashes = 0
      [void]$result.Append($ch)
    }
  }
  if ($backslashes -gt 0) { [void]$result.Append('\' * ($backslashes * 2)) }
  [void]$result.Append('"')
  return $result.ToString()
}

function Set-ProcessArguments([System.Diagnostics.ProcessStartInfo]$StartInfo, [string[]]$Arguments) {
  # ProcessStartInfo.ArgumentList is unavailable/null under Windows PowerShell
  # 5.1 (.NET Framework) in some environments — fall back to the classic
  # pre-quoted Arguments string when it's not usable.
  $argListProp = $StartInfo.GetType().GetProperty('ArgumentList')
  if ($argListProp -and $StartInfo.ArgumentList) {
    foreach ($arg in $Arguments) { [void]$StartInfo.ArgumentList.Add($arg) }
  } else {
    $StartInfo.Arguments = (($Arguments | ForEach-Object { Quote-WindowsArgument $_ }) -join ' ')
  }
}

function Start-RedirectedProcess {
  param([string]$FilePath, [string[]]$Arguments, [string]$WorkingDirectory, [string]$StdoutPath, [string]$StderrPath)
  $psi = [System.Diagnostics.ProcessStartInfo]::new()
  $psi.FileName = $FilePath
  $psi.WorkingDirectory = $WorkingDirectory
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  Set-ProcessArguments -StartInfo $psi -Arguments $Arguments
  $proc = [System.Diagnostics.Process]::new()
  $proc.StartInfo = $psi
  [void]$proc.Start()
  return [pscustomobject]@{
    proc = $proc
    stdoutTask = $proc.StandardOutput.ReadToEndAsync()
    stderrTask = $proc.StandardError.ReadToEndAsync()
    stdoutPath = $StdoutPath
    stderrPath = $StderrPath
  }
}

function Complete-RedirectedProcess([object]$Record) {
  $Record.proc.WaitForExit()
  try { $Record.stdoutTask.Wait(5000) | Out-Null } catch {}
  try { $Record.stderrTask.Wait(5000) | Out-Null } catch {}
  $stdout = ''; $stderr = ''
  try { $stdout = $Record.stdoutTask.Result } catch {}
  try { $stderr = $Record.stderrTask.Result } catch {}
  if ($Record.stdoutPath) { [System.IO.File]::WriteAllText($Record.stdoutPath, $stdout, [System.Text.Encoding]::UTF8) }
  if ($Record.stderrPath) { [System.IO.File]::WriteAllText($Record.stderrPath, $stderr, [System.Text.Encoding]::UTF8) }
  $exitCode = $Record.proc.ExitCode
  try { $Record.proc.Dispose() } catch {}
  return $exitCode
}

function Split-ClasspathEntries([string]$Classpath) {
  if (-not $Classpath) { return @() }
  $separator = [string][System.IO.Path]::PathSeparator
  return @($Classpath -split [regex]::Escape($separator) | Where-Object { $_ })
}

function Add-UniqueClasspathEntry {
  param([System.Collections.Generic.List[string]]$Entries, [hashtable]$Seen, [string]$Entry)
  if (-not $Entry) { return }
  try {
    $full = [System.IO.Path]::GetFullPath($Entry)
    $key = $full.ToLowerInvariant()
    $value = $full
  } catch {
    $key = $Entry.ToLowerInvariant()
    $value = $Entry
  }
  if (-not $Seen.ContainsKey($key)) {
    $Entries.Add($value)
    $Seen[$key] = $true
  }
}

function Get-GradleCacheRoot {
  if ($script:GradleCacheRootCache) { return $script:GradleCacheRootCache }
  $candidates = @()
  if ($env:GRADLE_USER_HOME) { $candidates += (Join-Path $env:GRADLE_USER_HOME 'caches\modules-2\files-2.1') }
  if ($env:USERPROFILE) { $candidates += (Join-Path $env:USERPROFILE '.gradle\caches\modules-2\files-2.1') }
  foreach ($c in $candidates) { if (Test-Path $c) { $script:GradleCacheRootCache = $c; return $c } }
  $script:GradleCacheRootCache = ''
  return ''
}

function Find-GradleCacheJar([string]$Group, [string]$Artifact) {
  $root = Get-GradleCacheRoot
  if (-not $root) { return $null }
  $artifactDir = Join-Path $root "$Group\$Artifact"
  if (-not (Test-Path $artifactDir)) { return $null }
  return Get-ChildItem -Path $artifactDir -Recurse -File -Filter "$Artifact-*.jar" -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notmatch '(-sources|-javadoc)\.jar$' } |
    Sort-Object FullName -Descending | Select-Object -First 1
}

function Add-JUnitPlatformInfraEntries {
  # SbRunner drives every class through the JUnit Platform Launcher's default
  # ServiceLoader engine auto-registration, so both jupiter (JUnit5) and
  # vintage (JUnit4, if a class needs it) run uniformly. A module's own
  # Gradle testRuntimeClasspath does NOT necessarily include the launcher
  # jar (Gradle's `test` task manages that on its own internal classpath,
  # not the project's), so make it universally available here — same
  # rationale as the Keycloak runner's Add-JUnitPlatformInfraEntries.
  param([System.Collections.Generic.List[string]]$Entries, [hashtable]$Seen)
  $artifacts = @(
    @('org.junit.platform', 'junit-platform-commons'),
    @('org.junit.platform', 'junit-platform-engine'),
    @('org.junit.platform', 'junit-platform-launcher'),
    @('org.junit.jupiter', 'junit-jupiter-api'),
    @('org.junit.jupiter', 'junit-jupiter-engine'),
    @('org.junit.vintage', 'junit-vintage-engine'),
    @('org.opentest4j', 'opentest4j'),
    @('org.apiguardian', 'apiguardian-api'),
    @('junit', 'junit')
  )
  foreach ($pair in $artifacts) {
    $jar = Find-GradleCacheJar -Group $pair[0] -Artifact $pair[1]
    if ($jar) { Add-UniqueClasspathEntry -Entries $Entries -Seen $Seen -Entry $jar.FullName }
  }
}

function ConvertTo-ManifestClasspathUrl([string]$Entry) {
  $full = [System.IO.Path]::GetFullPath($Entry)
  if ((Test-Path $full -PathType Container) -and -not ($full.EndsWith('\') -or $full.EndsWith('/'))) {
    $full += [System.IO.Path]::DirectorySeparatorChar
  }
  return ([System.Uri]::new($full, [System.UriKind]::Absolute)).AbsoluteUri
}

function Split-ManifestLine([string]$Line) {
  $max = 70
  $out = New-Object System.Collections.Generic.List[string]
  if ($Line.Length -le $max) { $out.Add($Line); return @($out) }
  $out.Add($Line.Substring(0, $max))
  $offset = $max
  while ($offset -lt $Line.Length) {
    $take = [Math]::Min($max - 1, $Line.Length - $offset)
    $out.Add(' ' + $Line.Substring($offset, $take))
    $offset += $take
  }
  return @($out)
}

function New-PathingJar {
  param([string]$Module, [string[]]$Entries)
  # -AllModes launches JIT and no-JIT child runners concurrently.  They have
  # the same module classpath signature but must not race over one
  # classpath.jar (one child can observe the other deleting/recreating it).
  # Mode-local wrappers retain caching within a lane while making the two
  # child processes independent.
  $modePath = ConvertTo-SafeName $(if ($script:EffectiveModeName) { $script:EffectiveModeName } else { 'default' })
  $pathingDir = Join-Path (Join-Path $script:WorkRoot 'pathing-jars') $modePath
  New-Item -ItemType Directory -Force -Path $pathingDir | Out-Null
  $signature = 'pathing-jar-manifest-url-v1' + "`n" + (($Entries | ForEach-Object { [System.IO.Path]::GetFullPath($_) }) -join "`n")
  $hash = (Get-Sha256Hex $signature).Substring(0, 16)
  $stem = ConvertTo-SafeFileStem $(if ($Module) { $Module } else { 'universal' })
  # Spring Boot's ModifiedClassPathClassLoader expands the manifest class
  # path only for IntelliJ-style `classpath.jar` files.  The runner needs
  # that expansion for @ClassPathExclusions/@ClassPathOverrides: otherwise
  # it sees this one wrapper JAR instead of the individual dependency JARs.
  # Keep module/content isolation in directories so the wrapper name itself
  # can retain the recognized IntelliJ convention.
  $jarDir = Join-Path (Join-Path $pathingDir $stem) $hash
  $jarPath = Join-Path $jarDir 'classpath.jar'
  if (Test-Path $jarPath) { return [System.IO.Path]::GetFullPath($jarPath) }
  New-Item -ItemType Directory -Force -Path $jarDir | Out-Null

  Add-Type -AssemblyName System.IO.Compression | Out-Null
  Add-Type -AssemblyName System.IO.Compression.FileSystem | Out-Null
  $urls = @($Entries | ForEach-Object { ConvertTo-ManifestClasspathUrl $_ })
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('Manifest-Version: 1.0')
  $lines.Add('Created-By: IntelliJ IDEA')
  $lines.Add('Main-Class: SbRunner')
  foreach ($line in (Split-ManifestLine ('Class-Path: ' + ($urls -join ' ')))) { $lines.Add($line) }
  $lines.Add('')

  if (Test-Path $jarPath) { Remove-Item -LiteralPath $jarPath -Force }
  $zip = [System.IO.Compression.ZipFile]::Open($jarPath, [System.IO.Compression.ZipArchiveMode]::Create)
  try {
    $entry = $zip.CreateEntry('META-INF/MANIFEST.MF')
    $stream = $entry.Open()
    try {
      $writer = [System.IO.StreamWriter]::new($stream, [System.Text.Encoding]::ASCII)
      try { $writer.NewLine = "`r`n"; foreach ($line in $lines) { $writer.WriteLine($line) } } finally { $writer.Dispose() }
    } finally { $stream.Dispose() }
  } finally { $zip.Dispose() }
  return [System.IO.Path]::GetFullPath($jarPath)
}

function Import-ResultRows([string]$Path) {
  if (-not (Test-Path $Path)) { return @() }
  $first = Get-Content -Path $Path -TotalCount 1
  $delimiter = ','
  if ($first -like "*`t*") { $delimiter = "`t" }
  return @(Import-Csv -Path $Path -Delimiter $delimiter)
}

function Select-ClassRange([object[]]$List) {
  $list = @($List)
  $from = [Math]::Max(1, $Start) - 1
  if ($from -ge $list.Count) { return @() }
  $end = $list.Count
  if ($Count -gt 0) { $end = [Math]::Min($list.Count, $from + $Count) }
  return @($list[$from..($end - 1)])
}

function Get-CorruptCellCensus {
  <#
    Read back the `[corrupt-cell] decoded=N reported=M` line every armed
    cratonvm.exe prints from its shutdown trailer.

    The ARMED count is reported separately from the DECODED count on purpose.
    An absent line and a zero line are different claims: the first armed sweep
    run against this suite printed the census in ZERO of 1975 logs -- a JUnit
    runner exits through System.exit, and the summary was on a path it never
    took -- and that run looked exactly like a clean one. Counting the logs that
    actually carried the line is what makes "0 decoded" mean something.
  #>
  param([string]$LogDir)
  $logs = @(Get-ChildItem -Path $LogDir -Filter '*.err.log' -ErrorAction SilentlyContinue)
  $armed = 0; $decoded = 0; $reported = 0; $arrayRecv = 0; $classes = @()
  foreach ($f in $logs) {
    $m = Select-String -Path $f.FullName -Pattern '\[corrupt-cell\] decoded=(\d+) reported=(\d+)' -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $m) { continue }
    $armed++
    $d = [int]$m.Matches[0].Groups[1].Value
    $r = [int]$m.Matches[0].Groups[2].Value
    $decoded += $d; $reported += $r
    # `array_receiver` is the SAME defect one step earlier: a plain-object field
    # access whose receiver is an array, refused at the heap accessor. It is a
    # COUNT where `decoded` is a floor -- the corrupt-cell guard only fires when
    # the striden element bytes happen to form an out-of-range discriminant --
    # so a sweep with `decoded=0 array_receiver=N` has found N producers the
    # guard could not see. Reported separately for that reason.
    $a = Select-String -Path $f.FullName -Pattern '\[corrupt-cell\] array_receiver=(\d+)' -ErrorAction SilentlyContinue | Select-Object -First 1
    $av = 0
    if ($a) { $av = [int]$a.Matches[0].Groups[1].Value; $arrayRecv += $av }
    if ($d -gt 0 -or $av -gt 0) {
      # `<module>.<fqcn>.err.log` -- keep the class, drop the module and suffix.
      $stem = $f.Name -replace '\.err\.log$', ''
      $classes += ("{0}  (decoded={1} named={2} array_receiver={3})" -f $stem, $d, $r, $av)
    }
  }
  return [pscustomobject]@{
    Logs = $logs.Count; Armed = $armed; Unarmed = ($logs.Count - $armed)
    Decoded = $decoded; Reported = $reported; ArrayReceiver = $arrayRecv; Classes = $classes
  }
}

function Resolve-ReferenceFile {
  if ($RefCsv -and (Test-Path $RefCsv)) { return $RefCsv }
  $candidates = @((Join-Path $script:WorkRoot 'reference.tsv'), (Join-Path $script:WorkRoot 'reference.csv'))
  foreach ($candidate in $candidates) { if (Test-Path $candidate) { return $candidate } }
  return ''
}

function Get-RowStatus($Row) {
  if ($Row.PSObject.Properties.Name -contains 'status') { return ([string]$Row.status).ToUpperInvariant() }
  return ''
}

# ---------------------------------------------------------------------------
# HotSpot baseline — reclassifying failures the reference VM shares
# ---------------------------------------------------------------------------
# A `-Vm hotspot` run already writes `<work>/baseline/hotspot-baseline-latest.tsv`,
# but nothing ever read it back, so a class that fails IDENTICALLY on HotSpot was
# still recorded as a plain CratonVM `FAIL`. That is how four
# `loader/spring-boot-jarmode-tools` classes reached `docs/known-issues/` and two
# residual lists as CratonVM defects when the real cause was the Spring Boot
# fixture checkout carrying CRLF expected-output resources against a Linux
# `println` (2026-08-04; HotSpot failed the same tests with the same counts).
#
# Loading the baseline lets those rows be recorded as BOTH-FAIL instead. The
# rule is deliberately conservative -- see `Resolve-BothFailStatus`.
function Import-HotspotBaseline {
  if ($Vm -ne 'craton') { return $null }
  $path = $HotspotBaseline
  if (-not $path) {
    $path = Join-Path (Join-Path $script:WorkRoot 'baseline') 'hotspot-baseline-latest.tsv'
  }
  if (-not (Test-Path $path)) {
    Write-Info "hotspot baseline: none at $path -- every failure will be attributed to CratonVM"
    return $null
  }
  $map = @{}
  foreach ($row in @(Import-Csv -Path $path -Delimiter "`t")) {
    if (-not ($row.PSObject.Properties.Name -contains 'class')) { continue }
    $map["$($row.module)`t$($row.class)"] = [pscustomobject]@{
      status           = Get-RowStatus $row
      failed           = [int]([string]$row.failed  -replace '[^0-9]', '' -replace '^$', '0')
      tests            = [int]([string]$row.tests   -replace '[^0-9]', '' -replace '^$', '0')
      aborted          = [int]([string]$row.aborted -replace '[^0-9]', '' -replace '^$', '0')
      containersFailed = [int]([string]$row.containersFailed -replace '[^0-9]', '' -replace '^$', '0')
    }
  }
  # Say the size out loud: a baseline that silently loaded zero rows is
  # indistinguishable from no baseline at all, and would quietly restore the
  # exact misattribution this exists to prevent.
  Write-Info "hotspot baseline: $($map.Count) classes from $path"
  return $map
}

# `hotspot-baseline-latest.tsv` is what `Import-HotspotBaseline` reads by
# default, and every `-Vm hotspot` run used to blind-copy its own results over
# it. That makes "latest" mean "most recent", not "best", so any ad-hoc
# few-class HotSpot check destroys the coverage of a full-suite one: on
# 2026-08-01 a 5-class run replaced an 81-class baseline, and the reclassifier
# has been running against 5 irrelevant rows ever since -- which is one reason
# host-caused Windows failures kept being attributed to CratonVM.
#
# Merge on `module + class` instead, newest row winning per key, so a narrow
# rerun refreshes the classes it actually covered and leaves the rest standing.
# Returns the resulting class count for the caller to log.
function Merge-HotspotBaselineLatest {
  param([string]$BaselineDir, [string]$ResultsPath)
  $latest = Join-Path $BaselineDir 'hotspot-baseline-latest.tsv'
  $fresh = @(Import-Csv -Path $ResultsPath -Delimiter "`t")
  $merged = [ordered]@{}
  if (Test-Path $latest) {
    foreach ($row in @(Import-Csv -Path $latest -Delimiter "`t")) {
      if (-not ($row.PSObject.Properties.Name -contains 'class')) { continue }
      $merged["$($row.module)`t$($row.class)"] = $row
    }
  }
  foreach ($row in $fresh) {
    if (-not ($row.PSObject.Properties.Name -contains 'class')) { continue }
    $merged["$($row.module)`t$($row.class)"] = $row
  }
  # Write the file the same way every other results TSV in .suite/ is written --
  # a header line plus tab-joined fields. `Export-Csv` would quote every field,
  # and the free-text `note` column routinely contains quotes and tabs of its
  # own, so round-tripping through it corrupts exactly the rows that carry the
  # most diagnostic text. The fresh results file defines the current schema;
  # older rows are projected onto it and any column they lack comes out empty.
  $header = (Get-Content -Path $ResultsPath -TotalCount 1)
  $columns = $header -split "`t"
  $out = New-Object System.Collections.Generic.List[string]
  $out.Add($header)
  $i = 1
  foreach ($row in $merged.Values) {
    $fields = foreach ($col in $columns) {
      if ($col -eq 'index') {
        [string]$i
      } else {
        $v = ''
        if ($row.PSObject.Properties.Name -contains $col) { $v = [string]$row.$col }
        # A stray tab or newline in a note would shift every later column.
        ($v -replace "`t", ' ') -replace "`r|`n", ' '
      }
    }
    $out.Add(($fields -join "`t"))
    $i++
  }
  Set-Content -Path $latest -Value $out -Encoding ascii
  return $merged.Count
}

# Returns 'BOTH-FAIL' when the reference VM fails this class the same way or
# worse, otherwise ''. Conservative on purpose:
#
#   * only a CratonVM `FAIL` is eligible. A CRASH/HANG/LOADFAIL is categorically
#     worse than an assertion failure and must never be excused by one.
#   * the baseline row must itself be `FAIL`, for the same reason in reverse.
#   * CratonVM must not come out WORSE than HotSpot on any counter the `FAIL`
#     verdict is built from. If it fails 5 where HotSpot fails 2, three of
#     those are ours and the row stays `FAIL`.
#
# That last rule has to cover every counter line ~883 tests, not just `failed`.
# Comparing `failed` alone let a row where CratonVM aborted 5 tests and HotSpot
# aborted 1 come out `BOTH-FAIL` on the strength of `0 -gt 0` being false --
# four extra aborts excused by a reference VM that never had them. `aborted` and
# `containersFailed` are what made `ApplicationTempTests` a `FAIL` in the first
# place (`failed=0 aborted=1`), so they are exactly the counters that must be
# compared for this class of row.
#
# Anything that does not qualify keeps its own status and gets the baseline
# appended to its note, so a near-miss is visible rather than silently dropped.
function Resolve-BothFailStatus {
  param(
    [object]$Baseline, [string]$Module, [string]$Class, [string]$Status,
    [int]$Failed, [int]$Aborted, [int]$ContainersFailed
  )
  if (-not $Baseline) { return '' }
  $row = $Baseline["$Module`t$Class"]
  if (-not $row) { return '' }
  if ($Status -ne 'FAIL' -or $row.status -ne 'FAIL') { return '' }
  if ($Failed -gt $row.failed) { return '' }
  if ($Aborted -gt $row.aborted) { return '' }
  if ($ContainersFailed -gt $row.containersFailed) { return '' }
  return 'BOTH-FAIL'
}

# ---------------------------------------------------------------------------
# Host capability gating -- failures the host cannot not have
# ---------------------------------------------------------------------------
# Three Spring Boot classes create symbolic links in test setup:
# `ConfigTreePropertySourceTests` (Kubernetes ConfigMap trees are a `..data`
# directory plus one relative link per key), `ApplicationTempTests`, and
# `FileWatcherTests`. Creating one on Windows needs `SeCreateSymbolicLinkPrivilege`
# -- an elevated token, or Developer Mode. Without it the call fails on ANY VM:
# verified 2026-08-11 on this host, where stock HotSpot (Temurin 25.0.3) fails
# the same calls with the same `FileSystemException`.
#
# All three pass under CratonVM on Linux, where the call needs no privilege
# (2026-08-11: FileWatcherTests 15/15, ConfigTreePropertySourceTests 23/23,
# ApplicationTempTests 7/7, zero skipped or aborted -- i.e. the symlink tests
# genuinely ran).
#
# So on a privilege-less Windows host these rows are a property of the host, not
# a CratonVM defect, and arriving as a plain `FAIL` sent them round a triage loop
# that could not converge: the identical `FAIL 23/3` for
# `ConfigTreePropertySourceTests` appears in at least ten runs between
# 2026-07-27 and 2026-08-01. `Resolve-BothFailStatus` cannot help here -- it
# needs a same-scope HotSpot baseline, and no Windows full-suite HotSpot run has
# ever existed. A capability probe needs no reference VM at all.
function Test-HostSymlinkSupport {
  if ($null -ne $script:HostSymlinkSupport) { return $script:HostSymlinkSupport }
  $probeDir = Join-Path ([System.IO.Path]::GetTempPath()) ("craton-symlink-probe-" + [guid]::NewGuid().ToString('N'))
  $supported = $false
  $detail = ''
  try {
    New-Item -ItemType Directory -Path $probeDir -Force | Out-Null
    $target = Join-Path $probeDir 'target.txt'
    Set-Content -Path $target -Value 'probe' -Encoding ascii
    $link = Join-Path $probeDir 'link.txt'
    try {
      New-Item -ItemType SymbolicLink -Path $link -Target $target -ErrorAction Stop | Out-Null
      $supported = Test-Path $link
    } catch {
      $detail = $_.Exception.Message
    }
  } catch {
    $detail = $_.Exception.Message
  } finally {
    try { Remove-Item -Path $probeDir -Recurse -Force -ErrorAction SilentlyContinue } catch {}
  }
  $script:HostSymlinkSupport = $supported
  if ($supported) {
    Write-Info 'host symlink support: yes -- symlink-dependent classes are scored normally'
  } else {
    # Say it out loud. A probe whose result is never printed is indistinguishable
    # from a probe that never ran, and this one silently reclassifies rows.
    Write-Info "host symlink support: NO (creating a symbolic link failed: $detail) -- symlink-only failures will be recorded as ENV-GATED"
  }
  return $script:HostSymlinkSupport
}

# What a symlink-privilege failure looks like in a per-class log, on BOTH sides
# of the divide it has to span.
#
# Do NOT match the OS's explanation text. It is localized -- on this host the
# Win32 message arrives in Russian and `-Duser.language=en` does not change it,
# because it comes from `FormatMessage`, not from Java. A detector keyed on
# "A required privilege is not held by the client" would silently never fire.
# Match the exception TYPE and the JUnit-sanctioned abort reason instead.
$script:SymlinkGapSignature =
  'java\.nio\.file\.FileSystemException|java\.lang\.UnsupportedOperationException.*[Ss]ymbolic|createSymbolicLink|[Ss]ymlink creation not supported|[Ss]ymbolic links? (are )?not supported'

# Returns 'ENV-GATED' when EVERY non-passing test in this class failed for want
# of the host symlink privilege, otherwise ''.
#
# Deliberately strict, because this status excuses a row:
#
#   * only a plain `FAIL` qualifies. A CRASH/HANG/LOADFAIL is a different
#     category of wrong and is never a host gap.
#   * `containersFailed` disqualifies: a container-level failure is not a
#     per-test symlink refusal.
#   * the number of failure/abort blocks carrying the signature must EQUAL the
#     counter they are explaining. If `failed=3` and only two blocks match, the
#     third failure is ours and the row stays FAIL.
#
# That last rule is also what makes this safe against a stale
# `SbRunner.class`: with no `SBRUNNER_ABORTED_DETAIL` lines emitted, the counts
# cannot match, and the row stays FAIL rather than being excused by evidence
# that was never printed.
function Resolve-EnvGatedStatus {
  # Stdout ONLY, never the combined text. Every SBRUNNER_* marker is printed on
  # stdout, and `$combined` appends stderr AFTER it -- so the last failure block
  # would otherwise swallow the whole of stderr, and a stray `FileSystemException`
  # logged there could satisfy the check for a failure that was nothing of the
  # kind.
  param([string]$Status, [string]$Stdout, [int]$Failed, [int]$Aborted, [int]$ContainersFailed)
  if ($Status -ne 'FAIL') { return '' }
  if ($ContainersFailed -gt 0) { return '' }
  if ($Failed -le 0 -and $Aborted -le 0) { return '' }
  if (Test-HostSymlinkSupport) { return '' }

  if ($Failed -gt 0) {
    # Split on the per-failure marker SbRunner prints, so each failure's own
    # stack trace is checked rather than the whole log at once (one symlink
    # failure must not excuse an unrelated second one). The final block is
    # bounded at the summary line for the same reason.
    $blocks = @([regex]::Split($Stdout, 'SBRUNNER_FAILURE_DETAIL ') | Select-Object -Skip 1)
    if ($blocks.Count -ne $Failed) { return '' }
    foreach ($block in $blocks) {
      $body = ($block -split 'SBRUNNER_RESULT ')[0]
      if ($body -notmatch $script:SymlinkGapSignature) { return '' }
    }
  }
  if ($Aborted -gt 0) {
    $lines = @([regex]::Matches($Stdout, '(?m)^SBRUNNER_ABORTED_DETAIL (.*)$'))
    if ($lines.Count -ne $Aborted) { return '' }
    foreach ($line in $lines) {
      if ($line.Groups[1].Value -notmatch $script:SymlinkGapSignature) { return '' }
    }
  }
  return 'ENV-GATED'
}

function Get-BaselineNote {
  param([object]$Baseline, [string]$Module, [string]$Class)
  if (-not $Baseline) { return '' }
  $row = $Baseline["$Module`t$Class"]
  if (-not $row) { return '' }
  $note = "hotspot-baseline: $($row.status) $($row.failed)/$($row.tests)"
  if ($row.aborted -gt 0 -or $row.containersFailed -gt 0) {
    $note += " aborted=$($row.aborted) containersFailed=$($row.containersFailed)"
  }
  return $note
}

# ---------------------------------------------------------------------------
# gradlew invocation helper
# ---------------------------------------------------------------------------
function Invoke-Gradlew {
  param([string]$Gradlew, [string[]]$GradleArgs)
  # Windows PowerShell 5.1 wraps ANY stderr line from a native process as a
  # terminating NativeCommandError while $ErrorActionPreference = 'Stop' is in
  # effect, even on exit code 0 (Gradle routinely logs benign warnings to
  # stderr). Temporarily relax to 'Continue' and check $LASTEXITCODE instead
  # (same pattern as the tomcat-suite-runner's Invoke-Setup).
  # NOTE: parameter deliberately NOT named $Args -- that collides with
  # PowerShell's automatic $args variable and silently corrupts the splat
  # (gradlew received zero args, defaulted to the `help` task against the
  # wrong project dir, every "Setup" run up to 2026-07-17 was silently
  # discovering 0 classes / regenerating no classpaths despite exit 0).
  $prevEAP = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  # gradlew.bat relies on the CALLER's current directory being the Gradle
  # project root (it does not `cd` into its own location) -- invoking it via
  # `& $Gradlew` from an arbitrary caller cwd (e.g. the CratonVM repo root)
  # fails with "Directory '<cwd>' does not contain a Gradle build" even
  # though $Gradlew's own path is fully qualified. Push into its directory
  # for the duration of the call.
  Push-Location (Split-Path $Gradlew -Parent)
  try {
    & $Gradlew @GradleArgs 2>&1 | ForEach-Object { Write-Host $_ }
    return $LASTEXITCODE
  } finally {
    Pop-Location
    $ErrorActionPreference = $prevEAP
  }
}

# ---------------------------------------------------------------------------
# Setup: compile test classes + generate per-module classpaths (Gradle)
# ---------------------------------------------------------------------------
function Invoke-GradleSetup {
  $jdk = Resolve-Jdk
  $env:JAVA_HOME = $jdk
  $gradlew = Join-Path $script:SpringBootDir 'gradlew.bat'
  if (-not (Test-Path $gradlew)) { Die "gradlew.bat not found: $gradlew" }
  $initScript = Join-Path $script:SpringBootDir 'cratonvm-test-cp.init.gradle'
  if (-not (Test-Path $initScript)) { Die "missing init script: $initScript (dumps per-module test runtime classpaths)" }

  foreach ($subtree in $Subtrees) {
    $dir = Join-Path $script:SpringBootDir $subtree
    if (-not (Test-Path $dir)) { Write-Info "skip missing subtree: $subtree"; continue }
    Write-Info "gradlew -p $subtree testClasses"
    $rc = Invoke-Gradlew -Gradlew $gradlew -GradleArgs @('-p', $dir, 'testClasses', '--no-daemon', '--continue')
    if ($rc -ne 0) { Write-Info "WARNING: testClasses had failures in $subtree (continuing; some modules may be env-gated)" }
    Write-Info "gradlew -p $subtree cratonvmTestCp"
    $rc = Invoke-Gradlew -Gradlew $gradlew -GradleArgs @('-p', $dir, 'cratonvmTestCp', '--init-script', $initScript, '--no-daemon', '--continue')
    if ($rc -ne 0) { Write-Info "WARNING: cratonvmTestCp had failures in $subtree" }
  }
  Build-ClassLists
  Write-Info "Setup complete. classes=$((Get-Content (Join-Path $script:WorkRoot 'all-tests.tsv') | Measure-Object -Line).Lines - 1)"
}

function Build-ClassLists {
  New-Item -ItemType Directory -Force -Path $script:WorkRoot | Out-Null
  $allPath = Join-Path $script:WorkRoot 'all-tests.tsv'
  $passedPath = Join-Path $script:WorkRoot 'passed.tsv'
  $othersPath = Join-Path $script:WorkRoot 'others.tsv'
  $testClassPatterns = @('*Test.class', '*Tests.class', '*IT.class', '*ITCase.class')

  $records = New-Object System.Collections.Generic.List[object]
  foreach ($subtree in $Subtrees) {
    $subtreeDir = Join-Path $script:SpringBootDir $subtree
    if (-not (Test-Path $subtreeDir)) { continue }
    $testDirs = Get-ChildItem -Path $subtreeDir -Recurse -Directory -ErrorAction SilentlyContinue |
      Where-Object { $_.FullName -match '[\\/]build[\\/]classes[\\/](java|kotlin)[\\/]test$' } |
      Sort-Object FullName
    foreach ($dir in $testDirs) {
      # module = project dir (…\<subtree>\<name>), the parent of build\classes\<lang>\test
      $moduleDir = $dir.FullName
      while ($moduleDir -and (Split-Path $moduleDir -Leaf) -ne 'build') { $moduleDir = Split-Path $moduleDir -Parent }
      $moduleDir = Split-Path $moduleDir -Parent
      if (-not $moduleDir) { continue }
      $module = $moduleDir.Substring($script:SpringBootDir.Length + 1) -replace '\\', '/'
      $cpFile = Join-Path $moduleDir 'build\cratonvm-test-cp.txt'
      if (-not (Test-Path $cpFile)) { continue }

      $classes = @(foreach ($pattern in $testClassPatterns) { Get-ChildItem -Path $dir.FullName -Recurse -File -Filter $pattern -ErrorAction SilentlyContinue }) |
        Where-Object { $_.Name -notlike '*$*' -and $_.Name -ne 'AbstractTest.class' } |
        Sort-Object FullName -Unique
      foreach ($classFile in $classes) {
        $rel = $classFile.FullName.Substring($dir.FullName.Length + 1)
        $fqcn = ($rel -replace '\.class$', '') -replace '[\\/]', '.'
        $records.Add([pscustomobject]@{ module = $module; class = $fqcn })
      }
    }
  }

  $unique = $records | Sort-Object module, class -Unique
  "module`tclass" | Set-Content -Path $allPath -Encoding ascii
  foreach ($record in $unique) { "$($record.module)`t$($record.class)" | Add-Content -Path $allPath -Encoding ascii }

  $reference = Resolve-ReferenceFile
  if ($reference) {
    $passedKeys = @{}
    foreach ($row in (Import-ResultRows $reference)) {
      if ((Get-RowStatus $row) -eq 'PASS') { $passedKeys["$($row.module)`t$($row.class)"] = $true }
    }
    "module`tclass" | Set-Content -Path $passedPath -Encoding ascii
    "module`tclass" | Set-Content -Path $othersPath -Encoding ascii
    foreach ($record in $unique) {
      $key = "$($record.module)`t$($record.class)"
      if ($passedKeys.ContainsKey($key)) { "$($record.module)`t$($record.class)" | Add-Content -Path $passedPath -Encoding ascii }
      else { "$($record.module)`t$($record.class)" | Add-Content -Path $othersPath -Encoding ascii }
    }
    Write-Info "class lists refreshed: all=$($unique.Count), passed=$((Import-Csv $passedPath -Delimiter "`t").Count), others=$((Import-Csv $othersPath -Delimiter "`t").Count)"
  } else {
    Write-Info "class list refreshed: all=$($unique.Count); no reference found for passed/others split"
  }
}

function Import-ClassRows([string]$Path) {
  if (-not (Test-Path $Path)) { Die "class list not found: $Path" }
  return @(Import-ResultRows $Path)
}

function Get-SelectedClasses {
  $allPath = Join-Path $script:WorkRoot 'all-tests.tsv'
  $passedPath = Join-Path $script:WorkRoot 'passed.tsv'
  $othersPath = Join-Path $script:WorkRoot 'others.tsv'

  if ($ClassList) { return Select-ClassRange (Import-ClassRows $ClassList) }
  if ($RefreshLists -or -not (Test-Path $allPath)) { Build-ClassLists }

  $resolvedCategory = $Category
  if ($resolvedCategory -eq 'failed') { $resolvedCategory = 'others' }
  $source = $allPath
  if ($resolvedCategory -eq 'passed') { $source = $passedPath }
  if ($resolvedCategory -eq 'others') { $source = $othersPath }
  if (-not (Test-Path $source)) {
    if (-not (Resolve-ReferenceFile)) { Die "category '$Category' needs a reference result file. Pass -RefCsv, or run -Category all first." }
    Build-ClassLists
  }
  if (-not (Test-Path $source)) { Die "class list not found: $source" }
  return Select-ClassRange (Import-Csv -Path $source -Delimiter "`t")
}

# ---------------------------------------------------------------------------
# Classpath resolution (per module, cached)
# ---------------------------------------------------------------------------
function Get-ModuleClasspathEntries {
  param([string]$Module)
  if (-not $script:ModuleClasspathCache) { $script:ModuleClasspathCache = @{} }
  if ($script:ModuleClasspathCache.ContainsKey($Module)) { return @($script:ModuleClasspathCache[$Module]) }

  $modulePath = $Module -replace '/', '\'
  $moduleRoot = Join-Path $script:SpringBootDir $modulePath
  $cpFile = Join-Path $moduleRoot 'build\cratonvm-test-cp.txt'
  if ($RefreshClasspaths -or -not (Test-Path $cpFile)) {
    $jdk = Resolve-Jdk
    $env:JAVA_HOME = $jdk
    $gradlew = Join-Path $script:SpringBootDir 'gradlew.bat'
    $initScript = Join-Path $script:SpringBootDir 'cratonvm-test-cp.init.gradle'
    $projPath = ':' + ($Module -replace '/', ':')
    Write-Info "refreshing classpath for $Module"
    Invoke-Gradlew -Gradlew $gradlew -GradleArgs @("${projPath}:cratonvmTestCp", '--init-script', $initScript, '--no-daemon', '--continue') | Out-Null
  }
  if (-not (Test-Path $cpFile)) { Die "missing classpath file: $cpFile (run -Setup or -RefreshClasspaths first)" }

  $entries = New-Object System.Collections.Generic.List[string]
  $seen = @{}
  Add-UniqueClasspathEntry -Entries $entries -Seen $seen -Entry $script:SbRunnerDir
  foreach ($entry in (Split-ClasspathEntries ((Get-Content -Path $cpFile -Raw).Trim()))) {
    Add-UniqueClasspathEntry -Entries $entries -Seen $seen -Entry $entry
  }
  Add-JUnitPlatformInfraEntries -Entries $entries -Seen $seen

  $result = @($entries)
  $script:ModuleClasspathCache[$Module] = $result
  return $result
}

function Get-LaunchSpec {
  param([object]$ClassRow)
  $module = [string]$ClassRow.module
  $entries = @(Get-ModuleClasspathEntries -Module $module)
  $separator = [string][System.IO.Path]::PathSeparator
  $cp = ($entries -join $separator)
  $usePathingJar = ([System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT) -and ($cp.Length -gt 24000)
  if ($usePathingJar) {
    $jar = New-PathingJar -Module $module -Entries $entries
    return [pscustomobject]@{ kind = 'jar'; value = $jar; entries = $entries.Count; length = $cp.Length }
  }
  return [pscustomobject]@{ kind = 'cp'; value = $cp; entries = $entries.Count; length = $cp.Length }
}

function Resolve-CratonExe {
  if ($Exe) { if (-not (Test-Path $Exe)) { Die "CratonVM executable not found: $Exe" }; return [System.IO.Path]::GetFullPath($Exe) }
  if ($env:CV_BIN -and (Test-Path $env:CV_BIN)) { return [System.IO.Path]::GetFullPath($env:CV_BIN) }
  if ($env:CRATONVM_SPRING_BOOT_EXE -and (Test-Path $env:CRATONVM_SPRING_BOOT_EXE)) { return [System.IO.Path]::GetFullPath($env:CRATONVM_SPRING_BOOT_EXE) }

  $unique = Join-Path $script:RepoRoot 'target\release\cratonvm-spring-boot-suite.exe'
  if (Test-Path $unique) { return [System.IO.Path]::GetFullPath($unique) }
  $generic = Join-Path $script:RepoRoot 'target\release\cratonvm.exe'
  if (Test-Path $generic) {
    New-Item -ItemType Directory -Force -Path (Split-Path $unique) | Out-Null
    Copy-Item -Path $generic -Destination $unique -Force
    Write-Info "copied generic cratonvm.exe to unique runner binary: $unique"
    return [System.IO.Path]::GetFullPath($unique)
  }
  Die "CratonVM executable not found. Pass -Exe or set CV_BIN/CRATONVM_SPRING_BOOT_EXE."
}

function Resolve-Jdk {
  if ($JdkHome) { return $JdkHome }
  if ($env:JAVA_HOME -and (Test-Path $env:JAVA_HOME)) { return $env:JAVA_HOME }
  $cands = @(
    'C:\Program Files\Eclipse Adoptium\jdk-25.0.3.9-hotspot',
    'C:\Program Files\Java\jdk-25'
  )
  foreach ($c in $cands) { if (Test-Path $c) { return $c } }
  return 'C:\Program Files\Eclipse Adoptium\jdk-25.0.3.9-hotspot'
}

function Get-EffectiveClassTimeoutSec {
  param([object]$ClassRow, [int]$BaseTimeoutSec)
  # This HSQLDB integration class creates and exercises several database-backed
  # application contexts.  After the Array.set fix it completes under Craton,
  # but its validated JIT-on time is about 14 minutes.  Keep the suite's
  # ordinary 300-second default for other classes while preventing this known
  # slow class from being reported as the old RangeGroupEmpty hang.
  if ($ClassRow.module -eq 'module/spring-boot-session-jdbc' -and
      $ClassRow.class -eq 'org.springframework.boot.session.jdbc.autoconfigure.JdbcSessionAutoConfigurationTests') {
    return [Math]::Max($BaseTimeoutSec, 900)
  }
  # 2026-07-17 contextrunner-resource-cycle-then-silent-stall-cluster investigation:
  # these 5 classes were originally misclassified as HANG at the standard 300s
  # shard timeout. A live CPU-sampled repro (single OS thread pegged near 100%
  # continuously, no thread ever genuinely parked) proved none of them are
  # deadlocked -- they are just slow (heavy reflection/annotation-scanning plus,
  # pre-fix, extra work from the since-fixed Class.getMethods() override-shadowing
  # bug). Each was run standalone to natural completion (FAIL, with real residual
  # test failures unrelated to hanging -- see
  # docs/known-issues/springboot/ for the specific residual docs) and the
  # validated wall-clock times below include headroom over the observed time.
  # See springboot/contextrunner-resource-cycle-then-silent-stall-cluster-FIXED.md.
  $slowClasses = @{
    'module/spring-boot-cache|org.springframework.boot.cache.autoconfigure.CacheAutoConfigurationTests' = 600
    # Hibernate's complete JPA auto-configuration class is CPU-bound and has
    # completed naturally in roughly 9.5 minutes under both Craton execution
    # modes. Keep the ordinary 300-second default for every other class, but
    # leave enough headroom for real failure reporting instead of labelling the
    # class as a hang before its result is available.
    'module/spring-boot-hibernate|org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfigurationTests' = 1200
    'module/spring-boot-security|org.springframework.boot.security.autoconfigure.actuate.web.servlet.JerseyEndpointRequestIntegrationTests' = 600
    'module/spring-boot-security|org.springframework.boot.security.autoconfigure.actuate.web.servlet.MvcEndpointRequestIntegrationTests' = 700
    'module/spring-boot-security|org.springframework.boot.security.autoconfigure.actuate.web.reactive.EndpointRequestIntegrationTests' = 1000
    'module/spring-boot-micrometer-tracing-opentelemetry|org.springframework.boot.micrometer.tracing.opentelemetry.autoconfigure.OpenTelemetryTracingAutoConfigurationTests' = 1400
    # WEBMVC.1 (2026-07-18): these are not deadlocks. An explicit 180-second
    # Craton watchdog captured WebMvcAutoConfigurationTests actively executing
    # Spring context creation/property binding on CPU; its 93 methods create
    # many independent contexts. BasicErrorControllerIntegrationTests likewise
    # repeatedly boots and tears down embedded Tomcat. Keep enough room for the
    # actual JUnit result instead of reporting a false 300-second HANG.
    'module/spring-boot-webmvc|org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfigurationTests' = 7200
    'module/spring-boot-webmvc|org.springframework.boot.webmvc.autoconfigure.error.BasicErrorControllerIntegrationTests' = 1800
    # SPRING-TESTCOMPILER.1 (2026-07-18): these processor tests repeatedly
    # compile fixture sources in-process through the real JDK javac. They are
    # CPU-bound and silent until JUnit has completed all fixture compilations;
    # a 300-second shard limit therefore reports a false HANG. The representative
    # 65-test annotation-processor class completed in 629.68s with JIT and
    # 680.00s with --nojit. Keep enough headroom to report its actual result.
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.ConstructorParameterPropertyDescriptorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.EndpointMetadataGenerationTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.JavaBeanPropertyDescriptorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.LombokPropertyDescriptorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.MergeMetadataGenerationTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.PropertyDescriptorResolverTests' = 1200
    # RABBIT-CGLIB.1 (2026-07-20): originally reported as a HANG
    # (docs/known-issues/springboot/rabbitautoconfigurationtests-cglib-enhance-hang.md)
    # because the log's last line was a CGLIB `@Configuration` enhancement
    # right before the standard 300s shard timeout killed the process. A
    # CPU-sampled standalone repro (same technique as the contextrunner
    # cluster above: `Get-Process` thread `TotalProcessorTime` growing
    # ~1 CPU-second per wall-second continuously, no thread ever parked)
    # proved this is not a deadlock -- the class's 78 tests each build and
    # tear down a full Spring context (many with CGLIB `@Configuration`
    # proxies and fresh Mockito/ByteBuddy mocks), which is genuinely
    # CPU-heavy under CratonVM. Run to natural completion in 470.1s
    # (`Test run finished after 470134 ms`, 76/78 passed). Keep headroom
    # above that observed time instead of reporting a false HANG.
    # STALE since the fixture renamed this module: the class is now
    # `module/spring-boot-rabbitmq|org.springframework.boot.rabbitmq.autoconfigure.RabbitAutoConfigurationTests`,
    # so this key has matched nothing and the 900s budget was never applied to
    # the class it was written for. Kept in case an older fixture checkout is
    # used; the live key is in .suite/class-timeouts.tsv.
    'module/spring-boot-amqp|org.springframework.boot.amqp.autoconfigure.RabbitAutoConfigurationTests' = 900
    # JACKSON-BUDGET.1 (2026-08-05): this class has been reported as a HANG at
    # the standard 300s shard timeout in every full-suite run that did not
    # instead report a correctness failure -- `08-02 HANG 300.140s`, and the
    # 2026-07-22 severe-slowdown page before it. It is not stuck. With the
    # recycled-`JitInvokeInfo` dispatch aliasing fixed (`383e7f5cf`, see
    # fixed-suite-bugs/springboot/jacksonautoconfigurationtests-disabledcondition-npe-FIXED-20260805.md)
    # it runs to natural completion with all 162 tests, 0 failed, 0
    # containersFailed: 336s and 343s on the Azure host at load average ~30,
    # 308s on Windows. That is 11-15x the HotSpot baseline (22.4s) and simply
    # does not fit 300s. Carve out headroom so the suite reports what actually
    # happens instead of a false HANG; the ratio itself belongs to the
    # Spring-bootstrap throughput work, not to a per-class timeout.
    'module/spring-boot-jackson|org.springframework.boot.jackson.autoconfigure.JacksonAutoConfigurationTests' = 900
    # CORE39-CLUSTERA.1 (2026-07-23): originally reported as a HANG at the
    # standard 300s shard timeout. A 900s standalone repro (single OS thread,
    # JIT on) proved this is not a deadlock -- it completes on its own in
    # 386.8s, PASS. The class exercises many individual `@Test` methods (each
    # a fresh YAML-loader parse), and JUnit5's own extension-registry /
    # interceptor-chain machinery multiplies CratonVM's per-call dispatch cost
    # across all of them (see reference_junit5_execution_machinery_dispatch_overhead
    # in project memory) -- CPU-bound, not stuck. Keep headroom above the
    # observed time (extra margin for contention when run alongside other
    # slow classes in the same -Parallel batch) instead of reporting a false
    # HANG.
    'core/spring-boot|org.springframework.boot.env.OriginTrackedYamlLoaderTests' = 1100
    # CORE39-CLUSTERA.2 (2026-07-24): ConfigurationPropertySourcesTests was
    # reported as a HANG at 300s. Extensive diagnosis (CPU-sampling across
    # multiple stack dumps at 60s/400s/1100s -- pegged near 100% CPU
    # throughout, never parked/blocked; a hand-scaled-down repro of its own
    # perf-test shape -- N property sources x M keys x K
    # `environment.getProperty()` iterations -- measured CONSTANT
    # per-iteration cost, ~47ms/iter at 5 sources x 1000 keys, no quadratic
    # growth across 20-iteration buckets, confirmed linear not superlinear
    # scaling) all point to a real but DIFFUSE interpreter/dispatch
    # throughput gap, not a deadlock -- consistent with the already-tracked
    # reference_hashmap_native_call_dispatch_overhead /
    # reference_junit5_execution_machinery_dispatch_overhead family in
    # project memory. The class deliberately exercises an "uncached"
    # O(sources x keys) baseline against ~100 property sources x 1000 keys x
    # 1000 iterations (explicit `cached < uncached/2` perf assertions) --
    # genuinely CPU-heavy by design, not merely slow-to-start. A standalone
    # rerun completed (PASS) in 2645.0s; keep headroom above that observed
    # time instead of reporting a false HANG.
    #
    # NOTE: `ConfigurationPropertiesBeanRegistrationAotProcessorTests` (the
    # other class originally reported alongside this one) is DELIBERATELY
    # NOT in this table -- unlike this class, it never completed even at a
    # 7200s (2-hour) ceiling with ZERO of its 9 `@Test` methods reporting a
    # result, and a CPU-sampled stack repeatedly lands at the identical
    # bytecode offset in Hibernate Validator's
    # `BeanMetaDataImpl.getClassLevelConstraintsAsDescriptors` across samples
    # taken minutes and hours apart -- a real, still-unfixed hang, not a
    # throughput gap. Do not paper over it with a timeout; see
    # docs/known-issues/springboot/configurationpropertiesbeanregistrationaotprocessortests-hang.md.
    'core/spring-boot|org.springframework.boot.context.properties.source.ConfigurationPropertySourcesTests' = 5400
    # EMBEDDED-SERVER-BUDGET.1 (2026-08-11): these two build, start and stop a
    # fresh embedded container per @Test -- 121 (Tomcat) and ~100 (Jetty)
    # container starts in one process, each of which runs Jasper's whole TLD
    # scan over the module's 130-jar test classpath. Both were reported as
    # HANG at 300s in every full-suite run since 2026-08-06, and the Jetty one
    # once as `tests=0` at a 2400s ceiling. Neither is stuck. Measured alone
    # on an idle Windows host, default collector, -Xmx 2g, after the
    # JarFile-accessor stat fix landed:
    #   Tomcat 420.2s, 132 tests, 0 failed   (HotSpot 41.1s / 129 tests)
    #   Jetty  407.0s, 113 tests, 0 failed   (HotSpot 28.6s / 111 tests)
    # -- see fixed-suite-bugs/springboot/tomcat-jetty-servletwebserverfactorytests-300s-budget-overrun-FIXED-20260811.md.
    # The 10-14x ratio is a real throughput item and is tracked as one
    # (known-issues/tomcat/!webapp-deploy-annotation-scan-interpreted-226x.md);
    # this entry exists so the suite reports 132/132 and 113/113 instead of a
    # HANG, not to hide the ratio. Headroom over the observed time for
    # contention when several slow classes share a -Parallel batch.
    'module/spring-boot-tomcat|org.springframework.boot.tomcat.servlet.TomcatServletWebServerFactoryTests' = 900
    'module/spring-boot-jetty|org.springframework.boot.jetty.servlet.JettyServletWebServerFactoryTests' = 900
    # PULSAR-BUDGET.1 (2026-08-11): reported as a deterministic 300s HANG in
    # the three 2026-08-06/07 full-suite runs. It is not stuck -- the evidence
    # for "hang" was a 0-byte .out.log (SbRunner prints nothing until the run
    # finishes, and this class logs nothing of its own) and an identical last
    # .err.log line, which is the last line of every PASSING run of this class
    # too. Alone on an idle host it completes 74/74 in 178-204s, and 220-277s
    # when sharing the box -- right on the 300s boundary, which is why the
    # suite has always seen it flip between HANG and PASS. See
    # fixed-suite-bugs/springboot/pulsarautoconfigurationtests-onbeancondition-multivaluemap-classcastexception-flake-FIXED-20260811.md.
    'module/spring-boot-pulsar|org.springframework.boot.pulsar.autoconfigure.PulsarAutoConfigurationTests' = 900
  }
  # The same budgets, in a form the Linux shard driver can read too
  # (`linux-oracles/run-sb-gc-shard.sh`). The ad-hoc copy of that driver which
  # ran the 2026-08-19 three-collector sweep re-implemented the launch and
  # dropped this table entirely, so every class above the 300-second default
  # came back HANG -- eight of the nine HANG rows in the 2026-08-21 re-run,
  # all of which pass with test counts identical to HotSpot once given the
  # budget already recorded here. One table, two readers, so that cannot
  # recur. The file wins where both define a key; the inline table above
  # remains the fallback, so a missing file changes nothing.
  $timeoutsFile = Join-Path $PSScriptRoot '.suite/class-timeouts.tsv'
  if (Test-Path -LiteralPath $timeoutsFile) {
    foreach ($row in @(Import-Csv -LiteralPath $timeoutsFile -Delimiter "`t")) {
      if (-not $row.module -or -not $row.class) { continue }
      $seconds = 0
      if ([int]::TryParse([string]$row.seconds, [ref]$seconds) -and $seconds -gt 0) {
        $slowClasses["$($row.module)|$($row.class)"] = $seconds
      }
    }
  }
  $key = "$($ClassRow.module)|$($ClassRow.class)"
  if ($slowClasses.ContainsKey($key)) {
    return [Math]::Max($BaseTimeoutSec, $slowClasses[$key])
  }
  return $BaseTimeoutSec
}

function New-ProcessRecord {
  param([object]$ClassRow, [string]$ModeOut, [object]$LaunchSpec, [string]$ExePath, [string]$JavaExe, [string]$JdkPath, [bool]$NoJit, [int]$Timeout, [int]$Retries = 0)
  $module = [string]$ClassRow.module
  $class = [string]$ClassRow.class
  $workingDirectory = $script:SpringBootDir
  $modulePath = $module -replace '/', [System.IO.Path]::DirectorySeparatorChar
  $moduleRoot = Join-Path $script:SpringBootDir $modulePath
  if (Test-Path $moduleRoot) { $workingDirectory = $moduleRoot }
  $logDir = Join-Path $ModeOut 'logs'
  New-Item -ItemType Directory -Force -Path $logDir | Out-Null
  # `WriteAllText` still observes the legacy MAX_PATH limit on some Windows
  # PowerShell/.NET Framework combinations.  Worktree and run names are both
  # intentionally unique and can be long, so size the per-class stem from the
  # actual log-directory prefix rather than assuming the historical 96-char
  # cap always leaves room for the extension.
  $maxStemLength = [Math]::Max(16, 240 - $logDir.Length - '.out.log'.Length - 1)
  $safe = ConvertTo-SafeFileStem "$module.$class" -MaxLength $maxStemLength
  $outFile = Join-Path $logDir "$safe.out.log"
  $errFile = Join-Path $logDir "$safe.err.log"

  # Several modules' own build.gradle add --add-opens=java.base/java.net=ALL-UNNAMED
  # to their Gradle `test` task JVM args (jetty/security/servlet/tomcat/webflux/
  # websocket -- reflective field reset in their web-server test fixtures, via
  # @DirtiesUrlFactories -> ReflectionTestUtils.setField(URL.class, "factory", null)).
  # This runner launches SbRunner directly instead of through Gradle's test task,
  # so none of those per-module jvmArgs apply; without it those classes fail with
  # "IllegalStateException: Unable to reset field", which is a harness gap, not a
  # genuine VM behavior difference. Apply it universally -- opens are additive and
  # harmless for modules that don't need it.
  #
  # "Universally" has to mean BOTH launch arms, and for three weeks it did not:
  # the flag was added (948df715a, 2026-07-17) to the hotspot branch only,
  # deliberately, because CratonVM did not enforce the module boundary at all and
  # the flag was moot there. Commit 7c92363bd (2026-08-06) closed that
  # encapsulation hole, and the same seven-plus classes that had always needed the
  # flag on HotSpot started failing 100% on CratonVM -- a harness asymmetry that
  # had been invisible only because the VM was wrong in a compensating direction.
  # Keep the argument in one variable so a future arm cannot silently omit it. See
  # fixed-suite-bugs/springboot/dirtiesurlfactories-craton-launcher-missing-add-opens-FIXED-20260809.md.
  $addOpensJavaNet = '--add-opens=java.base/java.net=ALL-UNNAMED'

  if ($Vm -eq 'hotspot') {
    $file = $JavaExe
    $args = @("-Xmx$MaxHeap", '-Dfile.encoding=UTF-8', '-Djava.awt.headless=true', $addOpensJavaNet)
    if ($NoJit) { $args += '-Xint' }
    if ($LaunchSpec.kind -eq 'jar') { $args += @('-jar', $LaunchSpec.value, $class) }
    else { $args += @('-cp', $LaunchSpec.value, 'SbRunner', $class) }
  } else {
    $file = $ExePath
    $args = @('--java-home', $JdkPath, '--Xmx', $MaxHeap, $addOpensJavaNet)
    # The suite normally disables the VM watchdog because it owns the
    # per-class timeout.  Preserve that default, but let a caller provide a
    # real watchdog value through -CratonArgs for a diagnostic run.
    $hasWatchdogArg = @($CratonArgs | Where-Object { $_ -match '^--stack-dump-on-timeout(?:=|$)' }).Count -gt 0
    if (-not $hasWatchdogArg) { $args += @('--stack-dump-on-timeout', '0') }
    if ($NoJit) { $args += '--nojit' }
    if ($CratonArgs.Count -gt 0) { $args += $CratonArgs }
    $args += @('-Dfile.encoding=UTF-8', '-Djava.awt.headless=true')
    if ($LaunchSpec.kind -eq 'jar') { $args += @('--jar', $LaunchSpec.value, $class) }
    else { $args += @('-cp', $LaunchSpec.value, 'SbRunner', $class) }
  }

  $psi = [System.Diagnostics.ProcessStartInfo]::new()
  $psi.FileName = $file
  $psi.WorkingDirectory = $workingDirectory
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  # Spring Boot's JUL formatter deliberately treats LOG_FORMAT as an
  # application-facing override.  Letting a developer's ambient value leak
  # into every direct JUnit launch changes assertions that exercise its
  # documented default format (for example JavaLoggingSystemTests), and makes
  # the CratonVM/HotSpot comparison host-dependent.  The runner owns a
  # hermetic test-process environment, so remove only this formatter override;
  # individual tests can still set the Java system property explicitly.
  [void]$psi.Environment.Remove('LOG_FORMAT')
  Set-ProcessArguments -StartInfo $psi -Arguments $args
  $proc = [System.Diagnostics.Process]::new()
  $proc.StartInfo = $psi
  [void]$proc.Start()
  return [pscustomobject]@{
    proc = $proc
    stdoutTask = $proc.StandardOutput.ReadToEndAsync()
    stderrTask = $proc.StandardError.ReadToEndAsync()
    module = $module; class = $class; start = Get-Date
    outFile = $outFile; errFile = $errFile; timeoutSec = $Timeout; retries = $Retries
  }
}

function Read-ProcessOutputs([object]$Record) {
  try { $Record.stdoutTask.Wait(5000) | Out-Null } catch {}
  try { $Record.stderrTask.Wait(5000) | Out-Null } catch {}
  $stdout = ''; $stderr = ''
  try { $stdout = $Record.stdoutTask.Result } catch {}
  try { $stderr = $Record.stderrTask.Result } catch {}
  return [pscustomobject]@{ stdout = $stdout; stderr = $stderr }
}

function Complete-ProcessRecord {
  param([object]$Record, [string]$ResultPath, [object]$ExitCode, [double]$Seconds, [string]$Stdout, [string]$Stderr)
  [System.IO.File]::WriteAllText($Record.outFile, $Stdout, [System.Text.Encoding]::UTF8)
  [System.IO.File]::WriteAllText($Record.errFile, $Stderr, [System.Text.Encoding]::UTF8)
  $combined = "$Stdout`n$Stderr"
  $status = 'NOSUMMARY'; $tests = 0; $failed = 0; $aborted = 0; $skipped = 0; $containersFailed = 0

  if ([string]$ExitCode -eq 'TIMEOUT') {
    $status = 'HANG'
  } elseif ($combined -match '(?i)EXCEPTION_ACCESS_VIOLATION|SIGSEGV|fatal runtime error|panicked at|stack smashing|illegal instruction|STATUS_ACCESS|STATUS_STACK_BUFFER|caught fatal signal|cratonvm panic|internal error: entered unreachable') {
    $status = 'CRASH'
  }

  $m = [regex]::Match($combined, 'SBRUNNER_RESULT tests=(\d+) failed=(\d+) aborted=(\d+) skipped=(\d+) containersFailed=(\d+)')
  if ($m.Success) {
    $tests = [int]$m.Groups[1].Value; $failed = [int]$m.Groups[2].Value; $aborted = [int]$m.Groups[3].Value
    $skipped = [int]$m.Groups[4].Value; $containersFailed = [int]$m.Groups[5].Value
    if ($status -ne 'CRASH' -and $status -ne 'HANG') {
      if ($combined -match 'SBRUNNER_LOAD_FAIL') { $status = 'LOADFAIL' }
      elseif ($failed -gt 0 -or $aborted -gt 0 -or $containersFailed -gt 0) { $status = 'FAIL' }
      elseif ($tests -eq 0) { $status = 'EMPTY' }
      else { $status = 'PASS' }
    }
  } elseif ($status -ne 'HANG' -and $status -ne 'CRASH' -and $ExitCode -ne 0) {
    $status = 'CRASH'
  }

  $note = ''
  if ($status -ne 'PASS' -and $status -ne 'EMPTY') {
    $noteMatch = [regex]::Match($combined, '(?im)^(?!\s+at\s)(.*(?:Exception|Error|Caused by|SBRUNNER_LOAD_FAIL|panicked|not implemented|NoClassDef|NoSuchMethod|AbstractMethod|AssertionError).*)$')
    if ($noteMatch.Success) { $note = (($noteMatch.Groups[1].Value -replace "`t", ' ') -replace "`r|`n", ' ') }
  }
  # Record how far the [moving-young] GC fallback escalated, because that count
  # is what distinguishes the two very different rows that both surface as a
  # 300s HANG:
  #
  #   * a handful of fallbacks is harmless -- FlywayAutoConfigurationTests hits
  #     7 and still completes (496s standalone, 73/73);
  #   * a count in the thousands is a death spiral -- the young free list
  #     fragments until allocation fails. IntegrationAutoConfigurationTests
  #     reaches #16384 and dies of OutOfMemoryError after 3.8 HOURS;
  #     QuartzEndpointWebIntegrationTests reaches #4096 and does not finish in
  #     2400s. Both pass in ~220-260s under `--nojit`, with zero fallbacks.
  #
  # Without this, all three read as "the class is slow, raise its timeout" --
  # which is the wrong fix for the latter two and costs a multi-hour standalone
  # rerun to discover. Same mechanism as the ZipContentTests OOM (512
  # consecutive fallbacks, clean under `--nojit`).
  $fallbacks = [regex]::Matches($combined, '\[moving-young\] fallback #(\d+)')
  if ($fallbacks.Count -gt 0) {
    $peak = 0
    foreach ($m in $fallbacks) {
      $n = [int]$m.Groups[1].Value
      if ($n -gt $peak) { $peak = $n }
    }
    $reason = ''
    $rm = [regex]::Match($combined, '\[moving-young\] fallback #\d+: reason=([a-z-]+)')
    if ($rm.Success) { $reason = " $($rm.Groups[1].Value)" }
    $gcNote = "moving-young-fallback peak=#$peak$reason"
    $note = if ($note) { "$gcNote | $note" } else { $gcNote }
  }
  # Truncate AFTER the GC note is prepended, so a long exception string cannot
  # push the fallback count out of the row.
  if ($note.Length -gt 240) { $note = $note.Substring(0, 240) }

  # Reclassify a failure the reference VM shares, and in every other case still
  # record what HotSpot did, so a row that stayed FAIL despite a failing
  # baseline (a crash, or more failed tests than HotSpot) shows why.
  if ($status -ne 'PASS' -and $status -ne 'EMPTY') {
    $baselineNote = Get-BaselineNote -Baseline $script:HotspotBaselineMap -Module $Record.module -Class $Record.class
    $bothFail = Resolve-BothFailStatus -Baseline $script:HotspotBaselineMap -Module $Record.module `
      -Class $Record.class -Status $status -Failed $failed -Aborted $aborted -ContainersFailed $containersFailed
    if ($bothFail) { $status = $bothFail }
    if ($baselineNote) { $note = if ($note) { "$note | $baselineNote" } else { $baselineNote } }
    # Host-capability gating runs after the baseline reclassifier and can still
    # apply to a row the baseline left alone: it needs no reference VM, which
    # matters because no Windows full-suite HotSpot baseline has ever existed.
    $envGated = Resolve-EnvGatedStatus -Status $status -Stdout $Stdout `
      -Failed $failed -Aborted $aborted -ContainersFailed $containersFailed
    if ($envGated) {
      $status = $envGated
      $gateNote = 'env-gated: host cannot create symbolic links (needs SeCreateSymbolicLinkPrivilege or Developer Mode); stock HotSpot fails these same tests here'
      $note = if ($note) { "$gateNote | $note" } else { $gateNote }
      if ($note.Length -gt 240) { $note = $note.Substring(0, 240) }
    }
  }

  $line = @(
    $script:ResultIndex, $Record.module, $Record.class, $Vm, $(if ($Jit -eq 'off') { 'off' } else { 'on' }),
    $ExitCode, $status, (ConvertTo-InvariantString $Seconds), $tests, $failed, $aborted, $skipped, $containersFailed,
    $Record.outFile, $Record.errFile, $note
  ) -join "`t"
  Add-Content -Path $ResultPath -Value $line -Encoding ascii
  $script:ResultIndex++
  Write-Host ("  [{0}] {1,-9} {2,7:N1}s {3}.{4}" -f $script:EffectiveModeName, $status, $Seconds, $Record.module, $Record.class)
}

function Invoke-Mode {
  param([object[]]$Classes)
  $script:HotspotBaselineMap = Import-HotspotBaseline
  $jdk = Resolve-Jdk
  $javaBin = Join-Path $jdk 'bin'
  $java = @((Join-Path $javaBin 'java.exe'), (Join-Path $javaBin 'java')) | Where-Object { Test-Path $_ } | Select-Object -First 1
  if (-not $java) { Die "HotSpot java executable not found under: $javaBin" }
  $craton = ''
  if ($Vm -eq 'craton') {
    $craton = Resolve-CratonExe
    # Matches tomcat-suite-runner's craton knobs. CRATONVM_REAL_NET_SOCKETS in
    # particular is load-bearing here: without it, java.net.ServerSocket uses
    # the legacy synthetic layout whose field-slot mapping doesn't match the
    # real JDK-25 class (declaration order impl@0/created@1/bound@2/closed@3/
    # socketLock@4/options@5), so socketLock reads back null and any real
    # bind (Hazelcast, embedded servers, etc.) throws
    # "NullPointerException: Cannot enter synchronized block because
    # this.socketLock is null" — see docs/known-issues (reference_server_socket_gap
    # in memory) for the full history; this is a known, already-fixed-behind-
    # a-flag issue, not something to re-report as a new bug.
    $env:CRATONVM_REAL = 'net-sockets,aqs'
    $env:CRATONVM_THREADS = '-default-watchdog'
    $env:CRATONVM_JIT = 'rootsnap-cache'
    # Corrupt-`Value`-cell census -- see `-NoCorruptCellCensus`. Armed here so
    # every child cratonvm.exe inherits it; the per-class cost is one line of
    # stderr, and `decoded=0` is what makes a quiet run a MEASUREMENT rather
    # than an absence of one.
    if ($NoCorruptCellCensus) {
      $env:CRATONVM_DBG_CORRUPT_CELL = $null
    } else {
      $env:CRATONVM_DBG_CORRUPT_CELL = '1'
    }
  }

  $run = $RunName
  if (-not $run) { $run = Get-Date -Format 'yyyyMMdd-HHmmss' }
  $mode = $ModeName
  if (-not $mode) {
    if ($Vm -eq 'hotspot') { $mode = if ($Jit -eq 'off') { 'hotspot-xint' } else { 'hotspot-jit' } }
    else { $mode = "$Category-$(if ($Jit -eq 'off') { 'nojit' } else { 'jit' })" }
  }
  $script:EffectiveModeName = $mode

  $modeOut = Join-Path (Join-Path (Join-Path $script:WorkRoot 'results') $run) $mode
  New-Item -ItemType Directory -Force -Path $modeOut | Out-Null
  $results = Join-Path $modeOut 'results.tsv'
  if (-not (Test-Path $results)) {
    "index`tmodule`tclass`tvm`tjit`trc`tstatus`tseconds`ttests`tfailed`taborted`tskipped`tcontainersFailed`tstdoutLog`tstderrLog`tnote" | Set-Content -Path $results -Encoding ascii
  }
  $done = @{}
  foreach ($row in (Import-Csv -Path $results -Delimiter "`t")) { if ($row.class) { $done["$($row.module)`t$($row.class)"] = $true } }
  $todo = @($Classes | Where-Object { -not $done.ContainsKey("$($_.module)`t$($_.class)") })
  $script:ResultIndex = (Import-Csv -Path $results -Delimiter "`t").Count + 1

  Write-Info "mode=$mode vm=$Vm jit=$Jit category=$Category selected=$($Classes.Count) todo=$($todo.Count) parallel=$Parallel timeout=${TimeoutSec}s"
  if ($Vm -eq 'craton') { Write-Info "craton exe=$craton" }
  Write-Info "logs/results=$modeOut"

  $modeStarted = Get-Date
  $script:RunningRecords = New-Object System.Collections.Generic.List[object]

  function Drain-Running {
    $still = New-Object System.Collections.Generic.List[object]
    foreach ($record in $script:RunningRecords) {
      $elapsed = ((Get-Date) - $record.start).TotalSeconds
      if ($record.proc.HasExited) {
        $code = $record.proc.ExitCode
        $outputs = Read-ProcessOutputs $record
        Complete-ProcessRecord -Record $record -ResultPath $results -ExitCode $code -Seconds ([Math]::Round($elapsed, 3)) -Stdout $outputs.stdout -Stderr $outputs.stderr
        try { $record.proc.Dispose() } catch {}
      } elseif ($elapsed -ge $record.timeoutSec) {
        try { $record.proc.Kill($true) } catch { try { $record.proc.Kill() } catch {} }
        try { $record.proc.WaitForExit(5000) | Out-Null } catch {}
        $outputs = Read-ProcessOutputs $record
        Complete-ProcessRecord -Record $record -ResultPath $results -ExitCode 'TIMEOUT' -Seconds ([Math]::Round($elapsed, 3)) -Stdout $outputs.stdout -Stderr $outputs.stderr
        try { $record.proc.Dispose() } catch {}
      } else { $still.Add($record) }
    }
    $script:RunningRecords = $still
  }

  foreach ($classRow in $todo) {
    while ($script:RunningRecords.Count -ge $Parallel) { Drain-Running; if ($script:RunningRecords.Count -ge $Parallel) { Start-Sleep -Milliseconds 200 } }
    $launch = Get-LaunchSpec -ClassRow $classRow
    $classTimeoutSec = Get-EffectiveClassTimeoutSec -ClassRow $classRow -BaseTimeoutSec $TimeoutSec
    if ($classTimeoutSec -ne $TimeoutSec) { Write-Info "timeout override=${classTimeoutSec}s $($classRow.module).$($classRow.class)" }
    $script:RunningRecords.Add((New-ProcessRecord -ClassRow $classRow -ModeOut $modeOut -LaunchSpec $launch -ExePath $craton -JavaExe $java -JdkPath $jdk -NoJit:($Jit -eq 'off') -Timeout $classTimeoutSec))
  }
  while ($script:RunningRecords.Count -gt 0) { Drain-Running; if ($script:RunningRecords.Count -gt 0) { Start-Sleep -Milliseconds 200 } }
  Remove-Variable -Name RunningRecords -Scope Script -ErrorAction SilentlyContinue

  $elapsed = [Math]::Round(((Get-Date) - $modeStarted).TotalSeconds, 3)
  $rows = @(Import-Csv -Path $results -Delimiter "`t")
  $summaryPath = Join-Path $modeOut 'summary.md'
  $counts = $rows | Group-Object status | Sort-Object Name
  $classSeconds = 0.0
  foreach ($row in $rows) { $classSeconds += ConvertFrom-InvariantString ([string]$row.seconds) }

  $summary = New-Object System.Collections.Generic.List[string]
  $summary.Add("# Spring Boot suite result")
  $summary.Add(""); $summary.Add("- run: $run"); $summary.Add("- mode: $mode"); $summary.Add("- vm: $Vm"); $summary.Add("- jit: $Jit")
  $summary.Add("- category: $Category"); $summary.Add("- classes recorded: $($rows.Count)")
  $summary.Add("- wall seconds: $(ConvertTo-InvariantString $elapsed)"); $summary.Add("- summed class seconds: $(ConvertTo-InvariantString $classSeconds)")
  $summary.Add("- spring-boot root: $script:SpringBootDir")
  if ($Vm -eq 'craton') { $summary.Add("- craton exe: $craton") }
  $summary.Add(""); $summary.Add("## Status Counts")
  foreach ($group in $counts) { $summary.Add("- $($group.Name): $($group.Count)") }
  if ($Vm -eq 'craton' -and -not $NoCorruptCellCensus) {
    $cc = Get-CorruptCellCensus -LogDir (Join-Path $modeOut 'logs')
    $summary.Add(""); $summary.Add("## Corrupt Value cell census")
    $summary.Add("- logs scanned: $($cc.Logs)")
    $summary.Add("- logs carrying the census line: $($cc.Armed)")
    $summary.Add("- logs with NO census line: $($cc.Unarmed) (a class killed before the shutdown trailer -- HANG/TIMEOUT -- cannot print it)")
    $summary.Add("- cells decoded: $($cc.Decoded)")
    $summary.Add("- cells named (door or backstop): $($cc.Reported)")
    $summary.Add("- array-receiver field accesses refused: $($cc.ArrayReceiver) (a plain-object field read whose receiver was an ARRAY -- the same defect one step earlier, and a COUNT where `cells decoded` is a floor)")
    if ($cc.Classes.Count -gt 0) {
      $summary.Add(""); $summary.Add("### Classes that decoded a cell or strided an array")
      foreach ($c in $cc.Classes) { $summary.Add("- $c") }
    }
    # Loud on stdout too: a census buried in a file nobody opens is the same
    # silence this exists to remove.
    if ($cc.Decoded -gt 0 -or $cc.ArrayReceiver -gt 0) {
      Write-Info "CORRUPT-VALUE-CELL: $($cc.Decoded) decoded, $($cc.Reported) named, $($cc.ArrayReceiver) array-receiver refusals, in $($cc.Classes.Count) class(es) -- see $summaryPath"
      foreach ($c in $cc.Classes) { Write-Info "  corrupt-cell: $c" }
    } else {
      Write-Info "corrupt-cell census: 0 decoded, 0 array-receiver refusals across $($cc.Armed) of $($cc.Logs) logs (armed)"
    }
  }
  $summary.Add(""); $summary.Add("## Files"); $summary.Add("- results: $results"); $summary.Add("- logs: $(Join-Path $modeOut 'logs')")
  $summary | Set-Content -Path $summaryPath -Encoding ascii

  if ($Vm -eq 'hotspot') {
    $baselineDir = Join-Path $script:WorkRoot 'baseline'
    New-Item -ItemType Directory -Force -Path $baselineDir | Out-Null
    $baselineBase = "hotspot-baseline-$run"
    Copy-Item -Path $results -Destination (Join-Path $baselineDir "$baselineBase.tsv") -Force
    Copy-Item -Path $summaryPath -Destination (Join-Path $baselineDir "$baselineBase.md") -Force
    Copy-Item -Path $summaryPath -Destination (Join-Path $baselineDir 'hotspot-baseline-latest.md') -Force
    $latestCount = Merge-HotspotBaselineLatest -BaselineDir $baselineDir -ResultsPath $results
    Write-Info "baseline copied to $baselineDir\$baselineBase.tsv; hotspot-baseline-latest.tsv now covers $latestCount classes"
  }
  Write-Info "DONE mode=$mode wall=${elapsed}s summary=$summaryPath"
}

function Invoke-AllModes {
  $run = $RunName
  if (-not $run) { $run = Get-Date -Format 'yyyyMMdd-HHmmss' }
  $self = $PSCommandPath
  $psExe = Get-PowerShellExe
  $modes = @(
    @{ jit = 'on';  name = 'jit' },
    @{ jit = 'off'; name = 'nojit' }
  )
  $runRoot = Join-Path (Join-Path $script:WorkRoot 'results') $run
  New-Item -ItemType Directory -Force -Path $runRoot | Out-Null
  $children = @()
  foreach ($mode in $modes) {
    $log = Join-Path $runRoot "$($mode.name).console.log"
    $err = Join-Path $runRoot "$($mode.name).console.err.log"
    $args = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $self,
      '-Category', $Category, '-Jit', $mode.jit, '-Vm', 'craton',
      '-Start', $Start, '-Count', $Count, '-Parallel', $Parallel, '-TimeoutSec', $TimeoutSec,
      '-RunName', $run, '-ModeName', $mode.name, '-SpringBootRoot', $script:SpringBootDir,
      '-WorkDir', $script:WorkRoot, '-JdkHome', (Resolve-Jdk), '-MaxHeap', $MaxHeap)
    if ($Exe) { $args += @('-Exe', $Exe) }
    if ($RefCsv) { $args += @('-RefCsv', $RefCsv) }
    if ($HotspotBaseline) { $args += @('-HotspotBaseline', $HotspotBaseline) }
    if ($ClassList) { $args += @('-ClassList', $ClassList) }
    if ($CratonArgs.Count -gt 0) { foreach ($extra in $CratonArgs) { $args += @('-CratonArgs', $extra) } }
    Write-Info "launching $($mode.name) in background"
    $children += Start-RedirectedProcess -FilePath $psExe -Arguments $args -WorkingDirectory $script:RepoRoot -StdoutPath $log -StderrPath $err
  }
  $failedChildren = 0
  foreach ($child in $children) { $exitCode = Complete-RedirectedProcess $child; if ($exitCode -ne 0) { $failedChildren++ } }
  if ($failedChildren -gt 0) { Die "$failedChildren all-mode child process(es) failed; inspect $runRoot\*.console*.log" }
  Write-Info "ALL MODES DONE. Results under $runRoot"
}

$script:RepoRoot = Get-RepoRoot
if (-not $SpringBootRoot) {
  $appsRoot = Split-Path $PSScriptRoot -Parent
  $SpringBootRoot = Join-Path $appsRoot 'spring-boot'
}
$script:SpringBootDir = [System.IO.Path]::GetFullPath($SpringBootRoot)
if (-not (Test-Path $script:SpringBootDir)) { Die "Spring Boot root not found: $script:SpringBootDir" }
$script:SbRunnerDir = Join-Path $script:SpringBootDir 'sb-runner'
if (-not (Test-Path (Join-Path $script:SbRunnerDir 'SbRunner.class'))) { Die "missing SbRunner.class in $script:SbRunnerDir (javac SbRunner.java against the JUnit platform jars first)" }
# Existence was the only thing ever checked, so a `.class` compiled before the
# `.java` last changed kept running unnoticed -- and the fixture directory is
# NOT under version control, so it goes stale by default. That is why
# `SBRUNNER_ABORTED_DETAIL` was documented as landed and yet appeared in no run
# log: `SbRunner.class` in the fixture predated the change that emits it, and
# the missing line was then read as "the reason strings are not wired up".
# (Confirmed 2026-08-11 on the Azure fixture: `SbRunner$OutcomeReasonCollector.class`
# did not exist beside a `SbRunner.java` that declares it.)
#
# Refuse to run on a stale runner rather than produce logs missing the very
# evidence the harness now classifies on -- `Resolve-EnvGatedStatus` counts
# those lines.
foreach ($src in @('SbRunner.java', 'SbRunnerMethod.java')) {
  $srcPath = Join-Path $script:SbRunnerDir $src
  if (-not (Test-Path $srcPath)) { continue }
  $clsPath = Join-Path $script:SbRunnerDir ([System.IO.Path]::ChangeExtension($src, '.class'))
  if (-not (Test-Path $clsPath) -or
      (Get-Item $srcPath).LastWriteTimeUtc -gt (Get-Item $clsPath).LastWriteTimeUtc) {
    Die ("stale sb-runner: $src is newer than its .class in $script:SbRunnerDir. " +
         "Recompile before running, e.g.`n" +
         "  javac -cp `"<any module>/build/cratonvm-test-cp.txt contents>`" -d `"$script:SbRunnerDir`" `"$script:SbRunnerDir\*.java`"")
  }
}

if (-not $WorkDir) { $WorkDir = Join-Path $PSScriptRoot '.suite' }
$script:WorkRoot = [System.IO.Path]::GetFullPath($WorkDir)
New-Item -ItemType Directory -Force -Path $script:WorkRoot | Out-Null

if ($Start -lt 1) { Die "-Start is 1-based and must be >= 1" }
if ($Count -lt 0) { Die "-Count must be >= 0" }
if ($Parallel -lt 1) { Die "-Parallel must be >= 1" }
if ($TimeoutSec -lt 1) { Die "-TimeoutSec must be >= 1" }

if ($Setup) {
  Invoke-GradleSetup
  if (-not $AllModes -and $Category -eq 'all' -and -not $ListOnly -and $Count -eq 0 -and $Start -eq 1) {
    Write-Info "Setup-only invocation complete (no -Count given). Re-run without -Setup to execute."
    return
  }
}

if ($AllModes) {
  if ($Vm -ne 'craton') { Die "-AllModes is CratonVM-only" }
  Invoke-AllModes
  return
}

$classes = @(Get-SelectedClasses)
Write-Info "selected $($classes.Count) classes (category=$Category start=$Start count=$(if ($Count -gt 0) { $Count } else { 'all' }))"
if ($ListOnly) {
  $i = $Start
  foreach ($class in $classes) { "{0}`t{1}`t{2}" -f $i, $class.module, $class.class; $i++ }
  return
}
if ($classes.Count -eq 0) { Die "no classes selected" }

Invoke-Mode -Classes $classes
