<#
.SYNOPSIS
  Spring Boot JUnit suite runner for CratonVM and HotSpot.

.DESCRIPTION
  Runs the compiled Spring Boot test classes (core/, module/, cli/,
  configuration-metadata/, loader/, test-support/ Gradle subtrees) one
  process per class through apps\spring-boot\sb-runner\SbRunner.class, a
  JUnit Platform launcher harness (mirrors apps\keycloak\kc-runner\KcRunner).
  Records per-class wall time, persists stdout/stderr logs, can select
  classes by category (passed vs all others), and can run JIT on/off x
  category combinations concurrently.

  Unlike the Maven-based Keycloak runner, Spring Boot's per-module test
  runtime classpath is generated by a Gradle init script
  (apps\spring-boot\cratonvm-test-cp.init.gradle) that writes
  <module>\build\cratonvm-test-cp.txt for every project with a `test`
  source set.
#>
[CmdletBinding()]
param(
  [ValidateSet('passed','others','failed','all')] [string]$Category = 'all',
  [ValidateSet('on','off')]                       [string]$Jit = 'on',
  [ValidateSet('craton','hotspot')]               [string]$Vm = 'craton',

  [int]$Start = 1,
  [int]$Count = 0,
  [int]$Parallel = 4,
  [int]$TimeoutSec = 300,

  [string]$RunName = '',
  [string]$ModeName = '',
  [string]$SpringBootRoot = '',
  [string]$WorkDir = '',
  [string]$RefCsv = '',
  [string]$ClassList = '',
  [string[]]$Subtrees = @('core','module','cli','configuration-metadata','loader','test-support'),
  [string]$Exe = '',
  [string]$JdkHome = '',
  [string]$MaxHeap = '2g',
  [string[]]$CratonArgs = @(),

  [switch]$RefreshLists,
  [switch]$RefreshClasspaths,
  [switch]$ListOnly,
  [switch]$AllModes,
  [switch]$Setup
)

$ErrorActionPreference = 'Stop'

function Write-Info([string]$Message) {
  Write-Host "[spring-boot-suite] $Message"
}

function Die([string]$Message) {
  Write-Error "[spring-boot-suite] $Message"
  exit 1
}

function Get-RepoRoot {
  try {
    $root = & git -C $PSScriptRoot rev-parse --show-toplevel 2>$null
    if ($LASTEXITCODE -eq 0 -and $root) { return $root.Trim() }
  } catch {}
  return (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent)
}

function Get-PowerShellExe {
  if ($PSHOME) {
    $candidate = Join-Path $PSHOME 'pwsh.exe'
    if (Test-Path $candidate) { return $candidate }
    $candidate = Join-Path $PSHOME 'powershell.exe'
    if (Test-Path $candidate) { return $candidate }
  }
  return 'powershell.exe'
}

function ConvertTo-SafeName([string]$Value) {
  return ($Value -replace '[^A-Za-z0-9_.-]', '_')
}

function ConvertTo-SafeFileStem([string]$Value, [int]$MaxLength = 96) {
  $safe = ConvertTo-SafeName $Value
  if ($MaxLength -lt 16) { $MaxLength = 16 }
  if ($safe.Length -le $MaxLength) { return $safe }
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($safe)
    $hash = ([System.BitConverter]::ToString($sha.ComputeHash($bytes)) -replace '-', '').Substring(0, 12).ToLowerInvariant()
  } finally {
    $sha.Dispose()
  }
  $prefixLength = $MaxLength - $hash.Length - 1
  return "$($safe.Substring(0, $prefixLength))-$hash"
}

function Get-Sha256Hex([string]$Value) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
    return (([System.BitConverter]::ToString($sha.ComputeHash($bytes))) -replace '-', '').ToLowerInvariant()
  } finally {
    $sha.Dispose()
  }
}

function ConvertTo-InvariantString([double]$Value) {
  return $Value.ToString('F3', [System.Globalization.CultureInfo]::InvariantCulture)
}

function ConvertFrom-InvariantString([string]$Value) {
  $parsed = 0.0
  if ([double]::TryParse($Value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
    return $parsed
  }
  return 0.0
}

function Quote-WindowsArgument([string]$Argument) {
  if ($null -eq $Argument) { return '""' }
  if ($Argument.Length -eq 0) { return '""' }
  if ($Argument -notmatch '[\s"]') { return $Argument }
  $result = New-Object System.Text.StringBuilder
  [void]$result.Append('"')
  $backslashes = 0
  foreach ($ch in $Argument.ToCharArray()) {
    if ($ch -eq '\') {
      $backslashes++
    } elseif ($ch -eq '"') {
      if ($backslashes -gt 0) { [void]$result.Append('\' * ($backslashes * 2)) }
      $backslashes = 0
      [void]$result.Append('\"')
    } else {
      if ($backslashes -gt 0) { [void]$result.Append('\' * $backslashes) }
      $backslashes = 0
      [void]$result.Append($ch)
    }
  }
  if ($backslashes -gt 0) { [void]$result.Append('\' * ($backslashes * 2)) }
  [void]$result.Append('"')
  return $result.ToString()
}

function Set-ProcessArguments([System.Diagnostics.ProcessStartInfo]$StartInfo, [string[]]$Arguments) {
  # ProcessStartInfo.ArgumentList is unavailable/null under Windows PowerShell
  # 5.1 (.NET Framework) in some environments — fall back to the classic
  # pre-quoted Arguments string when it's not usable.
  $argListProp = $StartInfo.GetType().GetProperty('ArgumentList')
  if ($argListProp -and $StartInfo.ArgumentList) {
    foreach ($arg in $Arguments) { [void]$StartInfo.ArgumentList.Add($arg) }
  } else {
    $StartInfo.Arguments = (($Arguments | ForEach-Object { Quote-WindowsArgument $_ }) -join ' ')
  }
}

function Start-RedirectedProcess {
  param([string]$FilePath, [string[]]$Arguments, [string]$WorkingDirectory, [string]$StdoutPath, [string]$StderrPath)
  $psi = [System.Diagnostics.ProcessStartInfo]::new()
  $psi.FileName = $FilePath
  $psi.WorkingDirectory = $WorkingDirectory
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  Set-ProcessArguments -StartInfo $psi -Arguments $Arguments
  $proc = [System.Diagnostics.Process]::new()
  $proc.StartInfo = $psi
  [void]$proc.Start()
  return [pscustomobject]@{
    proc = $proc
    stdoutTask = $proc.StandardOutput.ReadToEndAsync()
    stderrTask = $proc.StandardError.ReadToEndAsync()
    stdoutPath = $StdoutPath
    stderrPath = $StderrPath
  }
}

function Complete-RedirectedProcess([object]$Record) {
  $Record.proc.WaitForExit()
  try { $Record.stdoutTask.Wait(5000) | Out-Null } catch {}
  try { $Record.stderrTask.Wait(5000) | Out-Null } catch {}
  $stdout = ''; $stderr = ''
  try { $stdout = $Record.stdoutTask.Result } catch {}
  try { $stderr = $Record.stderrTask.Result } catch {}
  if ($Record.stdoutPath) { [System.IO.File]::WriteAllText($Record.stdoutPath, $stdout, [System.Text.Encoding]::UTF8) }
  if ($Record.stderrPath) { [System.IO.File]::WriteAllText($Record.stderrPath, $stderr, [System.Text.Encoding]::UTF8) }
  $exitCode = $Record.proc.ExitCode
  try { $Record.proc.Dispose() } catch {}
  return $exitCode
}

function Split-ClasspathEntries([string]$Classpath) {
  if (-not $Classpath) { return @() }
  $separator = [string][System.IO.Path]::PathSeparator
  return @($Classpath -split [regex]::Escape($separator) | Where-Object { $_ })
}

function Add-UniqueClasspathEntry {
  param([System.Collections.Generic.List[string]]$Entries, [hashtable]$Seen, [string]$Entry)
  if (-not $Entry) { return }
  try {
    $full = [System.IO.Path]::GetFullPath($Entry)
    $key = $full.ToLowerInvariant()
    $value = $full
  } catch {
    $key = $Entry.ToLowerInvariant()
    $value = $Entry
  }
  if (-not $Seen.ContainsKey($key)) {
    $Entries.Add($value)
    $Seen[$key] = $true
  }
}

function Get-GradleCacheRoot {
  if ($script:GradleCacheRootCache) { return $script:GradleCacheRootCache }
  $candidates = @()
  if ($env:GRADLE_USER_HOME) { $candidates += (Join-Path $env:GRADLE_USER_HOME 'caches\modules-2\files-2.1') }
  if ($env:USERPROFILE) { $candidates += (Join-Path $env:USERPROFILE '.gradle\caches\modules-2\files-2.1') }
  foreach ($c in $candidates) { if (Test-Path $c) { $script:GradleCacheRootCache = $c; return $c } }
  $script:GradleCacheRootCache = ''
  return ''
}

function Find-GradleCacheJar([string]$Group, [string]$Artifact) {
  $root = Get-GradleCacheRoot
  if (-not $root) { return $null }
  $artifactDir = Join-Path $root "$Group\$Artifact"
  if (-not (Test-Path $artifactDir)) { return $null }
  return Get-ChildItem -Path $artifactDir -Recurse -File -Filter "$Artifact-*.jar" -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notmatch '(-sources|-javadoc)\.jar$' } |
    Sort-Object FullName -Descending | Select-Object -First 1
}

function Add-JUnitPlatformInfraEntries {
  # SbRunner drives every class through the JUnit Platform Launcher's default
  # ServiceLoader engine auto-registration, so both jupiter (JUnit5) and
  # vintage (JUnit4, if a class needs it) run uniformly. A module's own
  # Gradle testRuntimeClasspath does NOT necessarily include the launcher
  # jar (Gradle's `test` task manages that on its own internal classpath,
  # not the project's), so make it universally available here — same
  # rationale as the Keycloak runner's Add-JUnitPlatformInfraEntries.
  param([System.Collections.Generic.List[string]]$Entries, [hashtable]$Seen)
  $artifacts = @(
    @('org.junit.platform', 'junit-platform-commons'),
    @('org.junit.platform', 'junit-platform-engine'),
    @('org.junit.platform', 'junit-platform-launcher'),
    @('org.junit.jupiter', 'junit-jupiter-api'),
    @('org.junit.jupiter', 'junit-jupiter-engine'),
    @('org.junit.vintage', 'junit-vintage-engine'),
    @('org.opentest4j', 'opentest4j'),
    @('org.apiguardian', 'apiguardian-api'),
    @('junit', 'junit')
  )
  foreach ($pair in $artifacts) {
    $jar = Find-GradleCacheJar -Group $pair[0] -Artifact $pair[1]
    if ($jar) { Add-UniqueClasspathEntry -Entries $Entries -Seen $Seen -Entry $jar.FullName }
  }
}

function ConvertTo-ManifestClasspathUrl([string]$Entry) {
  $full = [System.IO.Path]::GetFullPath($Entry)
  if ((Test-Path $full -PathType Container) -and -not ($full.EndsWith('\') -or $full.EndsWith('/'))) {
    $full += [System.IO.Path]::DirectorySeparatorChar
  }
  return ([System.Uri]::new($full, [System.UriKind]::Absolute)).AbsoluteUri
}

function Split-ManifestLine([string]$Line) {
  $max = 70
  $out = New-Object System.Collections.Generic.List[string]
  if ($Line.Length -le $max) { $out.Add($Line); return @($out) }
  $out.Add($Line.Substring(0, $max))
  $offset = $max
  while ($offset -lt $Line.Length) {
    $take = [Math]::Min($max - 1, $Line.Length - $offset)
    $out.Add(' ' + $Line.Substring($offset, $take))
    $offset += $take
  }
  return @($out)
}

function New-PathingJar {
  param([string]$Module, [string[]]$Entries)
  # -AllModes launches JIT and no-JIT child runners concurrently.  They have
  # the same module classpath signature but must not race over one
  # classpath.jar (one child can observe the other deleting/recreating it).
  # Mode-local wrappers retain caching within a lane while making the two
  # child processes independent.
  $modePath = ConvertTo-SafeName $(if ($script:EffectiveModeName) { $script:EffectiveModeName } else { 'default' })
  $pathingDir = Join-Path (Join-Path $script:WorkRoot 'pathing-jars') $modePath
  New-Item -ItemType Directory -Force -Path $pathingDir | Out-Null
  $signature = 'pathing-jar-manifest-url-v1' + "`n" + (($Entries | ForEach-Object { [System.IO.Path]::GetFullPath($_) }) -join "`n")
  $hash = (Get-Sha256Hex $signature).Substring(0, 16)
  $stem = ConvertTo-SafeFileStem $(if ($Module) { $Module } else { 'universal' })
  # Spring Boot's ModifiedClassPathClassLoader expands the manifest class
  # path only for IntelliJ-style `classpath.jar` files.  The runner needs
  # that expansion for @ClassPathExclusions/@ClassPathOverrides: otherwise
  # it sees this one wrapper JAR instead of the individual dependency JARs.
  # Keep module/content isolation in directories so the wrapper name itself
  # can retain the recognized IntelliJ convention.
  $jarDir = Join-Path (Join-Path $pathingDir $stem) $hash
  $jarPath = Join-Path $jarDir 'classpath.jar'
  if (Test-Path $jarPath) { return [System.IO.Path]::GetFullPath($jarPath) }
  New-Item -ItemType Directory -Force -Path $jarDir | Out-Null

  Add-Type -AssemblyName System.IO.Compression | Out-Null
  Add-Type -AssemblyName System.IO.Compression.FileSystem | Out-Null
  $urls = @($Entries | ForEach-Object { ConvertTo-ManifestClasspathUrl $_ })
  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('Manifest-Version: 1.0')
  $lines.Add('Created-By: IntelliJ IDEA')
  $lines.Add('Main-Class: SbRunner')
  foreach ($line in (Split-ManifestLine ('Class-Path: ' + ($urls -join ' ')))) { $lines.Add($line) }
  $lines.Add('')

  if (Test-Path $jarPath) { Remove-Item -LiteralPath $jarPath -Force }
  $zip = [System.IO.Compression.ZipFile]::Open($jarPath, [System.IO.Compression.ZipArchiveMode]::Create)
  try {
    $entry = $zip.CreateEntry('META-INF/MANIFEST.MF')
    $stream = $entry.Open()
    try {
      $writer = [System.IO.StreamWriter]::new($stream, [System.Text.Encoding]::ASCII)
      try { $writer.NewLine = "`r`n"; foreach ($line in $lines) { $writer.WriteLine($line) } } finally { $writer.Dispose() }
    } finally { $stream.Dispose() }
  } finally { $zip.Dispose() }
  return [System.IO.Path]::GetFullPath($jarPath)
}

function Import-ResultRows([string]$Path) {
  if (-not (Test-Path $Path)) { return @() }
  $first = Get-Content -Path $Path -TotalCount 1
  $delimiter = ','
  if ($first -like "*`t*") { $delimiter = "`t" }
  return @(Import-Csv -Path $Path -Delimiter $delimiter)
}

function Select-ClassRange([object[]]$List) {
  $list = @($List)
  $from = [Math]::Max(1, $Start) - 1
  if ($from -ge $list.Count) { return @() }
  $end = $list.Count
  if ($Count -gt 0) { $end = [Math]::Min($list.Count, $from + $Count) }
  return @($list[$from..($end - 1)])
}

function Resolve-ReferenceFile {
  if ($RefCsv -and (Test-Path $RefCsv)) { return $RefCsv }
  $candidates = @((Join-Path $script:WorkRoot 'reference.tsv'), (Join-Path $script:WorkRoot 'reference.csv'))
  foreach ($candidate in $candidates) { if (Test-Path $candidate) { return $candidate } }
  return ''
}

function Get-RowStatus($Row) {
  if ($Row.PSObject.Properties.Name -contains 'status') { return ([string]$Row.status).ToUpperInvariant() }
  return ''
}

# ---------------------------------------------------------------------------
# gradlew invocation helper
# ---------------------------------------------------------------------------
function Invoke-Gradlew {
  param([string]$Gradlew, [string[]]$GradleArgs)
  # Windows PowerShell 5.1 wraps ANY stderr line from a native process as a
  # terminating NativeCommandError while $ErrorActionPreference = 'Stop' is in
  # effect, even on exit code 0 (Gradle routinely logs benign warnings to
  # stderr). Temporarily relax to 'Continue' and check $LASTEXITCODE instead
  # (same pattern as the tomcat-suite-runner's Invoke-Setup).
  # NOTE: parameter deliberately NOT named $Args -- that collides with
  # PowerShell's automatic $args variable and silently corrupts the splat
  # (gradlew received zero args, defaulted to the `help` task against the
  # wrong project dir, every "Setup" run up to 2026-07-17 was silently
  # discovering 0 classes / regenerating no classpaths despite exit 0).
  $prevEAP = $ErrorActionPreference
  $ErrorActionPreference = 'Continue'
  # gradlew.bat relies on the CALLER's current directory being the Gradle
  # project root (it does not `cd` into its own location) -- invoking it via
  # `& $Gradlew` from an arbitrary caller cwd (e.g. the CratonVM repo root)
  # fails with "Directory '<cwd>' does not contain a Gradle build" even
  # though $Gradlew's own path is fully qualified. Push into its directory
  # for the duration of the call.
  Push-Location (Split-Path $Gradlew -Parent)
  try {
    & $Gradlew @GradleArgs 2>&1 | ForEach-Object { Write-Host $_ }
    return $LASTEXITCODE
  } finally {
    Pop-Location
    $ErrorActionPreference = $prevEAP
  }
}

# ---------------------------------------------------------------------------
# Setup: compile test classes + generate per-module classpaths (Gradle)
# ---------------------------------------------------------------------------
function Invoke-GradleSetup {
  $jdk = Resolve-Jdk
  $env:JAVA_HOME = $jdk
  $gradlew = Join-Path $script:SpringBootDir 'gradlew.bat'
  if (-not (Test-Path $gradlew)) { Die "gradlew.bat not found: $gradlew" }
  $initScript = Join-Path $script:SpringBootDir 'cratonvm-test-cp.init.gradle'
  if (-not (Test-Path $initScript)) { Die "missing init script: $initScript (dumps per-module test runtime classpaths)" }

  foreach ($subtree in $Subtrees) {
    $dir = Join-Path $script:SpringBootDir $subtree
    if (-not (Test-Path $dir)) { Write-Info "skip missing subtree: $subtree"; continue }
    Write-Info "gradlew -p $subtree testClasses"
    $rc = Invoke-Gradlew -Gradlew $gradlew -GradleArgs @('-p', $dir, 'testClasses', '--no-daemon', '--continue')
    if ($rc -ne 0) { Write-Info "WARNING: testClasses had failures in $subtree (continuing; some modules may be env-gated)" }
    Write-Info "gradlew -p $subtree cratonvmTestCp"
    $rc = Invoke-Gradlew -Gradlew $gradlew -GradleArgs @('-p', $dir, 'cratonvmTestCp', '--init-script', $initScript, '--no-daemon', '--continue')
    if ($rc -ne 0) { Write-Info "WARNING: cratonvmTestCp had failures in $subtree" }
  }
  Build-ClassLists
  Write-Info "Setup complete. classes=$((Get-Content (Join-Path $script:WorkRoot 'all-tests.tsv') | Measure-Object -Line).Lines - 1)"
}

function Build-ClassLists {
  New-Item -ItemType Directory -Force -Path $script:WorkRoot | Out-Null
  $allPath = Join-Path $script:WorkRoot 'all-tests.tsv'
  $passedPath = Join-Path $script:WorkRoot 'passed.tsv'
  $othersPath = Join-Path $script:WorkRoot 'others.tsv'
  $testClassPatterns = @('*Test.class', '*Tests.class', '*IT.class', '*ITCase.class')

  $records = New-Object System.Collections.Generic.List[object]
  foreach ($subtree in $Subtrees) {
    $subtreeDir = Join-Path $script:SpringBootDir $subtree
    if (-not (Test-Path $subtreeDir)) { continue }
    $testDirs = Get-ChildItem -Path $subtreeDir -Recurse -Directory -ErrorAction SilentlyContinue |
      Where-Object { $_.FullName -match '[\\/]build[\\/]classes[\\/](java|kotlin)[\\/]test$' } |
      Sort-Object FullName
    foreach ($dir in $testDirs) {
      # module = project dir (…\<subtree>\<name>), the parent of build\classes\<lang>\test
      $moduleDir = $dir.FullName
      while ($moduleDir -and (Split-Path $moduleDir -Leaf) -ne 'build') { $moduleDir = Split-Path $moduleDir -Parent }
      $moduleDir = Split-Path $moduleDir -Parent
      if (-not $moduleDir) { continue }
      $module = $moduleDir.Substring($script:SpringBootDir.Length + 1) -replace '\\', '/'
      $cpFile = Join-Path $moduleDir 'build\cratonvm-test-cp.txt'
      if (-not (Test-Path $cpFile)) { continue }

      $classes = @(foreach ($pattern in $testClassPatterns) { Get-ChildItem -Path $dir.FullName -Recurse -File -Filter $pattern -ErrorAction SilentlyContinue }) |
        Where-Object { $_.Name -notlike '*$*' -and $_.Name -ne 'AbstractTest.class' } |
        Sort-Object FullName -Unique
      foreach ($classFile in $classes) {
        $rel = $classFile.FullName.Substring($dir.FullName.Length + 1)
        $fqcn = ($rel -replace '\.class$', '') -replace '[\\/]', '.'
        $records.Add([pscustomobject]@{ module = $module; class = $fqcn })
      }
    }
  }

  $unique = $records | Sort-Object module, class -Unique
  "module`tclass" | Set-Content -Path $allPath -Encoding ascii
  foreach ($record in $unique) { "$($record.module)`t$($record.class)" | Add-Content -Path $allPath -Encoding ascii }

  $reference = Resolve-ReferenceFile
  if ($reference) {
    $passedKeys = @{}
    foreach ($row in (Import-ResultRows $reference)) {
      if ((Get-RowStatus $row) -eq 'PASS') { $passedKeys["$($row.module)`t$($row.class)"] = $true }
    }
    "module`tclass" | Set-Content -Path $passedPath -Encoding ascii
    "module`tclass" | Set-Content -Path $othersPath -Encoding ascii
    foreach ($record in $unique) {
      $key = "$($record.module)`t$($record.class)"
      if ($passedKeys.ContainsKey($key)) { "$($record.module)`t$($record.class)" | Add-Content -Path $passedPath -Encoding ascii }
      else { "$($record.module)`t$($record.class)" | Add-Content -Path $othersPath -Encoding ascii }
    }
    Write-Info "class lists refreshed: all=$($unique.Count), passed=$((Import-Csv $passedPath -Delimiter "`t").Count), others=$((Import-Csv $othersPath -Delimiter "`t").Count)"
  } else {
    Write-Info "class list refreshed: all=$($unique.Count); no reference found for passed/others split"
  }
}

function Import-ClassRows([string]$Path) {
  if (-not (Test-Path $Path)) { Die "class list not found: $Path" }
  return @(Import-ResultRows $Path)
}

function Get-SelectedClasses {
  $allPath = Join-Path $script:WorkRoot 'all-tests.tsv'
  $passedPath = Join-Path $script:WorkRoot 'passed.tsv'
  $othersPath = Join-Path $script:WorkRoot 'others.tsv'

  if ($ClassList) { return Select-ClassRange (Import-ClassRows $ClassList) }
  if ($RefreshLists -or -not (Test-Path $allPath)) { Build-ClassLists }

  $resolvedCategory = $Category
  if ($resolvedCategory -eq 'failed') { $resolvedCategory = 'others' }
  $source = $allPath
  if ($resolvedCategory -eq 'passed') { $source = $passedPath }
  if ($resolvedCategory -eq 'others') { $source = $othersPath }
  if (-not (Test-Path $source)) {
    if (-not (Resolve-ReferenceFile)) { Die "category '$Category' needs a reference result file. Pass -RefCsv, or run -Category all first." }
    Build-ClassLists
  }
  if (-not (Test-Path $source)) { Die "class list not found: $source" }
  return Select-ClassRange (Import-Csv -Path $source -Delimiter "`t")
}

# ---------------------------------------------------------------------------
# Classpath resolution (per module, cached)
# ---------------------------------------------------------------------------
function Get-ModuleClasspathEntries {
  param([string]$Module)
  if (-not $script:ModuleClasspathCache) { $script:ModuleClasspathCache = @{} }
  if ($script:ModuleClasspathCache.ContainsKey($Module)) { return @($script:ModuleClasspathCache[$Module]) }

  $modulePath = $Module -replace '/', '\'
  $moduleRoot = Join-Path $script:SpringBootDir $modulePath
  $cpFile = Join-Path $moduleRoot 'build\cratonvm-test-cp.txt'
  if ($RefreshClasspaths -or -not (Test-Path $cpFile)) {
    $jdk = Resolve-Jdk
    $env:JAVA_HOME = $jdk
    $gradlew = Join-Path $script:SpringBootDir 'gradlew.bat'
    $initScript = Join-Path $script:SpringBootDir 'cratonvm-test-cp.init.gradle'
    $projPath = ':' + ($Module -replace '/', ':')
    Write-Info "refreshing classpath for $Module"
    Invoke-Gradlew -Gradlew $gradlew -GradleArgs @("${projPath}:cratonvmTestCp", '--init-script', $initScript, '--no-daemon', '--continue') | Out-Null
  }
  if (-not (Test-Path $cpFile)) { Die "missing classpath file: $cpFile (run -Setup or -RefreshClasspaths first)" }

  $entries = New-Object System.Collections.Generic.List[string]
  $seen = @{}
  Add-UniqueClasspathEntry -Entries $entries -Seen $seen -Entry $script:SbRunnerDir
  foreach ($entry in (Split-ClasspathEntries ((Get-Content -Path $cpFile -Raw).Trim()))) {
    Add-UniqueClasspathEntry -Entries $entries -Seen $seen -Entry $entry
  }
  Add-JUnitPlatformInfraEntries -Entries $entries -Seen $seen

  $result = @($entries)
  $script:ModuleClasspathCache[$Module] = $result
  return $result
}

function Get-LaunchSpec {
  param([object]$ClassRow)
  $module = [string]$ClassRow.module
  $entries = @(Get-ModuleClasspathEntries -Module $module)
  $separator = [string][System.IO.Path]::PathSeparator
  $cp = ($entries -join $separator)
  $usePathingJar = ([System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT) -and ($cp.Length -gt 24000)
  if ($usePathingJar) {
    $jar = New-PathingJar -Module $module -Entries $entries
    return [pscustomobject]@{ kind = 'jar'; value = $jar; entries = $entries.Count; length = $cp.Length }
  }
  return [pscustomobject]@{ kind = 'cp'; value = $cp; entries = $entries.Count; length = $cp.Length }
}

function Resolve-CratonExe {
  if ($Exe) { if (-not (Test-Path $Exe)) { Die "CratonVM executable not found: $Exe" }; return [System.IO.Path]::GetFullPath($Exe) }
  if ($env:CV_BIN -and (Test-Path $env:CV_BIN)) { return [System.IO.Path]::GetFullPath($env:CV_BIN) }
  if ($env:CRATONVM_SPRING_BOOT_EXE -and (Test-Path $env:CRATONVM_SPRING_BOOT_EXE)) { return [System.IO.Path]::GetFullPath($env:CRATONVM_SPRING_BOOT_EXE) }

  $unique = Join-Path $script:RepoRoot 'target\release\cratonvm-spring-boot-suite.exe'
  if (Test-Path $unique) { return [System.IO.Path]::GetFullPath($unique) }
  $generic = Join-Path $script:RepoRoot 'target\release\cratonvm.exe'
  if (Test-Path $generic) {
    New-Item -ItemType Directory -Force -Path (Split-Path $unique) | Out-Null
    Copy-Item -Path $generic -Destination $unique -Force
    Write-Info "copied generic cratonvm.exe to unique runner binary: $unique"
    return [System.IO.Path]::GetFullPath($unique)
  }
  Die "CratonVM executable not found. Pass -Exe or set CV_BIN/CRATONVM_SPRING_BOOT_EXE."
}

function Resolve-Jdk {
  if ($JdkHome) { return $JdkHome }
  if ($env:JAVA_HOME) { return $env:JAVA_HOME }
  return 'C:\Program Files\Java\jdk-25'
}

function Get-EffectiveClassTimeoutSec {
  param([object]$ClassRow, [int]$BaseTimeoutSec)
  # This HSQLDB integration class creates and exercises several database-backed
  # application contexts.  After the Array.set fix it completes under Craton,
  # but its validated JIT-on time is about 14 minutes.  Keep the suite's
  # ordinary 300-second default for other classes while preventing this known
  # slow class from being reported as the old RangeGroupEmpty hang.
  if ($ClassRow.module -eq 'module/spring-boot-session-jdbc' -and
      $ClassRow.class -eq 'org.springframework.boot.session.jdbc.autoconfigure.JdbcSessionAutoConfigurationTests') {
    return [Math]::Max($BaseTimeoutSec, 900)
  }
  # 2026-07-17 contextrunner-resource-cycle-then-silent-stall-cluster investigation:
  # these 5 classes were originally misclassified as HANG at the standard 300s
  # shard timeout. A live CPU-sampled repro (single OS thread pegged near 100%
  # continuously, no thread ever genuinely parked) proved none of them are
  # deadlocked -- they are just slow (heavy reflection/annotation-scanning plus,
  # pre-fix, extra work from the since-fixed Class.getMethods() override-shadowing
  # bug). Each was run standalone to natural completion (FAIL, with real residual
  # test failures unrelated to hanging -- see
  # docs/known-issues/springboot/ for the specific residual docs) and the
  # validated wall-clock times below include headroom over the observed time.
  # See docs/internal/springboot/contextrunner-resource-cycle-then-silent-stall-cluster-FIXED.md.
  $slowClasses = @{
    'module/spring-boot-cache|org.springframework.boot.cache.autoconfigure.CacheAutoConfigurationTests' = 600
    # Hibernate's complete JPA auto-configuration class is CPU-bound and has
    # completed naturally in roughly 9.5 minutes under both Craton execution
    # modes. Keep the ordinary 300-second default for every other class, but
    # leave enough headroom for real failure reporting instead of labelling the
    # class as a hang before its result is available.
    'module/spring-boot-hibernate|org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfigurationTests' = 1200
    'module/spring-boot-security|org.springframework.boot.security.autoconfigure.actuate.web.servlet.JerseyEndpointRequestIntegrationTests' = 600
    'module/spring-boot-security|org.springframework.boot.security.autoconfigure.actuate.web.servlet.MvcEndpointRequestIntegrationTests' = 700
    'module/spring-boot-security|org.springframework.boot.security.autoconfigure.actuate.web.reactive.EndpointRequestIntegrationTests' = 1000
    'module/spring-boot-micrometer-tracing-opentelemetry|org.springframework.boot.micrometer.tracing.opentelemetry.autoconfigure.OpenTelemetryTracingAutoConfigurationTests' = 1400
    # WEBMVC.1 (2026-07-18): these are not deadlocks. An explicit 180-second
    # Craton watchdog captured WebMvcAutoConfigurationTests actively executing
    # Spring context creation/property binding on CPU; its 93 methods create
    # many independent contexts. BasicErrorControllerIntegrationTests likewise
    # repeatedly boots and tears down embedded Tomcat. Keep enough room for the
    # actual JUnit result instead of reporting a false 300-second HANG.
    'module/spring-boot-webmvc|org.springframework.boot.webmvc.autoconfigure.WebMvcAutoConfigurationTests' = 7200
    'module/spring-boot-webmvc|org.springframework.boot.webmvc.autoconfigure.error.BasicErrorControllerIntegrationTests' = 1800
    # SPRING-TESTCOMPILER.1 (2026-07-18): these processor tests repeatedly
    # compile fixture sources in-process through the real JDK javac. They are
    # CPU-bound and silent until JUnit has completed all fixture compilations;
    # a 300-second shard limit therefore reports a false HANG. The representative
    # 65-test annotation-processor class completed in 629.68s with JIT and
    # 680.00s with --nojit. Keep enough headroom to report its actual result.
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.ConfigurationMetadataAnnotationProcessorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.ConstructorParameterPropertyDescriptorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.EndpointMetadataGenerationTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.JavaBeanPropertyDescriptorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.LombokPropertyDescriptorTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.MergeMetadataGenerationTests' = 1200
    'configuration-metadata/spring-boot-configuration-processor|org.springframework.boot.configurationprocessor.PropertyDescriptorResolverTests' = 1200
    # RABBIT-CGLIB.1 (2026-07-20): originally reported as a HANG
    # (docs/known-issues/springboot/rabbitautoconfigurationtests-cglib-enhance-hang.md)
    # because the log's last line was a CGLIB `@Configuration` enhancement
    # right before the standard 300s shard timeout killed the process. A
    # CPU-sampled standalone repro (same technique as the contextrunner
    # cluster above: `Get-Process` thread `TotalProcessorTime` growing
    # ~1 CPU-second per wall-second continuously, no thread ever parked)
    # proved this is not a deadlock -- the class's 78 tests each build and
    # tear down a full Spring context (many with CGLIB `@Configuration`
    # proxies and fresh Mockito/ByteBuddy mocks), which is genuinely
    # CPU-heavy under CratonVM. Run to natural completion in 470.1s
    # (`Test run finished after 470134 ms`, 76/78 passed). Keep headroom
    # above that observed time instead of reporting a false HANG.
    'module/spring-boot-amqp|org.springframework.boot.amqp.autoconfigure.RabbitAutoConfigurationTests' = 900
    # CORE39-CLUSTERA.1 (2026-07-23): originally reported as a HANG at the
    # standard 300s shard timeout. A 900s standalone repro (single OS thread,
    # JIT on) proved this is not a deadlock -- it completes on its own in
    # 386.8s, PASS. The class exercises many individual `@Test` methods (each
    # a fresh YAML-loader parse), and JUnit5's own extension-registry /
    # interceptor-chain machinery multiplies CratonVM's per-call dispatch cost
    # across all of them (see reference_junit5_execution_machinery_dispatch_overhead
    # in project memory) -- CPU-bound, not stuck. Keep headroom above the
    # observed time (extra margin for contention when run alongside other
    # slow classes in the same -Parallel batch) instead of reporting a false
    # HANG.
    'core/spring-boot|org.springframework.boot.env.OriginTrackedYamlLoaderTests' = 1100
    # CORE39-CLUSTERA.2 (2026-07-24): ConfigurationPropertySourcesTests was
    # reported as a HANG at 300s. Extensive diagnosis (CPU-sampling across
    # multiple stack dumps at 60s/400s/1100s -- pegged near 100% CPU
    # throughout, never parked/blocked; a hand-scaled-down repro of its own
    # perf-test shape -- N property sources x M keys x K
    # `environment.getProperty()` iterations -- measured CONSTANT
    # per-iteration cost, ~47ms/iter at 5 sources x 1000 keys, no quadratic
    # growth across 20-iteration buckets, confirmed linear not superlinear
    # scaling) all point to a real but DIFFUSE interpreter/dispatch
    # throughput gap, not a deadlock -- consistent with the already-tracked
    # reference_hashmap_native_call_dispatch_overhead /
    # reference_junit5_execution_machinery_dispatch_overhead family in
    # project memory. The class deliberately exercises an "uncached"
    # O(sources x keys) baseline against ~100 property sources x 1000 keys x
    # 1000 iterations (explicit `cached < uncached/2` perf assertions) --
    # genuinely CPU-heavy by design, not merely slow-to-start. A standalone
    # rerun completed (PASS) in 2645.0s; keep headroom above that observed
    # time instead of reporting a false HANG.
    #
    # NOTE: `ConfigurationPropertiesBeanRegistrationAotProcessorTests` (the
    # other class originally reported alongside this one) is DELIBERATELY
    # NOT in this table -- unlike this class, it never completed even at a
    # 7200s (2-hour) ceiling with ZERO of its 9 `@Test` methods reporting a
    # result, and a CPU-sampled stack repeatedly lands at the identical
    # bytecode offset in Hibernate Validator's
    # `BeanMetaDataImpl.getClassLevelConstraintsAsDescriptors` across samples
    # taken minutes and hours apart -- a real, still-unfixed hang, not a
    # throughput gap. Do not paper over it with a timeout; see
    # docs/known-issues/springboot/configurationpropertiesbeanregistrationaotprocessortests-hang.md.
    'core/spring-boot|org.springframework.boot.context.properties.source.ConfigurationPropertySourcesTests' = 5400
  }
  $key = "$($ClassRow.module)|$($ClassRow.class)"
  if ($slowClasses.ContainsKey($key)) {
    return [Math]::Max($BaseTimeoutSec, $slowClasses[$key])
  }
  return $BaseTimeoutSec
}

function New-ProcessRecord {
  param([object]$ClassRow, [string]$ModeOut, [object]$LaunchSpec, [string]$ExePath, [string]$JavaExe, [string]$JdkPath, [bool]$NoJit, [int]$Timeout, [int]$Retries = 0)
  $module = [string]$ClassRow.module
  $class = [string]$ClassRow.class
  $workingDirectory = $script:SpringBootDir
  $modulePath = $module -replace '/', [System.IO.Path]::DirectorySeparatorChar
  $moduleRoot = Join-Path $script:SpringBootDir $modulePath
  if (Test-Path $moduleRoot) { $workingDirectory = $moduleRoot }
  $logDir = Join-Path $ModeOut 'logs'
  New-Item -ItemType Directory -Force -Path $logDir | Out-Null
  # `WriteAllText` still observes the legacy MAX_PATH limit on some Windows
  # PowerShell/.NET Framework combinations.  Worktree and run names are both
  # intentionally unique and can be long, so size the per-class stem from the
  # actual log-directory prefix rather than assuming the historical 96-char
  # cap always leaves room for the extension.
  $maxStemLength = [Math]::Max(16, 240 - $logDir.Length - '.out.log'.Length - 1)
  $safe = ConvertTo-SafeFileStem "$module.$class" -MaxLength $maxStemLength
  $outFile = Join-Path $logDir "$safe.out.log"
  $errFile = Join-Path $logDir "$safe.err.log"

  if ($Vm -eq 'hotspot') {
    $file = $JavaExe
    # Several modules' own build.gradle add --add-opens=java.base/java.net=ALL-UNNAMED
    # to their Gradle `test` task JVM args (jetty/security/servlet/tomcat/webflux/
    # websocket -- reflective field reset in their web-server test fixtures). This
    # runner launches SbRunner directly instead of through Gradle's test task, so
    # none of those per-module jvmArgs apply; without it those classes fail with
    # "IllegalStateException: Unable to reset field" on real HotSpot too, which is
    # a harness gap, not a genuine VM behavior difference. Apply it universally --
    # opens are additive and harmless for modules that don't need it.
    $args = @("-Xmx$MaxHeap", '-Dfile.encoding=UTF-8', '-Djava.awt.headless=true', '--add-opens=java.base/java.net=ALL-UNNAMED')
    if ($NoJit) { $args += '-Xint' }
    if ($LaunchSpec.kind -eq 'jar') { $args += @('-jar', $LaunchSpec.value, $class) }
    else { $args += @('-cp', $LaunchSpec.value, 'SbRunner', $class) }
  } else {
    $file = $ExePath
    $args = @('--java-home', $JdkPath, '--Xmx', $MaxHeap)
    # The suite normally disables the VM watchdog because it owns the
    # per-class timeout.  Preserve that default, but let a caller provide a
    # real watchdog value through -CratonArgs for a diagnostic run.
    $hasWatchdogArg = @($CratonArgs | Where-Object { $_ -match '^--stack-dump-on-timeout(?:=|$)' }).Count -gt 0
    if (-not $hasWatchdogArg) { $args += @('--stack-dump-on-timeout', '0') }
    if ($NoJit) { $args += '--nojit' }
    if ($CratonArgs.Count -gt 0) { $args += $CratonArgs }
    $args += @('-Dfile.encoding=UTF-8', '-Djava.awt.headless=true')
    if ($LaunchSpec.kind -eq 'jar') { $args += @('--jar', $LaunchSpec.value, $class) }
    else { $args += @('-cp', $LaunchSpec.value, 'SbRunner', $class) }
  }

  $psi = [System.Diagnostics.ProcessStartInfo]::new()
  $psi.FileName = $file
  $psi.WorkingDirectory = $workingDirectory
  $psi.UseShellExecute = $false
  $psi.CreateNoWindow = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  # Spring Boot's JUL formatter deliberately treats LOG_FORMAT as an
  # application-facing override.  Letting a developer's ambient value leak
  # into every direct JUnit launch changes assertions that exercise its
  # documented default format (for example JavaLoggingSystemTests), and makes
  # the CratonVM/HotSpot comparison host-dependent.  The runner owns a
  # hermetic test-process environment, so remove only this formatter override;
  # individual tests can still set the Java system property explicitly.
  [void]$psi.Environment.Remove('LOG_FORMAT')
  Set-ProcessArguments -StartInfo $psi -Arguments $args
  $proc = [System.Diagnostics.Process]::new()
  $proc.StartInfo = $psi
  [void]$proc.Start()
  return [pscustomobject]@{
    proc = $proc
    stdoutTask = $proc.StandardOutput.ReadToEndAsync()
    stderrTask = $proc.StandardError.ReadToEndAsync()
    module = $module; class = $class; start = Get-Date
    outFile = $outFile; errFile = $errFile; timeoutSec = $Timeout; retries = $Retries
  }
}

function Read-ProcessOutputs([object]$Record) {
  try { $Record.stdoutTask.Wait(5000) | Out-Null } catch {}
  try { $Record.stderrTask.Wait(5000) | Out-Null } catch {}
  $stdout = ''; $stderr = ''
  try { $stdout = $Record.stdoutTask.Result } catch {}
  try { $stderr = $Record.stderrTask.Result } catch {}
  return [pscustomobject]@{ stdout = $stdout; stderr = $stderr }
}

function Complete-ProcessRecord {
  param([object]$Record, [string]$ResultPath, [object]$ExitCode, [double]$Seconds, [string]$Stdout, [string]$Stderr)
  [System.IO.File]::WriteAllText($Record.outFile, $Stdout, [System.Text.Encoding]::UTF8)
  [System.IO.File]::WriteAllText($Record.errFile, $Stderr, [System.Text.Encoding]::UTF8)
  $combined = "$Stdout`n$Stderr"
  $status = 'NOSUMMARY'; $tests = 0; $failed = 0; $aborted = 0; $skipped = 0; $containersFailed = 0

  if ([string]$ExitCode -eq 'TIMEOUT') {
    $status = 'HANG'
  } elseif ($combined -match '(?i)EXCEPTION_ACCESS_VIOLATION|SIGSEGV|fatal runtime error|panicked at|stack smashing|illegal instruction|STATUS_ACCESS|STATUS_STACK_BUFFER|caught fatal signal|cratonvm panic|internal error: entered unreachable') {
    $status = 'CRASH'
  }

  $m = [regex]::Match($combined, 'SBRUNNER_RESULT tests=(\d+) failed=(\d+) aborted=(\d+) skipped=(\d+) containersFailed=(\d+)')
  if ($m.Success) {
    $tests = [int]$m.Groups[1].Value; $failed = [int]$m.Groups[2].Value; $aborted = [int]$m.Groups[3].Value
    $skipped = [int]$m.Groups[4].Value; $containersFailed = [int]$m.Groups[5].Value
    if ($status -ne 'CRASH' -and $status -ne 'HANG') {
      if ($combined -match 'SBRUNNER_LOAD_FAIL') { $status = 'LOADFAIL' }
      elseif ($failed -gt 0 -or $aborted -gt 0 -or $containersFailed -gt 0) { $status = 'FAIL' }
      elseif ($tests -eq 0) { $status = 'EMPTY' }
      else { $status = 'PASS' }
    }
  } elseif ($status -ne 'HANG' -and $status -ne 'CRASH' -and $ExitCode -ne 0) {
    $status = 'CRASH'
  }

  $note = ''
  if ($status -ne 'PASS' -and $status -ne 'EMPTY') {
    $noteMatch = [regex]::Match($combined, '(?im)^(?!\s+at\s)(.*(?:Exception|Error|Caused by|SBRUNNER_LOAD_FAIL|panicked|not implemented|NoClassDef|NoSuchMethod|AbstractMethod|AssertionError).*)$')
    if ($noteMatch.Success) { $note = (($noteMatch.Groups[1].Value -replace "`t", ' ') -replace "`r|`n", ' ') }
  }
  if ($note.Length -gt 180) { $note = $note.Substring(0, 180) }

  $line = @(
    $script:ResultIndex, $Record.module, $Record.class, $Vm, $(if ($Jit -eq 'off') { 'off' } else { 'on' }),
    $ExitCode, $status, (ConvertTo-InvariantString $Seconds), $tests, $failed, $aborted, $skipped, $containersFailed,
    $Record.outFile, $Record.errFile, $note
  ) -join "`t"
  Add-Content -Path $ResultPath -Value $line -Encoding ascii
  $script:ResultIndex++
  Write-Host ("  [{0}] {1,-9} {2,7:N1}s {3}.{4}" -f $script:EffectiveModeName, $status, $Seconds, $Record.module, $Record.class)
}

function Invoke-Mode {
  param([object[]]$Classes)
  $jdk = Resolve-Jdk
  $javaBin = Join-Path $jdk 'bin'
  $java = @((Join-Path $javaBin 'java.exe'), (Join-Path $javaBin 'java')) | Where-Object { Test-Path $_ } | Select-Object -First 1
  if (-not $java) { Die "HotSpot java executable not found under: $javaBin" }
  $craton = ''
  if ($Vm -eq 'craton') {
    $craton = Resolve-CratonExe
    # Matches tomcat-suite-runner's craton knobs. CRATONVM_REAL_NET_SOCKETS in
    # particular is load-bearing here: without it, java.net.ServerSocket uses
    # the legacy synthetic layout whose field-slot mapping doesn't match the
    # real JDK-25 class (declaration order impl@0/created@1/bound@2/closed@3/
    # socketLock@4/options@5), so socketLock reads back null and any real
    # bind (Hazelcast, embedded servers, etc.) throws
    # "NullPointerException: Cannot enter synchronized block because
    # this.socketLock is null" — see docs/known-issues (reference_server_socket_gap
    # in memory) for the full history; this is a known, already-fixed-behind-
    # a-flag issue, not something to re-report as a new bug.
    $env:CRATONVM_REAL = 'net-sockets,aqs'
    $env:CRATONVM_THREADS = '-default-watchdog'
    $env:CRATONVM_JIT = 'rootsnap-cache'
  }

  $run = $RunName
  if (-not $run) { $run = Get-Date -Format 'yyyyMMdd-HHmmss' }
  $mode = $ModeName
  if (-not $mode) {
    if ($Vm -eq 'hotspot') { $mode = if ($Jit -eq 'off') { 'hotspot-xint' } else { 'hotspot-jit' } }
    else { $mode = "$Category-$(if ($Jit -eq 'off') { 'nojit' } else { 'jit' })" }
  }
  $script:EffectiveModeName = $mode

  $modeOut = Join-Path (Join-Path (Join-Path $script:WorkRoot 'results') $run) $mode
  New-Item -ItemType Directory -Force -Path $modeOut | Out-Null
  $results = Join-Path $modeOut 'results.tsv'
  if (-not (Test-Path $results)) {
    "index`tmodule`tclass`tvm`tjit`trc`tstatus`tseconds`ttests`tfailed`taborted`tskipped`tcontainersFailed`tstdoutLog`tstderrLog`tnote" | Set-Content -Path $results -Encoding ascii
  }
  $done = @{}
  foreach ($row in (Import-Csv -Path $results -Delimiter "`t")) { if ($row.class) { $done["$($row.module)`t$($row.class)"] = $true } }
  $todo = @($Classes | Where-Object { -not $done.ContainsKey("$($_.module)`t$($_.class)") })
  $script:ResultIndex = (Import-Csv -Path $results -Delimiter "`t").Count + 1

  Write-Info "mode=$mode vm=$Vm jit=$Jit category=$Category selected=$($Classes.Count) todo=$($todo.Count) parallel=$Parallel timeout=${TimeoutSec}s"
  if ($Vm -eq 'craton') { Write-Info "craton exe=$craton" }
  Write-Info "logs/results=$modeOut"

  $modeStarted = Get-Date
  $script:RunningRecords = New-Object System.Collections.Generic.List[object]

  function Drain-Running {
    $still = New-Object System.Collections.Generic.List[object]
    foreach ($record in $script:RunningRecords) {
      $elapsed = ((Get-Date) - $record.start).TotalSeconds
      if ($record.proc.HasExited) {
        $code = $record.proc.ExitCode
        $outputs = Read-ProcessOutputs $record
        Complete-ProcessRecord -Record $record -ResultPath $results -ExitCode $code -Seconds ([Math]::Round($elapsed, 3)) -Stdout $outputs.stdout -Stderr $outputs.stderr
        try { $record.proc.Dispose() } catch {}
      } elseif ($elapsed -ge $record.timeoutSec) {
        try { $record.proc.Kill($true) } catch { try { $record.proc.Kill() } catch {} }
        try { $record.proc.WaitForExit(5000) | Out-Null } catch {}
        $outputs = Read-ProcessOutputs $record
        Complete-ProcessRecord -Record $record -ResultPath $results -ExitCode 'TIMEOUT' -Seconds ([Math]::Round($elapsed, 3)) -Stdout $outputs.stdout -Stderr $outputs.stderr
        try { $record.proc.Dispose() } catch {}
      } else { $still.Add($record) }
    }
    $script:RunningRecords = $still
  }

  foreach ($classRow in $todo) {
    while ($script:RunningRecords.Count -ge $Parallel) { Drain-Running; if ($script:RunningRecords.Count -ge $Parallel) { Start-Sleep -Milliseconds 200 } }
    $launch = Get-LaunchSpec -ClassRow $classRow
    $classTimeoutSec = Get-EffectiveClassTimeoutSec -ClassRow $classRow -BaseTimeoutSec $TimeoutSec
    if ($classTimeoutSec -ne $TimeoutSec) { Write-Info "timeout override=${classTimeoutSec}s $($classRow.module).$($classRow.class)" }
    $script:RunningRecords.Add((New-ProcessRecord -ClassRow $classRow -ModeOut $modeOut -LaunchSpec $launch -ExePath $craton -JavaExe $java -JdkPath $jdk -NoJit:($Jit -eq 'off') -Timeout $classTimeoutSec))
  }
  while ($script:RunningRecords.Count -gt 0) { Drain-Running; if ($script:RunningRecords.Count -gt 0) { Start-Sleep -Milliseconds 200 } }
  Remove-Variable -Name RunningRecords -Scope Script -ErrorAction SilentlyContinue

  $elapsed = [Math]::Round(((Get-Date) - $modeStarted).TotalSeconds, 3)
  $rows = @(Import-Csv -Path $results -Delimiter "`t")
  $summaryPath = Join-Path $modeOut 'summary.md'
  $counts = $rows | Group-Object status | Sort-Object Name
  $classSeconds = 0.0
  foreach ($row in $rows) { $classSeconds += ConvertFrom-InvariantString ([string]$row.seconds) }

  $summary = New-Object System.Collections.Generic.List[string]
  $summary.Add("# Spring Boot suite result")
  $summary.Add(""); $summary.Add("- run: $run"); $summary.Add("- mode: $mode"); $summary.Add("- vm: $Vm"); $summary.Add("- jit: $Jit")
  $summary.Add("- category: $Category"); $summary.Add("- classes recorded: $($rows.Count)")
  $summary.Add("- wall seconds: $(ConvertTo-InvariantString $elapsed)"); $summary.Add("- summed class seconds: $(ConvertTo-InvariantString $classSeconds)")
  $summary.Add("- spring-boot root: $script:SpringBootDir")
  if ($Vm -eq 'craton') { $summary.Add("- craton exe: $craton") }
  $summary.Add(""); $summary.Add("## Status Counts")
  foreach ($group in $counts) { $summary.Add("- $($group.Name): $($group.Count)") }
  $summary.Add(""); $summary.Add("## Files"); $summary.Add("- results: $results"); $summary.Add("- logs: $(Join-Path $modeOut 'logs')")
  $summary | Set-Content -Path $summaryPath -Encoding ascii

  if ($Vm -eq 'hotspot') {
    $baselineDir = Join-Path $script:WorkRoot 'baseline'
    New-Item -ItemType Directory -Force -Path $baselineDir | Out-Null
    $baselineBase = "hotspot-baseline-$run"
    Copy-Item -Path $results -Destination (Join-Path $baselineDir "$baselineBase.tsv") -Force
    Copy-Item -Path $summaryPath -Destination (Join-Path $baselineDir "$baselineBase.md") -Force
    Copy-Item -Path $results -Destination (Join-Path $baselineDir 'hotspot-baseline-latest.tsv') -Force
    Copy-Item -Path $summaryPath -Destination (Join-Path $baselineDir 'hotspot-baseline-latest.md') -Force
    Write-Info "baseline copied to $baselineDir\$baselineBase.tsv"
  }
  Write-Info "DONE mode=$mode wall=${elapsed}s summary=$summaryPath"
}

function Invoke-AllModes {
  $run = $RunName
  if (-not $run) { $run = Get-Date -Format 'yyyyMMdd-HHmmss' }
  $self = $PSCommandPath
  $psExe = Get-PowerShellExe
  $modes = @(
    @{ jit = 'on';  name = 'jit' },
    @{ jit = 'off'; name = 'nojit' }
  )
  $runRoot = Join-Path (Join-Path $script:WorkRoot 'results') $run
  New-Item -ItemType Directory -Force -Path $runRoot | Out-Null
  $children = @()
  foreach ($mode in $modes) {
    $log = Join-Path $runRoot "$($mode.name).console.log"
    $err = Join-Path $runRoot "$($mode.name).console.err.log"
    $args = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $self,
      '-Category', $Category, '-Jit', $mode.jit, '-Vm', 'craton',
      '-Start', $Start, '-Count', $Count, '-Parallel', $Parallel, '-TimeoutSec', $TimeoutSec,
      '-RunName', $run, '-ModeName', $mode.name, '-SpringBootRoot', $script:SpringBootDir,
      '-WorkDir', $script:WorkRoot, '-JdkHome', (Resolve-Jdk), '-MaxHeap', $MaxHeap)
    if ($Exe) { $args += @('-Exe', $Exe) }
    if ($RefCsv) { $args += @('-RefCsv', $RefCsv) }
    if ($ClassList) { $args += @('-ClassList', $ClassList) }
    if ($CratonArgs.Count -gt 0) { foreach ($extra in $CratonArgs) { $args += @('-CratonArgs', $extra) } }
    Write-Info "launching $($mode.name) in background"
    $children += Start-RedirectedProcess -FilePath $psExe -Arguments $args -WorkingDirectory $script:RepoRoot -StdoutPath $log -StderrPath $err
  }
  $failedChildren = 0
  foreach ($child in $children) { $exitCode = Complete-RedirectedProcess $child; if ($exitCode -ne 0) { $failedChildren++ } }
  if ($failedChildren -gt 0) { Die "$failedChildren all-mode child process(es) failed; inspect $runRoot\*.console*.log" }
  Write-Info "ALL MODES DONE. Results under $runRoot"
}

$script:RepoRoot = Get-RepoRoot
if (-not $SpringBootRoot) {
  $appsRoot = Split-Path $PSScriptRoot -Parent
  $SpringBootRoot = Join-Path $appsRoot 'spring-boot'
}
$script:SpringBootDir = [System.IO.Path]::GetFullPath($SpringBootRoot)
if (-not (Test-Path $script:SpringBootDir)) { Die "Spring Boot root not found: $script:SpringBootDir" }
$script:SbRunnerDir = Join-Path $script:SpringBootDir 'sb-runner'
if (-not (Test-Path (Join-Path $script:SbRunnerDir 'SbRunner.class'))) { Die "missing SbRunner.class in $script:SbRunnerDir (javac SbRunner.java against the JUnit platform jars first)" }

if (-not $WorkDir) { $WorkDir = Join-Path $PSScriptRoot '.suite' }
$script:WorkRoot = [System.IO.Path]::GetFullPath($WorkDir)
New-Item -ItemType Directory -Force -Path $script:WorkRoot | Out-Null

if ($Start -lt 1) { Die "-Start is 1-based and must be >= 1" }
if ($Count -lt 0) { Die "-Count must be >= 0" }
if ($Parallel -lt 1) { Die "-Parallel must be >= 1" }
if ($TimeoutSec -lt 1) { Die "-TimeoutSec must be >= 1" }

if ($Setup) {
  Invoke-GradleSetup
  if (-not $AllModes -and $Category -eq 'all' -and -not $ListOnly -and $Count -eq 0 -and $Start -eq 1) {
    Write-Info "Setup-only invocation complete (no -Count given). Re-run without -Setup to execute."
    return
  }
}

if ($AllModes) {
  if ($Vm -ne 'craton') { Die "-AllModes is CratonVM-only" }
  Invoke-AllModes
  return
}

$classes = @(Get-SelectedClasses)
Write-Info "selected $($classes.Count) classes (category=$Category start=$Start count=$(if ($Count -gt 0) { $Count } else { 'all' }))"
if ($ListOnly) {
  $i = $Start
  foreach ($class in $classes) { "{0}`t{1}`t{2}" -f $i, $class.module, $class.class; $i++ }
  return
}
if ($classes.Count -eq 0) { Die "no classes selected" }

Invoke-Mode -Classes $classes
