[package]
name = "cratonvm-jit"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "x86-64 JIT compiler for CratonVM"
documentation = "https://docs.rs/cratonvm-jit"
readme = "../README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cratonvm-types = { path = "../types" }
cratonvm-reader = { path = "../reader" }
cratonvm-jit-api = { path = "../jit-api" }
parking_lot.workspace = true
rustc-hash.workspace = true

[features]
vm-tests = []

[dev-dependencies]
cratonvm-gc = { path = "../gc" }

[lints]
workspace = true
