[package]
name = "cratonvm-jit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "x86-64 JIT compiler for CratonVM"
readme = "README.md"
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cratonvm-types = { path = "../types", version = "0.3.0" }
cratonvm-reader = { path = "../reader", version = "0.3.0" }
cratonvm-jit-api = { path = "../jit-api", version = "0.3.0" }
parking_lot.workspace = true
rustc-hash.workspace = true
tracing.workspace = true

[features]
vm-tests = []

[dev-dependencies]
cratonvm-gc = { path = "../gc", version = "0.3.0" }

[lints]
workspace = true
