[package]
name = "cratonvm-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
cratonvm-reader = { path = "../reader" }

[[bin]]
name = "fuzz_classfile"
path = "fuzz_targets/fuzz_classfile.rs"
test = false
doc = false

[[bin]]
name = "read_class"
path = "fuzz_targets/read_class.rs"
test = false
doc = false
