# Keycloak. Genuinely BUILT on this host, and genuinely NOT RUNNABLE.
#
# Measured 2026-08-12 (B7). The build output is real and substantial:
#
#     /data/cratonvm/apps/keycloak            97 target/classes, 58 target/test-classes
#                                        7779 main .class, 2254 test .class,
#                                        1400 *Test.class
#     /data/cratonvm/apps/keycloak   83 / 38, 7383 main, 1572 test, 856 *Test
#
# So this is NOT the `apps/spring-boot` shape (a `*-suite-runner` directory and
# no corpus) and it is NOT the H2 decoy shape (a target/classes holding one
# file). Keycloak really is compiled here.
#
# What is missing is the dependency classpath. `kc-universal-cp.txt` at the
# root is the dump generated by
# apps/keycloak-suite-runner/generate-kc-universal-cp.ps1, and of its **247
# entries, 114 do not exist**. The survivors are not a usable subset: the
# casualties include jackson-databind, jackson-core and the jackson datatype
# modules, which essentially every Keycloak class touches.
#
# The eviction is mostly POINT-VERSION DRIFT rather than wholesale deletion --
# the dump names jackson-core 2.21.2 and the repository now holds 2.21.3, and
# the same is true of most of the 114. That makes a "nearest version" rewrite
# tempting and it is deliberately NOT done here: silently substituting a
# different dependency version under an application produces genuine
# NoSuchMethodErrors and NoClassDefFoundErrors that are indistinguishable, in
# the log, from the VM defects this corpus exists to find. If they are wanted,
# `mvn -o dependency:build-classpath` will re-resolve them honestly.
#
# The other four also-empty dumps in that root (`cp.txt`,
# `cratonvm-{core,crypto,cryptodef,full}-cp.txt`) are ZERO BYTES and are not
# read: a zero-byte classpath dump is a failed dump, not an empty classpath.
#
# This file therefore does what hibernate.sh does -- refuse loudly, with the
# measurement, rather than compose a partial classpath. When the maven
# dependencies are re-resolved this corpus starts working with no edit.

CORPUS_DESC="Keycloak server + its unit tests"
CORPUS_KIND=junit
CORPUS_CONFIDENCE=blocked
CORPUS_NOTE="BLOCKED: built (7779 main / 1400 *Test.class) but 114 of 247 dumped classpath entries are evicted .m2 jars, jackson among them. Needs a maven re-resolve, not a path fix."

CORPUS_ROOT_CANDIDATES="/data/cratonvm/apps/keycloak /data/cratonvm/apps/keycloak"

CORPUS_RUNNER_CLASS="SbRunner"
CORPUS_RUNNER_SRC="/data/cratonvm/apps/spring-boot/sb-runner/SbRunner.java"
CORPUS_DEFAULT_CLASS=""

KC_CP_DUMP="kc-universal-cp.txt"

corpus_is_built() {
  local r="$1"
  [ -n "$(find "$r" -path '*/target/classes/*' -name '*.class' 2>/dev/null | head -1)" ] || return 1
  return 0
}

corpus_classpath() {
  local r="$1" f="$1/$KC_CP_DUMP" j tot=0 miss=0

  if [ ! -s "$f" ]; then
    echo "ERROR: keycloak has no usable classpath dump at $f." >&2
    echo "       The four cratonvm-*-cp.txt dumps in this root are ZERO BYTES -- a failed" >&2
    echo "       dump, not an empty classpath. Regenerate with" >&2
    echo "       apps/keycloak-suite-runner/generate-kc-universal-cp.ps1." >&2
    return 1
  fi

  for j in $(tr ';' '\n' < "$f"); do
    tot=$((tot+1))
    if [ -e "$j" ]; then cp_add "$j"; else miss=$((miss+1)); fi
  done

  # Same refusal rule as hibernate.sh. Running with the survivors would
  # manufacture NoClassDefFoundErrors that read as VM regressions.
  if [ "$miss" -gt 0 ]; then
    echo "ERROR: keycloak classpath is not usable on this host: $((tot-miss)) entries exist, $miss do not." >&2
    echo "       The missing ones are .m2 jars that have been EVICTED or point-version" >&2
    echo "       upgraded since $f was dumped (e.g. the dump names jackson-core 2.21.2" >&2
    echo "       and this host now carries 2.21.3). jackson-databind is among the" >&2
    echo "       casualties, so the survivors are NOT a runnable subset." >&2
    echo "       This is a fixture problem: re-resolve with 'mvn -o dependency:build-classpath'" >&2
    echo "       and re-dump. Substituting nearest versions is NOT done automatically," >&2
    echo "       because a swapped dependency version produces linkage errors that are" >&2
    echo "       indistinguishable from the VM defects this corpus exists to find." >&2
    return 1
  fi

  local m
  while IFS= read -r m; do [ -n "$m" ] && cp_add "$m"; done < <(find "$r" -type d -path '*/target/classes' 2>/dev/null)
  while IFS= read -r m; do [ -n "$m" ] && cp_add "$m"; done < <(find "$r" -type d -path '*/target/test-classes' 2>/dev/null)
  return 0
}

corpus_discover() {
  local r="$1" f rel base
  while IFS= read -r base; do
    [ -n "$base" ] || continue
    find "$base" -name '*Test.class' 2>/dev/null | sort | while IFS= read -r f; do
      case "$f" in *'$'*) continue ;; esac
      rel="${f#"$base/"}"; rel="${rel%.class}"
      printf '%s\n' "${rel//\//.}"
    done
  done < <(find "$r" -type d -path '*/target/test-classes' 2>/dev/null | sort)
}
