status=error
appender.stdout.type=Console
appender.stdout.name=stdout
appender.stdout.layout.type=PatternLayout
appender.stdout.layout.pattern=%p [%c] %m%n
rootLogger.level=warn
rootLogger.appenderRef.stdout.ref=stdout
logger.junit.name=org.hibernate.testing.orm.junit
logger.junit.level=debug
logger.junit.additivity=false
logger.junit.appenderRef.stdout.ref=stdout
logger.jdbc-error.name=org.hibernate.orm.jdbc.error
logger.jdbc-error.level=warn
logger.jdbc-error.additivity=false
logger.jdbc-error.appenderRef.stdout.ref=stdout
