// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Craton Software Company
//
// What a BIGGER FRAME costs, holding the executed body constant.
//
// The interpreter builds a callee frame by sizing two buffers to the method's
// `max_locals` and `max_stack` and filling them. Everything else about a call
// -- the dispatch, the argument transfer, the push -- is independent of those
// two numbers. So the difference between calling a method with a small frame
// and one with a large frame, when both bodies execute the SAME bytecode, is
// the per-frame sizing and fill cost and nothing else.
//
// Each `big` arm declares its locals (or builds its deep expression) inside a
// branch that is never taken -- the caller never passes Integer.MIN_VALUE --
// so javac raises `max_locals` / `max_stack` for the whole method while the
// executed path stays the same few bytecodes as the `small` arm. Read the
// DELTA between arms, not either arm alone: the body difference (one extra
// compare) is constant across binaries and cancels.
//
// Generated by scratchpad/gen_frameshape.py so the nesting is balanced.
//
// Interleaves its arms in both directions on alternating rounds and reports
// min-of-N, like every other probe on
// docs/known-issues/perf/interpreted-invoke-cost-350ns-20260825.md.
public class FrameShape {

    // max_locals ~= 2, max_stack ~= 2
    static int small(int a) {
        return a;
    }

    // max_locals ~= 50, max_stack small. The branch never runs.
    static int locals48(int a) {
        if (a == Integer.MIN_VALUE) {
            int l0=a,l1=a,l2=a,l3=a,l4=a,l5=a,l6=a,l7=a,l8=a,l9=a;
            int l10=a,l11=a,l12=a,l13=a,l14=a,l15=a,l16=a,l17=a,l18=a,l19=a;
            int l20=a,l21=a,l22=a,l23=a,l24=a,l25=a,l26=a,l27=a,l28=a,l29=a;
            int l30=a,l31=a,l32=a,l33=a,l34=a,l35=a,l36=a,l37=a,l38=a,l39=a;
            int l40=a,l41=a,l42=a,l43=a,l44=a,l45=a,l46=a,l47=a;
           return l0 + l1 + l2 + l3 + l4 + l5 + l6 + l7 + l8 + l9 + l10 + l11 + l12 +
               l13 + l14 + l15 + l16 + l17 + l18 + l19 + l20 + l21 + l22 + l23 + l24 +
               l25 + l26 + l27 + l28 + l29 + l30 + l31 + l32 + l33 + l34 + l35 + l36 +
               l37 + l38 + l39 + l40 + l41 + l42 + l43 + l44 + l45 + l46 + l47;
        }
        return a;
    }

    // max_locals ~= 2, max_stack ~= 34: one deep expression, never evaluated.
    static int stack32(int a) {
        if (a == Integer.MIN_VALUE) {
           return a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a +
               (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a + (a
               + (a + (a + (a)))))))))))))))))))))))))))))));
        }
        return a;
    }

    // Both, which is what an ordinary framework method looks like.
    static int both(int a) {
        if (a == Integer.MIN_VALUE) {
            int l0=a,l1=a,l2=a,l3=a,l4=a,l5=a,l6=a,l7=a,l8=a,l9=a;
            int l10=a,l11=a,l12=a,l13=a,l14=a,l15=a,l16=a,l17=a,l18=a,l19=a;
            int l20=a,l21=a,l22=a,l23=a,l24=a,l25=a,l26=a,l27=a,l28=a,l29=a;
            int l30=a,l31=a,l32=a,l33=a,l34=a,l35=a,l36=a,l37=a,l38=a,l39=a;
            int l40=a,l41=a,l42=a,l43=a,l44=a,l45=a,l46=a,l47=a;
           return l0 + (l1 + (l2 + (l3 + (l4 + (l5 + (l6 + (l7 + (l8 + (l9 + (l10 + (l11
               + (l12 + (l13 + (l14 + (l15 + (l16 + (l17 + (l18 + (l19 + (l20 + (l21 +
               (l22 + (l23 + (l24 + (l25 + (l26 + (l27 + (l28 + (l29 + (l30 + (l31 +
               (l32 + (l33 + (l34 + (l35 + (l36 + (l37 + (l38 + (l39 + (l40 + (l41 +
               (l42 + (l43 + (l44 + (l45 + (l46 +
               (l47)))))))))))))))))))))))))))))))))))))))))))))));
        }
        return a;
    }

    static int cNone(int n){int s=0;for(int i=0;i<n;i++) s+=i; return s;}
    static int cSmall(int n){int s=0;for(int i=0;i<n;i++) s+=small(i); return s;}
    static int cLocals(int n){int s=0;for(int i=0;i<n;i++) s+=locals48(i); return s;}
    static int cStack(int n){int s=0;for(int i=0;i<n;i++) s+=stack32(i); return s;}
    static int cBoth(int n){int s=0;for(int i=0;i<n;i++) s+=both(i); return s;}

    public static void main(String[] a) {
        int n = a.length > 0 ? Integer.parseInt(a[0]) : 1000000;
        int rounds = a.length > 1 ? Integer.parseInt(a[1]) : 9;
        // Optional third argument: run ONE arm only. The rdtsc phase
        // counters (CRATONVM_DBG=invoke-phases) are process-wide, so
        // isolating an arm is the only way to read a per-arm breakdown
        // out of them.
        String only = a.length > 2 ? a[2] : null;
        String[] nm = {"nocall", "small", "locals48", "stack32", "both"};
        double[] m = new double[nm.length];
        for (int i = 0; i < m.length; i++) m[i] = 1e18;
        int sink = 0; long t;
        for (int r = 0; r < rounds; r++) {
            boolean fwd = (r & 1) == 0;
            for (int k = 0; k < nm.length; k++) {
                int j = fwd ? k : nm.length - 1 - k;
                if (only != null && !nm[j].equals(only)) continue;
                t = System.nanoTime();
                switch (j) {
                    case 0: sink += cNone(n); break;
                    case 1: sink += cSmall(n); break;
                    case 2: sink += cLocals(n); break;
                    case 3: sink += cStack(n); break;
                    default: sink += cBoth(n); break;
                }
                double d = (System.nanoTime() - t) / (double) n;
                if (d < m[j]) m[j] = d;
            }
        }
        for (int i = 0; i < nm.length; i++) {
            if (only != null && !nm[i].equals(only)) continue;
            System.out.println(nm[i] + "\t" + m[i] + " ns/iter\tdelta=" + (m[i] - m[0]));
        }
        if (only != null) { if (sink == 42) System.out.println("x"); return; }
        System.out.println("per-call frame cost, small       = " + (m[1] - m[0]));
        System.out.println("48 extra local slots cost        = " + (m[2] - m[1]));
        System.out.println("32 extra stack slots cost        = " + (m[3] - m[1]));
        System.out.println("both                             = " + (m[4] - m[1]));
        if (sink == 42) System.out.println("x");
    }
}
