// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Craton Software Company

//! RT-8's cold-body sweeper, end to end, on the workload it exists for.
//!
//! # What this pins
//!
//! `CodeCacheSweepPhases` (generated by `tools/probes/gen-sweep-phases.py
//! 600 4 cratonvm.CodeCacheSweepPhases`) is 600 small methods in four phases.
//! Each phase makes its own 150 hot and never calls the previous phase's again.
//! At a 1 MiB cap the cache fills during phase 0, so every later phase runs
//! against a cache full of dead code. That is the case the sweeper exists for.
//!
//! This test asserts that the sweeper actually recovers from it:
//!
//! * every phase's answer equals an independent Rust model of the arithmetic.
//!   A swept body is demoted and recompiled, and none of that may change a
//!   result;
//! * the cap was really hit (`cap_refusals > 0`), or the rest proves nothing;
//! * bytes actually came back to the OS (`reclaimed_bytes > 0`), not merely
//!   bodies withdrawn;
//! * the LAST phase's methods got compiled bodies. They went hot only after
//!   the cap was hit, so they can have compiled only into room a sweep freed.
//!
//! # The four defects it would have caught (RT-8 soak, 2026-09-18)
//!
//! Before the soak, the last two assertions failed together, for four
//! independent reasons, any one of which was enough:
//!
//! 1. the sweep's rate limit read "no compiled body entered" as "nothing ran"
//!    and refused on every call once the program moved on;
//! 2. a cap refusal was charged to the method's compile-failure budget, so
//!    after three the method was settled for good;
//! 3. a withdrawal did not expire the method's "settled" stamp, so its call
//!    sites never asked the manager again;
//! 4. interpreter dispatch caches owned every withdrawn body behind call
//!    sites that never ran again, so a sweep freed no byte.
//!
//! # ONE `#[test]`
//!
//! The cap, the sweeper and the entry counter are process-wide latched flags,
//! and `COMMITTED_JIT_CODE_BYTES` is process-global. Another test in this
//! binary would share the cap.

use cratonvm_vm::config::VmConfig;
use cratonvm_vm::types::Value;
use cratonvm_vm::vm::Vm;

const CLASS: &str = "cratonvm/CodeCacheSweepPhases";
const METHODS: u64 = 600;
const PHASES: u64 = 4;
const PER_PHASE: u64 = METHODS / PHASES;
const REPS: i32 = 2000;

const OVERRIDES: &[(&str, Option<&str>)] = &[
    ("CRATONVM_JIT_CODE_CACHE_MAX_MB", Some("1")),
    ("CRATONVM_JIT_CODE_CACHE_SWEEP", Some("1")),
    ("CRATONVM_JIT_ENTRY_COUNTER", Some("1")),
];

fn test_resources_dir() -> String {
    if let Some(generated) = option_env!("CRATONVM_TEST_CLASSES_DIR") {
        if std::path::Path::new(generated).is_dir() {
            return generated.to_owned();
        }
    }
    format!("{}/tests/resources", env!("CARGO_MANIFEST_DIR"))
}

fn class_files_available() -> bool {
    std::path::Path::new(&format!(
        "{}/cratonvm/CodeCacheSweepPhases.class",
        test_resources_dir()
    ))
    .exists()
}

/// `m{i}` in Java, in Rust: the oracle. Long arithmetic wraps, `(k ^ i)` is an
/// int widened to long, and `>>>` is a logical shift.
fn m(i: u64, x: i64) -> i64 {
    let mut s = x;
    for k in 0..8i64 {
        s = s
            .wrapping_mul(31 + (i % 97) as i64)
            .wrapping_add(k ^ i as i64);
        if s & (i % 13 + 1) as i64 == 0 {
            s = s.wrapping_add(i as i64);
        }
        s ^= ((s as u64) >> (i % 17 + 1)) as i64;
    }
    s
}

/// `phase{p}(reps)` in Rust.
fn phase(p: u64, reps: i32) -> i64 {
    let mut c: i64 = 0;
    for r in 0..reps {
        for i in p * PER_PHASE..(p + 1) * PER_PHASE {
            c = c.wrapping_add(m(i, (r as i64).wrapping_add(c)));
        }
    }
    c
}

#[test]
fn the_sweeper_recovers_a_code_cache_full_of_dead_phases() {
    if !class_files_available() {
        eprintln!("skipping: CodeCacheSweepPhases.class not built");
        return;
    }
    cratonvm_types::flags::with_process_overrides(OVERRIDES, body);
}

fn body() {
    let mut vm = Vm::new(VmConfig::new().with_classpath(vec![test_resources_dir()]));

    // Two rounds: the second needs round one's bodies again after they were
    // swept, which is the recompile-after-withdrawal path.
    for round in 0..2 {
        for p in 0..PHASES {
            let name = format!("phase{p}");
            let got = vm.invoke(CLASS, &name, "(I)J", &[Value::Int(REPS)]);
            let want = phase(p, REPS);
            match got {
                Ok(Some(Value::Long(v))) => assert_eq!(
                    v, want,
                    "round {round} {name}: a sweep, a demotion or a recompile changed an answer"
                ),
                other => panic!("round {round} {name}: expected a long, got {other:?}"),
            }
        }
    }

    let manager = &vm.shared.jit.tiered_manager;
    assert!(
        manager.cap_refusals() > 0,
        "the 1 MiB cap was never hit, so nothing below says anything about the \
         sweeper. The fixture must fill the cache during phase 0"
    );

    let stats = cratonvm_jit::jit_code_reclamation_stats();
    assert!(
        stats.reclaimed_bytes > 0,
        "no byte of withdrawn code came back to the OS: withdrawn {} bodies / {} bytes, \
         {} still queued. A dispatch cache still owning withdrawn bodies looks like this",
        stats.withdrawn_bodies,
        stats.withdrawn_bytes,
        stats.queued_owners,
    );

    let class_id = vm
        .shared
        .classes
        .class_manager
        .read()
        .get_loaded_class_id(CLASS)
        .expect("the fixture class is loaded");
    let cache = vm.shared.jit.jit_cache.read();
    let last = PHASES - 1;
    let compiled = (last * PER_PHASE..METHODS)
        .filter(|i| {
            cache
                .get(CLASS, &format!("m{i}"), "(J)J", class_id)
                .is_some()
        })
        .count();
    assert!(
        compiled > 0,
        "none of phase {last}'s {PER_PHASE} methods has a compiled body. They went hot \
         after the cap was hit, so they can compile only into room a sweep freed -- \
         and none did. Sweeps: {}",
        cache.code_cache_sweeps(),
    );
}
