// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Craton Software Company

//! Differential & correctness tests for the interpreter intrinsic table.
//!
//! Feature: `feature_roadmap_interpreter_intrinsic_table.md`
//! Contract: `intrinsic_table_contract.md`
//!
//! ## What this verifies
//!
//! A parallel team is adding an interpreter fast path that dispatches hot JDK
//! methods (`Object.getClass/hashCode`, `String.length/charAt/isEmpty`,
//! `System.arraycopy`, `StringBuilder.*`, `Integer/Long` box/unbox/parse,
//! `Math.*`) directly from the inline cache, bypassing the native registry.
//!
//! The whole correctness argument is: **the intrinsic fast path must be
//! byte-for-byte behavior-identical to the normal native dispatch path.**
//! The implementation provides a kill-switch env var
//! `CRATONVM_DISABLE_INTRINSICS=1` that suppresses intrinsic-table population
//! so calls fall through to the normal path. These tests run the *same* Java
//! program with the switch ON and OFF and assert identical observable output.
//!
//! ## How the VM is launched (so the orchestrator can verify)
//!
//! The kill-switch is read once per process (an `OnceLock` in
//! `vm/src/runtime/env_cache.rs`), so an in-process `Vm::new` cannot test both
//! modes in one test binary. We therefore launch the **`cratonvm` CLI binary
//! as a subprocess**, exactly like `vm/tests/cluster_c_constructor.rs` and
//! `vm/tests/cluster_a_aqs_chm.rs` do:
//!
//! ```text
//!   <cratonvm-bin>  -c  <vm/tests/resources>  cratonvm.IntrinsicDiff
//! ```
//!
//! with `stdout`/`stderr` piped and the env var set (or unset) for that one
//! child process. The classpath `vm/tests/resources/` points at committed
//! fixture classes. New classes generated by `vm/build.rs` are staged under
//! `CRATONVM_TEST_CLASSES_DIR` instead of being written back to this tree.
//!
//! Binary resolution order (see `cratonvm_binary`):
//!   1. `CRATONVM_BIN` env var, if it points to an existing file.
//!   2. `target/release/cratonvm[.exe]`
//!   3. `target/debug/cratonvm[.exe]`
//!
//! ## Assumptions / notes
//!
//! - These tests are gated: if `javac` did not compile the Java sources, or
//!   the `cratonvm` binary has not been built, the test prints a skip notice
//!   and returns (it does not fail). This matches every other subprocess test
//!   in `vm/tests/`.
//! - The intrinsic hit counter (`intrinsic_hit_count()` in
//!   `interpreter.rs`, per the contract) is process-internal and **not**
//!   surfaced through the CLI, so a black-box subprocess test cannot read it.
//!   Per the task spec we therefore rely on the behavioral differential only.
//!   If the CLI later grows a `--XX:PrintIntrinsicHits` style flag, a
//!   hit-count assertion can be layered on here.
//! - Until the parallel intrinsic implementation lands AND the workspace is
//!   rebuilt, the behavior is identical on/off trivially (intrinsics simply do
//!   not exist yet) — these tests still pass, and become meaningful once the
//!   fast path is wired in.
//!
//! Run with:
//!     cargo test -p cratonvm-vm --test intrinsic_diff -- --nocapture

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

/// Hard per-subprocess timeout. The differential program is short; a hang
/// here means an inline-cache livelock (the megamorphic-degradation bug the
/// roadmap calls out as a risk).
const RUN_TIMEOUT: Duration = Duration::from_secs(120);

// ---------------------------------------------------------------------------
// Path / binary resolution
// ---------------------------------------------------------------------------

/// Workspace root (parent of the `vm` crate).
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("CARGO_MANIFEST_DIR has no parent")
        .to_path_buf()
}

/// The committed fixture classpath directory: `vm/tests/resources/`.
/// `vm/build.rs` stages freshly compiled classes under
/// `CRATONVM_TEST_CLASSES_DIR`; this test still uses committed fixtures.
fn classpath_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("resources")
}

/// Resolve the `cratonvm` CLI binary. Mirrors the helper used by the other
/// subprocess tests (`cluster_c_constructor.rs` etc.).
mod common;

/// Prerequisite gate: the lookup below is unchanged — only a MISSING binary is
/// reported differently. See `common::require_binary`.
fn cratonvm_binary() -> Option<PathBuf> {
    common::require_binary(cratonvm_binary_lookup())
}

fn cratonvm_binary_lookup() -> Option<PathBuf> {
    if let Ok(bin) = std::env::var("CRATONVM_BIN") {
        let p = PathBuf::from(&bin);
        if p.exists() {
            return Some(p);
        }
    }
    let target = workspace_root().join("target");
    let exe = if cfg!(windows) {
        "cratonvm.exe"
    } else {
        "cratonvm"
    };
    for profile in &["release", "debug"] {
        let candidate = target.join(profile).join(exe);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    None
}

/// True if the compiled `.class` for `cratonvm/<simple_name>` exists.
fn class_file_present(simple_name: &str) -> bool {
    classpath_dir()
        .join("cratonvm")
        .join(format!("{simple_name}.class"))
        .exists()
}

// ---------------------------------------------------------------------------
// Subprocess runner
// ---------------------------------------------------------------------------

/// Outcome of one subprocess run of a Java class on the cratonvm CLI.
#[derive(Debug, Clone)]
struct Run {
    stdout: String,
    stderr: String,
    exit_code: Option<i32>,
}

/// Run `cratonvm -c <classpath> cratonvm.<class_simple_name>` as a child
/// process. `disable_intrinsics` selects whether `CRATONVM_DISABLE_INTRINSICS`
/// is set to `1` (the kill-switch) or explicitly removed for that child.
///
/// Returns `Some(Run)` on a clean spawn+wait, or `None` if a prerequisite is
/// missing (binary not built / class not compiled) so callers can skip.
fn run_class(class_simple_name: &str, disable_intrinsics: bool) -> Option<Run> {
    if !class_file_present(class_simple_name) {
        eprintln!(
            "[intrinsic_diff] {class_simple_name}.class not found under \
             {} — javac unavailable at build time? skipping.",
            classpath_dir().display()
        );
        return None;
    }
    let bin = match cratonvm_binary() {
        Some(b) => b,
        None => {
            eprintln!(
                "[intrinsic_diff] cratonvm binary not found; build it with \
                 `cargo build -p cratonvm-cli` (or set CRATONVM_BIN). skipping."
            );
            return None;
        }
    };

    let mut cmd = Command::new(&bin);
    cmd.arg("-c")
        .arg(classpath_dir())
        .arg(format!("cratonvm.{class_simple_name}"))
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    // The differential off-switch. We set OR clear the var explicitly so the
    // child's environment is deterministic regardless of what the test
    // harness inherited.
    if disable_intrinsics {
        cmd.env("CRATONVM_DISABLE_INTRINSICS", "1");
    } else {
        cmd.env_remove("CRATONVM_DISABLE_INTRINSICS");
    }

    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("[intrinsic_diff] failed to spawn cratonvm: {e}");
            return None;
        }
    };

    let start = Instant::now();
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) => {
                if start.elapsed() > RUN_TIMEOUT {
                    let _ = child.kill();
                    let _ = child.wait();
                    panic!(
                        "[intrinsic_diff] {class_simple_name} timed out after \
                         {RUN_TIMEOUT:?} (intrinsics_disabled={disable_intrinsics}) \
                         — likely an inline-cache livelock at a megamorphic site."
                    );
                }
                std::thread::sleep(Duration::from_millis(25));
            }
            Err(e) => {
                eprintln!("[intrinsic_diff] try_wait failed: {e}");
                return None;
            }
        }
    }

    let output = match child.wait_with_output() {
        Ok(o) => o,
        Err(e) => {
            eprintln!("[intrinsic_diff] wait_with_output failed: {e}");
            return None;
        }
    };

    Some(Run {
        stdout: normalize(&String::from_utf8_lossy(&output.stdout)),
        stderr: normalize(&String::from_utf8_lossy(&output.stderr)),
        exit_code: output.status.code(),
    })
}

/// Normalize line endings (CRLF -> LF) and strip a trailing newline so a
/// stray platform `\r` cannot masquerade as a behavioral divergence.
fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n").trim_end().to_string()
}

/// Extract the `r:` observation lines (the per-intrinsic results emitted by
/// `IntrinsicDiff.java`) from a stdout blob.
fn observation_lines(stdout: &str) -> Vec<&str> {
    stdout.lines().filter(|l| l.starts_with("r:")).collect()
}

/// Locate the first line on which two stdout blobs differ — used to localise
/// a divergence in the failure message.
fn first_diff(a: &str, b: &str) -> Option<(usize, String, String)> {
    let (la, lb): (Vec<&str>, Vec<&str>) = (a.lines().collect(), b.lines().collect());
    for i in 0..la.len().max(lb.len()) {
        let x = la.get(i).copied().unwrap_or("<missing>");
        let y = lb.get(i).copied().unwrap_or("<missing>");
        if x != y {
            return Some((i + 1, x.to_string(), y.to_string()));
        }
    }
    None
}

// ===========================================================================
// Test 1 — differential_on_vs_off
// ===========================================================================

/// Run `IntrinsicDiff` twice — intrinsics ON, then forced OFF via
/// `CRATONVM_DISABLE_INTRINSICS=1` — and assert byte-for-byte identical
/// stdout and identical exit code. This is the core acceptance criterion:
/// the intrinsic fast path must not change observable behavior for ANY of
/// the intrinsic methods over the edge-case input matrix in the Java program.
#[test]
fn differential_on_vs_off() {
    let on = match run_class("IntrinsicDiff", false) {
        Some(r) => r,
        None => return, // prerequisite missing; skip (see module docs)
    };
    let off = match run_class("IntrinsicDiff", true) {
        Some(r) => r,
        None => return,
    };

    // Sanity: the program must have actually completed (printed its marker).
    assert!(
        on.stdout.contains("INTRINSIC_DIFF_OK "),
        "intrinsics-ON run did not reach the INTRINSIC_DIFF_OK marker.\n\
         stdout:\n{}\nstderr:\n{}",
        on.stdout,
        on.stderr,
    );
    assert!(
        off.stdout.contains("INTRINSIC_DIFF_OK "),
        "intrinsics-OFF run did not reach the INTRINSIC_DIFF_OK marker.\n\
         stdout:\n{}\nstderr:\n{}",
        off.stdout,
        off.stderr,
    );

    // The decisive check: identical stdout.
    if on.stdout != off.stdout {
        let where_ = first_diff(&on.stdout, &off.stdout)
            .map(|(n, x, y)| format!("first divergence at line {n}:\n  ON : {x}\n  OFF: {y}"))
            .unwrap_or_else(|| "(divergence in line count / trailing content)".to_string());
        panic!(
            "INTRINSIC DIVERGENCE: stdout differs between intrinsics ON and OFF.\n\
             {where_}\n\
             The intrinsic fast path is NOT behavior-identical to native dispatch.\n\
             --- full ON stdout ---\n{}\n--- full OFF stdout ---\n{}",
            on.stdout, off.stdout,
        );
    }

    // Exit codes must also match.
    assert_eq!(
        on.exit_code, off.exit_code,
        "exit code diverged: ON={:?} OFF={:?}",
        on.exit_code, off.exit_code,
    );

    // A clean main() return must not yield a nonzero exit.
    assert!(
        matches!(on.exit_code, Some(0) | None),
        "IntrinsicDiff exited nonzero ({:?}) despite printing the OK marker.\n\
         stderr:\n{}",
        on.exit_code,
        on.stderr,
    );

    let obs = observation_lines(&on.stdout).len();
    assert!(
        obs >= 80,
        "expected the differential program to emit many 'r:' observation \
         lines (one per intrinsic case); got only {obs}. Did the program \
         abort early? stdout:\n{}",
        on.stdout,
    );

    eprintln!(
        "[intrinsic_diff] differential_on_vs_off: {obs} intrinsic observations \
         identical with intrinsics ON vs OFF; exit codes match ({:?}).",
        on.exit_code,
    );
}

// ===========================================================================
// Test 2 — virtual_dispatch_guard
// ===========================================================================

/// Virtual-dispatch soundness. `IntrinsicVirtualGuard` defines subclasses
/// that OVERRIDE `hashCode()` (and a `CharSequence` overriding `length()`).
/// The interpreter must guard the intrinsic on the resolved declaring class:
/// an overriding subclass must dispatch to the override, never to the
/// `Object.hashCode` / `String.length` intrinsic.
///
/// Run with intrinsics ON — that is the configuration in which the guard can
/// fail. The Java program self-checks and prints `VIRTUAL_GUARD_OK` only if
/// every overridden method returned its overridden value.
#[test]
fn virtual_dispatch_guard() {
    let run = match run_class("IntrinsicVirtualGuard", false) {
        Some(r) => r,
        None => return,
    };

    assert!(
        run.stdout.contains("VIRTUAL_GUARD_OK"),
        "virtual-dispatch guard FAILED: an overriding subclass hit the \
         intrinsic instead of its own override (intrinsic virtual-dispatch \
         unsoundness — roadmap §8).\nstdout:\n{}\nstderr:\n{}",
        run.stdout,
        run.stderr,
    );
    assert!(
        !run.stdout.contains("VIRTUAL_GUARD_FAIL") && !run.stdout.contains("FAIL:"),
        "virtual-dispatch guard reported an explicit failure line.\n\
         stdout:\n{}",
        run.stdout,
    );
    assert!(
        matches!(run.exit_code, Some(0) | None),
        "IntrinsicVirtualGuard exited nonzero: {:?}\nstderr:\n{}",
        run.exit_code,
        run.stderr,
    );

    // Cross-check: the guard must hold with intrinsics OFF too (trivially —
    // there is no fast path then — but this proves the program itself is
    // correct and the ON result is meaningful).
    if let Some(off) = run_class("IntrinsicVirtualGuard", true) {
        assert!(
            off.stdout.contains("VIRTUAL_GUARD_OK"),
            "IntrinsicVirtualGuard failed even with intrinsics OFF — the test \
             program itself is wrong.\nstdout:\n{}",
            off.stdout,
        );
        assert_eq!(
            normalize(&run.stdout),
            normalize(&off.stdout),
            "virtual-guard stdout diverged between intrinsics ON and OFF",
        );
    }

    eprintln!(
        "[intrinsic_diff] virtual_dispatch_guard: overriding subclasses \
         correctly bypass the intrinsic; identity-hash and String intrinsics \
         still apply to non-overriding receivers.",
    );
}

// ===========================================================================
// Test 3 — megamorphic_site
// ===========================================================================

/// Megamorphic inline-cache stress. `IntrinsicMegamorphic` hammers two call
/// sites (`cs.length()` and `o.hashCode()`) each of which observes many
/// distinct receiver classes — String/StringBuilder/custom `CharSequence`s,
/// and several `hashCode`-overriding classes. The IC must degrade cleanly
/// (no livelock) and produce correct results for every receiver.
///
/// A hang would be caught by `RUN_TIMEOUT`; correctness is self-checked by
/// the program (`MEGAMORPHIC_OK`). Run with intrinsics ON.
#[test]
fn megamorphic_site() {
    let run = match run_class("IntrinsicMegamorphic", false) {
        Some(r) => r,
        None => return,
    };

    assert!(
        run.stdout.contains("MEGAMORPHIC_OK"),
        "megamorphic call-site test FAILED — incorrect result or IC \
         degradation bug.\nstdout:\n{}\nstderr:\n{}",
        run.stdout,
        run.stderr,
    );
    assert!(
        !run.stdout.contains("MEGAMORPHIC_FAIL"),
        "megamorphic test reported MEGAMORPHIC_FAIL.\nstdout:\n{}",
        run.stdout,
    );
    assert!(
        matches!(run.exit_code, Some(0) | None),
        "IntrinsicMegamorphic exited nonzero: {:?}\nstderr:\n{}",
        run.exit_code,
        run.stderr,
    );

    // The deterministic sums must also be invariant across the kill-switch.
    if let Some(off) = run_class("IntrinsicMegamorphic", true) {
        let det = |s: &str| -> Vec<String> {
            s.lines()
                .filter(|l| l.starts_with("megamorphic.") && !l.contains("Consistent"))
                .map(|l| l.to_string())
                .collect()
        };
        assert_eq!(
            det(&run.stdout),
            det(&off.stdout),
            "megamorphic deterministic results diverged between intrinsics \
             ON and OFF",
        );
    }

    eprintln!(
        "[intrinsic_diff] megamorphic_site: both megamorphic call sites \
         produced correct results with no livelock.",
    );
}

// ===========================================================================
// Test 4 — arraycopy_exception_parity
// ===========================================================================

/// Exception parity for `System.arraycopy`. The three mandated failure modes
/// — `NullPointerException`, `ArrayStoreException`,
/// `ArrayIndexOutOfBoundsException` — must be thrown identically whether the
/// intrinsic fast path or the native path handles the call.
///
/// The `arraycopy` exception cases live inside `IntrinsicDiff.java` (folded
/// into the differential program, as the task spec permits). This test
/// re-runs that program on/off and asserts parity *specifically* on the
/// `r:arraycopy.*` observation lines, so an arraycopy-only regression is
/// reported with a focused message even though `differential_on_vs_off`
/// would also catch it.
#[test]
fn arraycopy_exception_parity() {
    let on = match run_class("IntrinsicDiff", false) {
        Some(r) => r,
        None => return,
    };
    let off = match run_class("IntrinsicDiff", true) {
        Some(r) => r,
        None => return,
    };

    let on_ac: Vec<&str> = observation_lines(&on.stdout)
        .into_iter()
        .filter(|l| l.starts_with("r:arraycopy."))
        .collect();
    let off_ac: Vec<&str> = observation_lines(&off.stdout)
        .into_iter()
        .filter(|l| l.starts_with("r:arraycopy."))
        .collect();

    assert!(
        !on_ac.is_empty(),
        "no r:arraycopy.* observations found — IntrinsicDiff did not reach \
         the arraycopy section.\nstdout:\n{}",
        on.stdout,
    );

    assert_eq!(
        on_ac, off_ac,
        "System.arraycopy behavior diverged between intrinsics ON and OFF.\n\
         ON : {on_ac:#?}\nOFF: {off_ac:#?}",
    );

    // The three exception kinds must each have been observed (proves the
    // edge cases ran, not just that they matched).
    let joined = on_ac.join("\n");
    for (label, marker) in [
        ("NullPointerException", "NPE"),
        ("ArrayStoreException", "ASE"),
        ("ArrayIndexOutOfBoundsException", "AIOOBE"),
    ] {
        assert!(
            joined.contains(marker),
            "expected at least one arraycopy {label} ('{marker}') observation; \
             arraycopy lines were:\n{joined}",
        );
        assert!(
            !joined.contains("NO-THROW"),
            "an arraycopy exception case did NOT throw — expected {label}.\n\
             arraycopy lines:\n{joined}",
        );
    }

    eprintln!(
        "[intrinsic_diff] arraycopy_exception_parity: NPE / ArrayStoreException \
         / ArrayIndexOutOfBoundsException thrown identically ON vs OFF \
         ({} arraycopy observations).",
        on_ac.len(),
    );
}

// ===========================================================================
// Test 5 — record_object_methods_differential
// ===========================================================================

/// Records (JEP 395). `IntrinsicRecordDiff` exercises the generated
/// `hashCode`/`equals` bodies over every component shape — primitives
/// (including `NaN` / signed zero), `String` (Latin-1 and UTF-16), enums,
/// nested records three levels deep, `null`s, arrays (identity semantics),
/// collections, boxed types, a component-less record, and a record that
/// hand-writes all three bodies — then drives 300 record keys through a
/// `HashMap` and a megamorphic `equals`/`hashCode` call site.
///
/// With intrinsics ON those calls take `InterpIntrinsic::RecordHashCode` /
/// `RecordEquals`; with `CRATONVM_DISABLE_INTRINSICS=1` they fall back to the
/// `invokedynamic ObjectMethods.bootstrap` call-site path. Both must produce
/// identical output — that is what makes installing the intrinsic safe.
///
/// The program never prints a raw `hashCode()`: the JLS leaves a record's hash
/// value unspecified. It prints the observable consequences instead (equal
/// objects hashing alike, `HashMap`/`HashSet` placement and lookup) plus
/// `equals`/`toString`, which the JLS does specify.
#[test]
fn record_object_methods_differential() {
    let on = match run_class("IntrinsicRecordDiff", false) {
        Some(r) => r,
        None => return, // prerequisite missing; skip (see module docs)
    };
    let off = match run_class("IntrinsicRecordDiff", true) {
        Some(r) => r,
        None => return,
    };

    for (label, run) in [("ON", &on), ("OFF", &off)] {
        assert!(
            run.stdout.contains("INTRINSIC_RECORD_DIFF_OK "),
            "intrinsics-{label} run did not reach the INTRINSIC_RECORD_DIFF_OK \
             marker.\nstdout:\n{}\nstderr:\n{}",
            run.stdout,
            run.stderr,
        );
    }

    if on.stdout != off.stdout {
        let where_ = first_diff(&on.stdout, &off.stdout)
            .map(|(n, x, y)| format!("first divergence at line {n}:\n  ON : {x}\n  OFF: {y}"))
            .unwrap_or_else(|| "(divergence in line count / trailing content)".to_string());
        panic!(
            "RECORD INTRINSIC DIVERGENCE: stdout differs between intrinsics ON \
             and OFF.\n{where_}\n\
             The record hashCode/equals intrinsic is NOT behavior-identical to \
             the invokedynamic ObjectMethods path.",
        );
    }

    assert_eq!(
        on.exit_code, off.exit_code,
        "exit code diverged: ON={:?} OFF={:?}",
        on.exit_code, off.exit_code,
    );
    assert!(
        matches!(on.exit_code, Some(0) | None),
        "IntrinsicRecordDiff exited nonzero ({:?}) despite printing the OK \
         marker.\nstderr:\n{}",
        on.exit_code,
        on.stderr,
    );

    // Spot-check the invariants that would break loudest if the intrinsic
    // mis-hashed or mis-compared, independent of the ON/OFF comparison above
    // (both paths share the Rust implementation, so a bug in it would agree
    // with itself).
    for expected in [
        // Equal records are equal, hash alike, and collapse to one bucket.
        "r: node.same.equals=true",
        "r: node.same.hashAgrees=true",
        "r: node.same.setSize=1",
        "r: node.same.mapGetX=second",
        // A one-component-deep difference three records down is detected.
        "r: node.deepDiff.equals=false",
        "r: node.deepDiff.setSize=2",
        // NaN equals NaN; +0.0 does not equal -0.0.
        "r: prim.nan.equals=true",
        "r: prim.signedZero.equals=false",
        // `Long.hashCode` folds the high word: 1L<<32 and 1L must not collide
        // into equality.
        "r: prim.longHighWord.equals=false",
        // Arrays keep identity semantics.
        "r: arr.sameInstances.equals=true",
        "r: arr.equalContent.equals=false",
        // A record must never equal an array of that record type.
        "r: arr.recordVsArray=false",
        "r: arr.arrayVsRecord=false",
        // Hand-written bodies are not diverted to the intrinsic.
        "r: custom.hashIs4242=true",
        "r: custom.equalsIgnoresB=true",
        "r: custom.equalsChecksA=false",
        "r: custom.toString=CUSTOM",
        // Every one of 300 record keys round-trips through a HashMap.
        "r: big.size=300",
        "r: big.hits=300",
        "r: big.misses=0",
        "r: big.absent=null",
        // toString stays on the invokedynamic path and keeps its format.
        "r: node.toString=Node[group=Group[table=employee, kind=INSERT, \
shape=Shape[table=employee, kind=INSERT, shapeHash=17], \
ops=[op-0, op-1, op-2, op-3, op-4, op-5, op-6, op-7], pre=true, ordinal=3], \
stableId=42]",
        "r: null.toString=Nullable[s=null, o=null]",
        "r: empty.toString=Empty[]",
    ] {
        assert!(
            on.stdout.contains(expected),
            "missing expected record observation: {expected:?}\nstdout:\n{}",
            on.stdout,
        );
    }

    let obs = observation_lines(&on.stdout).len();
    assert!(
        obs >= 300,
        "expected the record differential program to emit many 'r:' \
         observation lines; got only {obs}. stdout:\n{}",
        on.stdout,
    );

    eprintln!(
        "[intrinsic_diff] record_object_methods_differential: {obs} record \
         observations identical with intrinsics ON vs OFF; exit codes match \
         ({:?}).",
        on.exit_code,
    );
}
