// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Craton Software Company

//! Differential test catching synthetic-overlay stubs that diverge from real
//! JDK bytecode.
//!
//! ## What this verifies
//!
//! CratonVM ships hand-written native ("synthetic") implementations for a set
//! of hot `java.util` / `java.lang` methods. Some of those stubs have
//! historically returned values that DIVERGE from what the real JDK bytecode
//! produces (e.g. `Collections.disjoint` returning wrong booleans,
//! `Collectors.toMap` dropping a merged value, `String.format("%s", boxed)`
//! returning `null`). See `SyntheticDiff.java` for the exact case matrix.
//!
//! The correctness argument mirrors `intrinsic_diff.rs`: run the **same** Java
//! program two ways and assert byte-for-byte identical observable output. The
//! two runs toggle the env var `CRATONVM_REAL`:
//!   * the **synthetic** run sets NOTHING (the default overlay path);
//!   * the **real** run sets `CRATONVM_REAL=all`, forcing the VM to execute the
//!     real JDK bytecode instead of the synthetic native stub.
//!
//! `CRATONVM_REAL=all` is implemented by a sibling change in
//! `vm/src/runtime/env_cache.rs` + `vm_exec.rs`; this test only sets the env
//! var. If the sequence of `r:` observation lines differs between the two
//! runs, a synthetic stub returned a different value than real bytecode — the
//! failure message reports the first divergent case and both values.
//!
//! ## How the VM is launched (so the orchestrator can verify)
//!
//! `CRATONVM_REAL` is read once per process (an `OnceLock`-style cache in
//! `env_cache.rs`), so an in-process `Vm::new` cannot test both modes in one
//! test binary. We therefore launch the **`cratonvm` CLI binary as a
//! subprocess**, exactly like `intrinsic_diff.rs`:
//!
//! ```text
//!   <cratonvm-bin>  -c  <vm/tests/resources>  cratonvm.SyntheticDiff
//! ```
//!
//! with `stdout`/`stderr` piped and `CRATONVM_REAL` set (or removed) for that
//! one child process. The classpath `vm/tests/resources/` points at committed
//! fixture classes. New classes generated by `vm/build.rs` are staged under
//! `CRATONVM_TEST_CLASSES_DIR` instead of being written back to this tree.
//!
//! Binary resolution order (see `cratonvm_binary`):
//!   1. `CRATONVM_BIN` env var, if it points to an existing file.
//!   2. `target/release/cratonvm[.exe]`
//!   3. `target/debug/cratonvm[.exe]`
//!
//! ## Skip / gate behavior (mirrors intrinsic_diff.rs EXACTLY)
//!
//! If `javac` did not compile the Java sources, or the `cratonvm` binary has
//! not been built, the test prints a skip notice and returns (it does NOT
//! fail). This matches `intrinsic_diff.rs` and every other subprocess test in
//! `vm/tests/`, so CI without a JDK does not fail spuriously.
//!
//! Run with:
//!     cargo test -p cratonvm-vm --test synthetic_diff -- --nocapture

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

/// Hard per-subprocess timeout. The differential program is short.
const RUN_TIMEOUT: Duration = Duration::from_secs(120);

// ---------------------------------------------------------------------------
// Path / binary resolution  (copied + adapted from intrinsic_diff.rs)
// ---------------------------------------------------------------------------

/// Workspace root (parent of the `vm` crate).
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("CARGO_MANIFEST_DIR has no parent")
        .to_path_buf()
}

/// The committed fixture classpath directory: `vm/tests/resources/`.
/// `vm/build.rs` stages freshly compiled classes under
/// `CRATONVM_TEST_CLASSES_DIR`; this test still uses committed fixtures.
fn classpath_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("resources")
}

/// Resolve the `cratonvm` CLI binary. Mirrors the helper used by the other
/// subprocess tests.
mod common;

/// Prerequisite gate: the lookup below is unchanged — only a MISSING binary is
/// reported differently. See `common::require_binary`.
fn cratonvm_binary() -> Option<PathBuf> {
    common::require_binary(cratonvm_binary_lookup())
}

fn cratonvm_binary_lookup() -> Option<PathBuf> {
    if let Ok(bin) = std::env::var("CRATONVM_BIN") {
        let p = PathBuf::from(&bin);
        if p.exists() {
            return Some(p);
        }
    }
    let target = workspace_root().join("target");
    let exe = if cfg!(windows) {
        "cratonvm.exe"
    } else {
        "cratonvm"
    };
    for profile in &["release", "debug"] {
        let candidate = target.join(profile).join(exe);
        if candidate.exists() {
            return Some(candidate);
        }
    }
    None
}

/// True if the compiled `.class` for `cratonvm/<simple_name>` exists.
fn class_file_present(simple_name: &str) -> bool {
    classpath_dir()
        .join("cratonvm")
        .join(format!("{simple_name}.class"))
        .exists()
}

// ---------------------------------------------------------------------------
// Subprocess runner
// ---------------------------------------------------------------------------

/// Outcome of one subprocess run of a Java class on the cratonvm CLI.
#[derive(Debug, Clone)]
struct Run {
    stdout: String,
    stderr: String,
    exit_code: Option<i32>,
}

/// Run `cratonvm -c <classpath> cratonvm.<class_simple_name>` as a child
/// process. `real` selects whether `CRATONVM_REAL` is set to `all` (force real
/// JDK bytecode) or explicitly removed for that child (the synthetic overlay).
///
/// Returns `Some(Run)` on a clean spawn+wait, or `None` if a prerequisite is
/// missing (binary not built / class not compiled) so callers can skip.
fn run_class(class_simple_name: &str, real: bool) -> Option<Run> {
    if !class_file_present(class_simple_name) {
        eprintln!(
            "[synthetic_diff] {class_simple_name}.class not found under \
             {} — javac unavailable at build time? skipping.",
            classpath_dir().display()
        );
        return None;
    }
    let bin = match cratonvm_binary() {
        Some(b) => b,
        None => {
            eprintln!(
                "[synthetic_diff] cratonvm binary not found; build it with \
                 `cargo build -p cratonvm-cli` (or set CRATONVM_BIN). skipping."
            );
            return None;
        }
    };

    let mut cmd = Command::new(&bin);
    cmd.arg("-c")
        .arg(classpath_dir())
        .arg(format!("cratonvm.{class_simple_name}"))
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    // The differential switch. The synthetic run clears CRATONVM_REAL; the
    // real run sets `CRATONVM_REAL=all`. We set OR clear the var explicitly so
    // the child's environment is deterministic regardless of what the test
    // harness inherited. The `=all` switch itself is implemented in the VM
    // (env_cache.rs + vm_exec.rs) by a sibling change — we only toggle it.
    if real {
        cmd.env("CRATONVM_REAL", "all");
    } else {
        cmd.env_remove("CRATONVM_REAL");
    }

    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("[synthetic_diff] failed to spawn cratonvm: {e}");
            return None;
        }
    };

    let start = Instant::now();
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) => {
                if start.elapsed() > RUN_TIMEOUT {
                    let _ = child.kill();
                    let _ = child.wait();
                    panic!(
                        "[synthetic_diff] {class_simple_name} timed out after \
                         {RUN_TIMEOUT:?} (real={real})."
                    );
                }
                std::thread::sleep(Duration::from_millis(25));
            }
            Err(e) => {
                eprintln!("[synthetic_diff] try_wait failed: {e}");
                return None;
            }
        }
    }

    let output = match child.wait_with_output() {
        Ok(o) => o,
        Err(e) => {
            eprintln!("[synthetic_diff] wait_with_output failed: {e}");
            return None;
        }
    };

    Some(Run {
        stdout: normalize(&String::from_utf8_lossy(&output.stdout)),
        stderr: normalize(&String::from_utf8_lossy(&output.stderr)),
        exit_code: output.status.code(),
    })
}

/// Normalize line endings (CRLF -> LF) and strip a trailing newline so a
/// stray platform `\r` cannot masquerade as a behavioral divergence.
fn normalize(s: &str) -> String {
    s.replace("\r\n", "\n").trim_end().to_string()
}

/// Extract the `r:` observation lines (the per-method results emitted by
/// `SyntheticDiff.java`) from a stdout blob.
fn observation_lines(stdout: &str) -> Vec<&str> {
    stdout.lines().filter(|l| l.starts_with("r:")).collect()
}

/// Locate the first `r:` observation line on which two runs differ — used to
/// localise (and name) a synthetic-vs-real divergence in the failure message.
fn first_observation_diff(syn: &str, real: &str) -> Option<(usize, String, String)> {
    let a = observation_lines(syn);
    let b = observation_lines(real);
    for i in 0..a.len().max(b.len()) {
        let x = a.get(i).copied().unwrap_or("<missing>");
        let y = b.get(i).copied().unwrap_or("<missing>");
        if x != y {
            return Some((i + 1, x.to_string(), y.to_string()));
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Generic env-var runner for per-subsystem real-path smoke tests
// ---------------------------------------------------------------------------

/// Run `cratonvm -c <classpath> cratonvm.<class_simple_name>` with an
/// explicit set of env-var overrides.  All CRATONVM_REAL* vars inherited
/// from the test harness are cleared first so each test has a clean baseline.
///
/// Returns `Some(Run)` on a successful spawn, or `None` when a prerequisite
/// is missing (binary not built / class not compiled) so callers can skip.
fn run_class_env(class_simple_name: &str, env_vars: &[(&str, &str)]) -> Option<Run> {
    if !class_file_present(class_simple_name) {
        eprintln!(
            "[synthetic_diff] {class_simple_name}.class not found — \
             javac unavailable at build time? skipping."
        );
        return None;
    }
    let bin = match cratonvm_binary() {
        Some(b) => b,
        None => {
            eprintln!(
                "[synthetic_diff] cratonvm binary not found; \
                 build with `cargo build -p cratonvm-cli`. skipping."
            );
            return None;
        }
    };

    let mut cmd = Command::new(&bin);
    cmd.arg("-c")
        .arg(classpath_dir())
        .arg(format!("cratonvm.{class_simple_name}"))
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    // Clear every CRATONVM_REAL* var that the test runner may have inherited
    // so the child starts from a known baseline.
    for var in &[
        "CRATONVM_REAL",
        "CRATONVM_REAL_ANNOTATIONS",
        "CRATONVM_REAL_AQS",
        "CRATONVM_REAL_RAF",
        "CRATONVM_REAL_NET_SOCKETS",
        "CRATONVM_REAL_FORKJOINPOOL",
        "CRATONVM_SYNTHETIC_AQS",
        "CRATONVM_SYNTHETIC_RAF",
        "CRATONVM_SYNTHETIC_NET_SOCKETS",
        "CRATONVM_SYNTHETIC_FORKJOINPOOL",
    ] {
        cmd.env_remove(var);
    }
    // Apply the caller's per-subsystem overrides.
    for (k, v) in env_vars {
        cmd.env(k, v);
    }

    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("[synthetic_diff] failed to spawn cratonvm: {e}");
            return None;
        }
    };

    let start = Instant::now();
    loop {
        match child.try_wait() {
            Ok(Some(_)) => break,
            Ok(None) => {
                if start.elapsed() > RUN_TIMEOUT {
                    let _ = child.kill();
                    let _ = child.wait();
                    panic!(
                        "[synthetic_diff] {class_simple_name} timed out after \
                         {RUN_TIMEOUT:?}."
                    );
                }
                std::thread::sleep(Duration::from_millis(25));
            }
            Err(e) => {
                eprintln!("[synthetic_diff] try_wait failed: {e}");
                return None;
            }
        }
    }

    let output = match child.wait_with_output() {
        Ok(o) => o,
        Err(e) => {
            eprintln!("[synthetic_diff] wait_with_output failed: {e}");
            return None;
        }
    };

    Some(Run {
        stdout: normalize(&String::from_utf8_lossy(&output.stdout)),
        stderr: normalize(&String::from_utf8_lossy(&output.stderr)),
        exit_code: output.status.code(),
    })
}

// ===========================================================================
// Test — synthetic_vs_real
// ===========================================================================

/// Run `SyntheticDiff` twice — synthetic overlay (CRATONVM_REAL unset), then
/// real JDK bytecode (CRATONVM_REAL=all) — and assert that:
///   (a) both runs reach the `SYNTHETIC_DIFF_OK` marker;
///   (b) the sequence of `r:` observation lines is identical between them
///       (a mismatch means a synthetic stub returned a different value than
///       the real method — the first divergent case and both values are
///       reported);
///   (c) the exit codes match.
#[test]
fn synthetic_vs_real() {
    let syn = match run_class("SyntheticDiff", false) {
        Some(r) => r,
        None => return, // prerequisite missing; skip (see module docs)
    };
    let real = match run_class("SyntheticDiff", true) {
        Some(r) => r,
        None => return,
    };

    // (a) Both runs must have completed (printed their marker).
    assert!(
        syn.stdout.contains("SYNTHETIC_DIFF_OK "),
        "synthetic run did not reach the SYNTHETIC_DIFF_OK marker.\n\
         stdout:\n{}\nstderr:\n{}",
        syn.stdout,
        syn.stderr,
    );
    assert!(
        real.stdout.contains("SYNTHETIC_DIFF_OK "),
        "real (CRATONVM_REAL=all) run did not reach the SYNTHETIC_DIFF_OK \
         marker.\nstdout:\n{}\nstderr:\n{}",
        real.stdout,
        real.stderr,
    );

    // (b) The decisive check: identical sequence of r: observation lines.
    let syn_obs = observation_lines(&syn.stdout);
    let real_obs = observation_lines(&real.stdout);
    if syn_obs != real_obs {
        let where_ = first_observation_diff(&syn.stdout, &real.stdout)
            .map(|(n, x, y)| {
                format!(
                    "first divergent case at r: line {n}:\n  \
                     SYNTHETIC: {x}\n  REAL     : {y}"
                )
            })
            .unwrap_or_else(|| "(divergence in observation-line count)".to_string());
        panic!(
            "SYNTHETIC DIVERGENCE: a synthetic stub returned a different value \
             than real JDK bytecode.\n{where_}\n\
             --- full SYNTHETIC stdout ---\n{}\n--- full REAL stdout ---\n{}",
            syn.stdout, real.stdout,
        );
    }

    // (c) Exit codes must match.
    assert_eq!(
        syn.exit_code, real.exit_code,
        "exit code diverged: SYNTHETIC={:?} REAL={:?}",
        syn.exit_code, real.exit_code,
    );

    // A clean main() return must not yield a nonzero exit.
    assert!(
        matches!(syn.exit_code, Some(0) | None),
        "SyntheticDiff exited nonzero ({:?}) despite printing the OK marker.\n\
         stderr:\n{}",
        syn.exit_code,
        syn.stderr,
    );

    // Sanity: the program must have emitted a meaningful number of cases.
    assert!(
        syn_obs.len() >= 20,
        "expected the differential program to emit many 'r:' observation \
         lines (one per case); got only {}. Did the program abort early? \
         stdout:\n{}",
        syn_obs.len(),
        syn.stdout,
    );

    eprintln!(
        "[synthetic_diff] synthetic_vs_real: {} observations identical between \
         the synthetic overlay and real JDK bytecode; exit codes match ({:?}).",
        syn_obs.len(),
        syn.exit_code,
    );
}

// ===========================================================================
// Per-subsystem real-path smoke tests (Phase 1 CI coverage)
//
// Each test sets the relevant CRATONVM_REAL_* flag and asserts the program
// runs to completion (OK marker present, exit code 0, key r: lines correct).
// All tests skip gracefully when the binary or class file is absent.
// ===========================================================================

/// Smoke test: annotation dispatch routes to real JDK bytecode under
/// CRATONVM_REAL_ANNOTATIONS=1.  Exercises getAnnotation / annotationType /
/// attribute reads on a @Retention(RUNTIME) annotation.
#[test]
fn real_annotations_path() {
    let run = match run_class_env("RealAnnotations", &[]) {
        Some(r) => r,
        None => return,
    };
    assert!(
        run.stdout.contains("REAL_ANNOTATIONS_OK"),
        "RealAnnotations did not reach the OK marker (exit={:?}).\n\
         stdout:\n{}\nstderr:\n{}",
        run.exit_code,
        run.stdout,
        run.stderr,
    );
    assert_eq!(
        run.exit_code,
        Some(0),
        "RealAnnotations exited nonzero.\nstderr:\n{}",
        run.stderr,
    );
    assert!(
        run.stdout.contains("r:present=true"),
        "annotation not found on class"
    );
    assert!(
        run.stdout.contains("r:value=world"),
        "annotation value() attribute wrong"
    );
    assert!(
        run.stdout.contains("r:retention=RUNTIME"),
        "@Retention not readable on the annotation type"
    );
}

/// Smoke test: AQS, ReentrantLock, and ReentrantReadWriteLock route to real
/// JDK bytecode under CRATONVM_REAL_AQS=1. Acquires a lock on the main thread,
/// observes it from a second thread, releases it, and creates a WriteLock
/// condition through the real lock view.
#[test]
fn real_aqs_path() {
    let run = match run_class_env("RealAqs", &[]) {
        Some(r) => r,
        None => return,
    };
    assert!(
        run.stdout.contains("REAL_AQS_OK"),
        "RealAqs did not reach the OK marker (exit={:?}).\n\
         stdout:\n{}\nstderr:\n{}",
        run.exit_code,
        run.stdout,
        run.stderr,
    );
    assert_eq!(
        run.exit_code,
        Some(0),
        "RealAqs exited nonzero.\nstderr:\n{}",
        run.stderr,
    );
    assert!(
        run.stdout.contains("r:lock_seen_held=true"),
        "background thread did not observe the lock as held"
    );
    assert!(
        run.stdout.contains("r:now_unlocked=true"),
        "lock still appears locked after unlock"
    );
    assert!(
        run.stdout.contains("r:rw_write_condition=true"),
        "real WriteLock.newCondition() did not produce a Condition"
    );
}

/// Smoke test: RandomAccessFile routes to real JDK bytecode under
/// CRATONVM_REAL_RAF=1.  Writes an int + long, seeks back, reads them, and
/// verifies the values.
#[test]
fn real_raf_path() {
    let run = match run_class_env("RealRaf", &[]) {
        Some(r) => r,
        None => return,
    };
    assert!(
        run.stdout.contains("REAL_RAF_OK"),
        "RealRaf did not reach the OK marker (exit={:?}).\n\
         stdout:\n{}\nstderr:\n{}",
        run.exit_code,
        run.stdout,
        run.stderr,
    );
    assert_eq!(
        run.exit_code,
        Some(0),
        "RealRaf exited nonzero.\nstderr:\n{}",
        run.stderr,
    );
    assert!(
        run.stdout.contains("r:magic=deadbeef"),
        "int value read back wrong (expected deadbeef)"
    );
    assert!(
        run.stdout.contains("r:value=123456789"),
        "long value read back wrong"
    );
}

/// Smoke test: ForkJoinPool routes to real JDK bytecode under
/// CRATONVM_REAL_FORKJOINPOOL=1.  Submits two trivial callables to the
/// common pool and verifies the results.
#[test]
fn real_fjp_path() {
    let run = match run_class_env("RealFjp", &[]) {
        Some(r) => r,
        None => return,
    };
    assert!(
        run.stdout.contains("REAL_FJP_OK"),
        "RealFjp did not reach the OK marker (exit={:?}).\n\
         stdout:\n{}\nstderr:\n{}",
        run.exit_code,
        run.stdout,
        run.stderr,
    );
    assert_eq!(
        run.exit_code,
        Some(0),
        "RealFjp exited nonzero.\nstderr:\n{}",
        run.stderr,
    );
    assert!(
        run.stdout.contains("r:result=42"),
        "ForkJoinPool task returned wrong value (expected 42)"
    );
    assert!(
        run.stdout.contains("r:sum=123"),
        "second FJP task returned wrong value (expected 123)"
    );

    // --- bulk submission (the hibernate CDI-cluster regression) ---------
    //
    // `invokeAll(Collection)` was missing from the real-FJP bridge
    // allow-list, so it fell through to real JDK bytecode against the
    // under-initialized `commonPool()` object and threw
    // RejectedExecutionException at submissionQueue(). Every assertion below
    // is PAIRED — size AND sum AND "the callables actually ran" AND "the
    // futures report done" — because a bridge that silently dropped the work
    // would pass a bare "it returned a list of the right length".
    assert!(
        run.stdout.contains("r:invokeAllSize=4"),
        "invokeAll returned the wrong number of futures.\nstdout:\n{}\nstderr:\n{}",
        run.stdout,
        run.stderr,
    );
    assert!(
        run.stdout.contains("r:invokeAllSum=10"),
        "invokeAll futures carried the wrong results (expected 1+2+3+4)"
    );
    assert!(
        run.stdout.contains("r:invokeAllRan=4"),
        "invokeAll did not actually RUN every callable — a list of futures \
         with no work done behind them is the failure this guards"
    );
    assert!(
        run.stdout.contains("r:invokeAllDone=true"),
        "invokeAll returned before every task completed"
    );
    assert!(
        run.stdout.contains("r:ifaceInvokeAllSize=4"),
        "invokeAll failed through an ExecutorService-typed receiver — the \
         invokeinterface shape Weld's ConcurrentBeanDeployer actually uses"
    );
    // Weld's `AbstractExecutorServices.checkForExceptions` calls
    // `Future.get()` on each result and rethrows the ExecutionException's
    // cause; a swallowed failure would silently report a half-built
    // container as a successful CDI deployment.
    assert!(
        run.stdout
            .contains("r:invokeAllFailure=IllegalStateException"),
        "a throwing callable did not surface as ExecutionException(cause) \
         from Future.get().\nstdout:\n{}",
        run.stdout,
    );
    assert!(
        run.stdout.contains("r:invokeAllOkSibling=7"),
        "one failing callable disturbed its sibling's result — invokeAll must \
         complete the whole batch and report failures per-future"
    );
    assert!(
        run.stdout.contains("r:invokeAnyInRange=true"),
        "invokeAny returned a value outside the submitted set (it returned \
         null before the fix — a silent wrong answer, not an exception)"
    );
}

/// Smoke test: socket layer routes to real JDK bytecode under
/// CRATONVM_REAL_NET_SOCKETS=1.  Opens a loopback ServerSocket, connects a
/// client from the same JVM, sends a byte, and verifies the exchange.
#[test]
fn real_net_sockets_path() {
    let run = match run_class_env("RealNetSockets", &[]) {
        Some(r) => r,
        None => return,
    };
    assert!(
        run.stdout.contains("REAL_NET_SOCKETS_OK"),
        "RealNetSockets did not reach the OK marker (exit={:?}).\n\
         stdout:\n{}\nstderr:\n{}",
        run.exit_code,
        run.stdout,
        run.stderr,
    );
    assert_eq!(
        run.exit_code,
        Some(0),
        "RealNetSockets exited nonzero.\nstderr:\n{}",
        run.stderr,
    );
    assert!(
        run.stdout.contains("r:received=42"),
        "loopback byte not received correctly (expected 0x42)"
    );
}
