#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-2026 Craton Software Company
"""Generate the per-JDK JDK-only blocker artifacts, and ratchet them in CI.

    target/jdk-only-audit/jdk-<feature>-missing-natives.json
    target/jdk-only-audit/jdk-<feature>-synthetic-dependencies.json

`jdk-only-audit.md` section 6 requires these two files per supported JDK
image, because no static source review can produce an exhaustive missing-method
list across JDK versions: native surfaces and class-library internals vary by
image, so the list is *generated per image* and is only valid for that image.

Consumes the runtime dumps written by `cratonvm` (see `--help` and the README
next to this file for the exact flags):

    --dump-native-registry          native census, schema_version 2
    --dump-missing-natives          flat unresolved-native log
    --dump-missing-natives-grouped  the same, grouped by JDK module
    --dump-class-origins            class-origin census, schema_version 1
    --jdk-only-report               violations + counters, schema_version 1

Design constraints, all of them load-bearing:

* **Deterministic.** Stable sort order everywhere, no timestamps, no absolute
  paths, LF newlines, ASCII-escaped JSON. Two runs over the same dumps produce
  byte-identical files, so the outputs can be committed as ratchet baselines
  and diffed across hosts.
* **Partial, never fabricated.** A missing or malformed input dump yields a
  partial result carrying an explicit note and `"partial": true`, never a
  silent zero. `--check` fails on a partial result unless `--allow-partial` is
  passed, because "the dump was not produced" must never read as "nothing is
  broken".
* **Allowed generation is not a blocker.** `vm-array`, `hidden-class`,
  `generated-lambda`, `generated-proxy` and `reflection-accessor` classes are
  legitimate (contract section 1 item 6) and are reported in a separate
  `allowed` section. Only `compatibility-stub` origins are blockers. Getting
  that distinction wrong is what makes an origin census useless.
* **`synthetic-stub` is a classification request, not a verdict.** The native
  kind is *ambient*: it comes from `NativeMethodRegistry::set_category` /
  `with_category`, not from a `register()` argument, and it defaults to
  `SyntheticStub`. A `register()` call outside a `with_category(...)` block is
  a stub by omission. Some `synthetic-stub` rows are therefore genuinely
  mis-tagged permanent bridges. Those entries carry
  `"requires_classification": true` and point at
  `docs/jdk-only-native-review.md`; this tool never asserts they are defects.

Exit codes:

    0  success
    1  ratchet failure -- the open blocker set grew against the baseline
    2  usage / configuration error (bad arguments, bad status ledger,
       undeterminable JDK feature version, missing baseline in --check)
    3  partial result where a complete one was required
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys

SCHEMA_VERSION = 1

# ---------------------------------------------------------------------------
# Closure vocabulary
# ---------------------------------------------------------------------------

# An entry is *closed* only when it is implemented as a reviewed bridge,
# implemented as a reviewed intrinsic, executed from real bytecode, implemented
# as legitimate generated class bytes, or explicitly declared out of scope with
# a specification-consistent error. Anything else is open. There is no
# "wontfix", no "deferred" and no "probably fine": those all spell `open`.
STATUS_OPEN = 'open'
STATUS_VOCABULARY = (
    'open',            # not closed
    'bridge',          # reviewed NativeKind::Bridge
    'intrinsic',       # reviewed NativeKind::Intrinsic
    'real-bytecode',   # executed from real class bytes; the native is gone
    'generated-class',  # legitimate generated bytes (lambda/proxy/accessor)
    'out-of-scope',    # declared out of scope, spec-consistent error raised
)
CLOSED_STATUSES = frozenset(STATUS_VOCABULARY) - {STATUS_OPEN}

NATIVE_REVIEW_DOC = 'docs/jdk-only-native-review.md'
CONTRACT_DOC = 'docs/feature-designs/jdk-only-mode.md'

# Class origins that are *allowed* under `--jdk-only` (contract section 1 item
# 6 / section 5 rubric). These are reported separately and are never blockers.
ALLOWED_GENERATED_ORIGINS = (
    'vm-array',
    'hidden-class',
    'generated-lambda',
    'generated-proxy',
    'reflection-accessor',
)
# Origins backed by real class bytes. Neither blockers nor "generated".
REAL_BYTES_ORIGINS = ('boot-image', 'application-class-path', 'user-defined')
BLOCKER_ORIGIN = 'compatibility-stub'

# Entry categories.
CAT_UNRESOLVED = 'unresolved-native'
CAT_STUB_REGISTRATION = 'synthetic-stub-registration'
CAT_STUB_CLASS = 'compatibility-stub-class'
CAT_CLASS_REFUSED = 'compatibility-class-refused'


# ---------------------------------------------------------------------------
# JDK module classification
# ---------------------------------------------------------------------------

# Mirror of `classify_jdk_module` in `vm/src/vm/vm_init.rs`, used only when the
# grouped dump (which already carries the VM's own answer) is unavailable. To
# avoid the two tables drifting apart, the real table is *parsed out of the
# Rust source* when it can be found; this literal is the fallback and the note
# emitted alongside it says so.
_FALLBACK_MODULE_PREFIXES = (
    ('java/net/http/', 'java.net.http'),
    ('jdk/internal/net/http/', 'java.net.http'),
    ('java/sql/', 'java.sql'),
    ('javax/sql/', 'java.sql'),
    ('java/rmi/', 'java.rmi'),
    ('javax/management/', 'java.management'),
    ('java/lang/management/', 'java.management'),
    ('javax/naming/', 'java.naming'),
    ('javax/xml/', 'java.xml'),
    ('org/w3c/dom/', 'java.xml'),
    ('org/xml/sax/', 'java.xml'),
    ('javax/crypto/', 'java.base'),
    ('javax/security/', 'java.base'),
    ('javax/net/ssl/', 'java.base'),
    ('javax/net/', 'java.base'),
    ('java/util/logging/', 'java.logging'),
    ('java/util/prefs/', 'java.prefs'),
    ('java/lang/instrument/', 'java.instrument'),
    ('jdk/jfr/', 'jdk.jfr'),
    ('jdk/management/jfr/', 'jdk.management.jfr'),
    ('com/sun/management/', 'jdk.management'),
    ('jdk/management/', 'jdk.management'),
    ('jdk/jdi/', 'jdk.jdi'),
    ('com/sun/jdi/', 'jdk.jdi'),
    ('jdk/jshell/', 'jdk.jshell'),
    ('jdk/compiler/', 'jdk.compiler'),
    ('javax/tools/', 'java.compiler'),
    ('jdk/javadoc/', 'jdk.javadoc'),
    ('jdk/unsupported/', 'jdk.unsupported'),
    ('sun/misc/', 'jdk.unsupported'),
    ('java/lang/', 'java.base'),
    ('java/util/', 'java.base'),
    ('java/io/', 'java.base'),
    ('java/nio/', 'java.base'),
    ('java/net/', 'java.base'),
    ('java/security/', 'java.base'),
    ('java/math/', 'java.base'),
    ('java/text/', 'java.base'),
    ('java/time/', 'java.base'),
    ('jdk/internal/', 'java.base'),
    ('sun/nio/', 'java.base'),
    ('sun/security/', 'java.base'),
    ('sun/util/', 'java.base'),
)

_MODULE_TABLE_RE = re.compile(
    r'const\s+PREFIX_TO_MODULE\s*:\s*&\[\(&str,\s*&str\)\]\s*=\s*&\[(.*?)\n\s*\];',
    re.DOTALL,
)
_MODULE_ROW_RE = re.compile(r'\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)')


class ModuleClassifier:
    """Longest-prefix-first class-name -> JDK module name mapping."""

    def __init__(self, prefixes, source):
        self.prefixes = tuple(prefixes)
        self.source = source

    @classmethod
    def load(cls, repo_root):
        """Parse the table out of `vm/src/vm/vm_init.rs`, else fall back."""
        path = os.path.join(repo_root, 'vm', 'src', 'vm', 'vm_init.rs')
        try:
            with open(path, encoding='utf-8', errors='replace') as fh:
                text = fh.read()
        except OSError:
            return cls(_FALLBACK_MODULE_PREFIXES, 'fallback-table')
        match = _MODULE_TABLE_RE.search(text)
        if not match:
            return cls(_FALLBACK_MODULE_PREFIXES, 'fallback-table')
        rows = _MODULE_ROW_RE.findall(match.group(1))
        if not rows:
            return cls(_FALLBACK_MODULE_PREFIXES, 'fallback-table')
        return cls(rows, 'vm/src/vm/vm_init.rs')

    def classify(self, class_name):
        for prefix, module in self.prefixes:
            if class_name.startswith(prefix):
                return module
        return 'other'


# ---------------------------------------------------------------------------
# Input loading
# ---------------------------------------------------------------------------

class Inputs:
    """Loaded dumps plus a per-role state string, and the note trail."""

    # Roles are reported verbatim in the `inputs` object of both artifacts.
    STATE_NOT_PROVIDED = 'not-provided'
    STATE_PRESENT = 'present'
    STATE_MISSING = 'missing'
    STATE_MALFORMED = 'malformed'

    def __init__(self):
        self.data = {}
        self.state = {}
        self.notes = []
        self.partial = False

    def load(self, role, path, required_for, degrade_when_absent=True):
        """Load one dump. `required_for` names what degrades without it.

        `degrade_when_absent=False` marks the role as genuinely optional --
        used for the flat unresolved-native log, which carries no fact the
        grouped dump does not already carry.
        """
        if not path:
            self.state[role] = self.STATE_NOT_PROVIDED
            self.data[role] = None
            if degrade_when_absent:
                self.notes.append(
                    'input %s was not provided; %s is incomplete. Re-run '
                    'cratonvm with the corresponding --dump flag.'
                    % (role, required_for))
                self.partial = True
            return None
        if not os.path.isfile(path):
            self.state[role] = self.STATE_MISSING
            self.data[role] = None
            self.notes.append(
                'input %s was requested but the file does not exist; %s is '
                'incomplete. A missing dump is NOT evidence of a clean run.'
                % (role, required_for))
            self.partial = True
            return None
        try:
            with open(path, encoding='utf-8') as fh:
                data = json.load(fh)
        except (OSError, ValueError) as exc:
            self.state[role] = self.STATE_MALFORMED
            self.data[role] = None
            self.notes.append(
                'input %s could not be parsed (%s); %s is incomplete. A '
                'malformed dump is NOT evidence of a clean run.'
                % (role, type(exc).__name__, required_for))
            self.partial = True
            return None
        if not isinstance(data, dict):
            self.state[role] = self.STATE_MALFORMED
            self.data[role] = None
            self.notes.append(
                'input %s parsed but is not a JSON object; %s is incomplete.'
                % (role, required_for))
            self.partial = True
            return None
        self.state[role] = self.STATE_PRESENT
        self.data[role] = data
        return data

    def note(self, text):
        self.notes.append(text)

    def degrade(self, text):
        self.notes.append(text)
        self.partial = True


def _rows(container, key):
    """A list-valued field, or [] plus a flag saying the shape was wrong."""
    value = container.get(key) if isinstance(container, dict) else None
    if isinstance(value, list):
        return [r for r in value if isinstance(r, dict)], True
    return [], value is None


# ---------------------------------------------------------------------------
# Status ledger
# ---------------------------------------------------------------------------

class StatusLedger:
    """Operator-maintained closure records, keyed by native triple / class.

    Nothing in a runtime dump can say "this was reviewed and closed" -- closure
    is a human judgement. The ledger is where that judgement is recorded and
    reviewed; the generator only joins it onto the machine-observed rows.
    """

    def __init__(self):
        self.natives = {}
        self.classes = {}
        self.used = set()
        self.source = None

    @classmethod
    def load(cls, path, errors):
        ledger = cls()
        if not path:
            return ledger
        if not os.path.isfile(path):
            # An absent ledger is normal: it means nothing has been closed yet.
            return ledger
        ledger.source = os.path.basename(path)
        try:
            with open(path, encoding='utf-8') as fh:
                data = json.load(fh)
        except (OSError, ValueError) as exc:
            errors.append('status ledger %s could not be parsed: %s: %s'
                          % (path, type(exc).__name__, exc))
            return ledger
        if not isinstance(data, dict):
            errors.append('status ledger %s is not a JSON object' % path)
            return ledger
        for row in data.get('natives') or []:
            if not isinstance(row, dict):
                errors.append('status ledger: natives[] entry is not an object')
                continue
            key = (str(row.get('class', '')), str(row.get('name', '')),
                   str(row.get('descriptor', '')))
            if not all(key):
                errors.append('status ledger: natives[] entry needs class, '
                              'name and descriptor (got %r)' % (key,))
                continue
            status = row.get('status', STATUS_OPEN)
            if status not in STATUS_VOCABULARY:
                errors.append(
                    'status ledger: %s.%s%s has status %r, which is not in the '
                    'closure vocabulary %s' % (key[0], key[1], key[2], status,
                                               list(STATUS_VOCABULARY)))
                continue
            ledger.natives[key] = (status, row.get('note'))
        for row in data.get('classes') or []:
            if not isinstance(row, dict):
                errors.append('status ledger: classes[] entry is not an object')
                continue
            name = str(row.get('name', ''))
            if not name:
                errors.append('status ledger: classes[] entry needs a name')
                continue
            status = row.get('status', STATUS_OPEN)
            if status not in STATUS_VOCABULARY:
                errors.append(
                    'status ledger: class %s has status %r, which is not in '
                    'the closure vocabulary %s'
                    % (name, status, list(STATUS_VOCABULARY)))
                continue
            ledger.classes[name] = (status, row.get('note'))
        return ledger

    def for_native(self, class_name, name, descriptor):
        key = (class_name, name, descriptor)
        hit = self.natives.get(key)
        if hit is None:
            return STATUS_OPEN, None
        self.used.add(('native',) + key)
        return hit

    def for_class(self, name):
        hit = self.classes.get(name)
        if hit is None:
            return STATUS_OPEN, None
        self.used.add(('class', name))
        return hit

    def stale(self):
        """Ledger rows that matched nothing this run, sorted."""
        out = []
        for key in self.natives:
            if ('native',) + key not in self.used:
                out.append('native %s.%s%s' % key)
        for name in self.classes:
            if ('class', name) not in self.used:
                out.append('class %s' % name)
        return sorted(out)


# ---------------------------------------------------------------------------
# missing-natives artifact
# ---------------------------------------------------------------------------

def _native_key(entry):
    """Ratchet identity of a native blocker.

    Deliberately excludes `invocations`: an uninvoked stub is still a stub, so
    a newly appearing entry with `invocations: 0` must fail the ratchet exactly
    like an invoked one.
    """
    return (entry['category'], entry['class'], entry['name'],
            entry['descriptor'])


def _merge(entries, entry):
    key = _native_key(entry)
    existing = entries.get(key)
    if existing is None:
        entries[key] = entry
        return
    for source in entry['sources']:
        if source not in existing['sources']:
            existing['sources'].append(source)
    for field in ('module', 'sample_call_site', 'registered_by', 'overwrote',
                  'real_declaring_method', 'kind'):
        if existing.get(field) in (None, '') and entry.get(field) not in (None, ''):
            existing[field] = entry[field]
    if entry['invocations_known']:
        if existing['invocations_known']:
            existing['invocations'] = max(existing['invocations'],
                                          entry['invocations'])
        else:
            existing['invocations'] = entry['invocations']
            existing['invocations_known'] = True
    existing['requires_classification'] = (
        existing['requires_classification'] or entry['requires_classification'])


def build_missing_natives(inputs, ledger, classifier, jdk_feature):
    entries = {}

    # (a) Unresolved natives grouped by module -- the VM's own module answer,
    #     which is why this source is preferred over the flat log.
    grouped = inputs.data.get('missing-natives-grouped')
    if grouped is not None:
        modules = grouped.get('modules')
        if not isinstance(modules, dict):
            inputs.degrade('missing-natives-grouped has no "modules" object; '
                           'unresolved natives from that dump were skipped')
            modules = {}
        for module, rows in sorted(modules.items()):
            if not isinstance(rows, list):
                inputs.degrade('missing-natives-grouped module %r is not a '
                               'list; skipped' % module)
                continue
            for row in rows:
                if not isinstance(row, dict):
                    continue
                _merge(entries, _unresolved_entry(
                    row.get('class'), row.get('name'), row.get('descriptor'),
                    module, row.get('sample_call_site'),
                    'missing-natives-grouped'))

    # (b) Flat unresolved-native log. Same facts, no module column, so the
    #     module is derived locally.
    flat = inputs.data.get('missing-natives')
    if flat is not None:
        rows, ok = _rows(flat, 'missing_natives')
        if not ok:
            inputs.degrade('missing-natives has no "missing_natives" array; '
                           'that dump contributed nothing')
        for row in rows:
            class_name = row.get('class')
            _merge(entries, _unresolved_entry(
                class_name, row.get('name'), row.get('descriptor'),
                classifier.classify(class_name) if class_name else None,
                row.get('sample_call_site'), 'missing-natives'))

    # (c) `missing-native` / `missing-implementation` violations from the
    #     strict report. These are the dispatch-time refusals, which the
    #     missing-native log does not necessarily carry.
    report = inputs.data.get('jdk-only-report')
    if report is not None:
        rows, ok = _rows(report, 'violations')
        if not ok:
            inputs.degrade('jdk-only-report has no "violations" array')
        for row in rows:
            kind = row.get('kind')
            if kind not in ('missing-native', 'missing-implementation'):
                continue
            class_name = row.get('class')
            module = row.get('module')
            if not module and class_name:
                module = classifier.classify(class_name)
            _merge(entries, _unresolved_entry(
                class_name, row.get('method'), row.get('descriptor'), module,
                None, 'jdk-only-report:' + str(kind)))

    # (d) Every registration still classified `synthetic-stub`. Not asserted to
    #     be a defect: the kind is ambient and defaults to SyntheticStub, so
    #     some of these are mis-tagged permanent bridges. They are emitted with
    #     `requires_classification` and a pointer at the review checklist.
    registry_totals = None
    registry = inputs.data.get('native-registry')
    if registry is not None:
        counts = registry.get('counts')
        if isinstance(counts, dict):
            registry_totals = {k: counts[k] for k in sorted(counts)}
        rows, ok = _rows(registry, 'natives')
        if not ok:
            inputs.degrade('native-registry has no "natives" array; '
                           'synthetic-stub registrations were not enumerated')
        for row in rows:
            if row.get('kind') != 'synthetic-stub':
                continue
            class_name = row.get('class')
            invocations = row.get('invocations')
            _merge(entries, {
                'class': str(class_name or ''),
                'name': str(row.get('name') or ''),
                'descriptor': str(row.get('descriptor') or ''),
                'category': CAT_STUB_REGISTRATION,
                'module': classifier.classify(class_name) if class_name else None,
                'kind': 'synthetic-stub',
                'invocations': int(invocations) if isinstance(invocations, int) else 0,
                'invocations_known': isinstance(invocations, int),
                'registered_by': row.get('registered_by'),
                'overwrote': row.get('overwrote'),
                'real_declaring_method': row.get('real_declaring_method'),
                'sample_call_site': None,
                'sources': ['native-registry'],
                # The whole point: this row is a request for a human
                # classification decision, not an assertion of a defect.
                'requires_classification': True,
                'status': STATUS_OPEN,
                'status_note': None,
            })

    # Join the operator ledger on, then finalise ordering.
    final = []
    for key in sorted(entries):
        entry = entries[key]
        status, note = ledger.for_native(entry['class'], entry['name'],
                                         entry['descriptor'])
        entry['status'] = status
        entry['status_note'] = note
        entry['sources'] = sorted(entry['sources'])
        if entry['requires_classification']:
            entry['classification_reference'] = NATIVE_REVIEW_DOC
        final.append(_ordered_native(entry))

    counts = {
        'total': len(final),
        'open': sum(1 for e in final if e['status'] == STATUS_OPEN),
        'closed': sum(1 for e in final if e['status'] != STATUS_OPEN),
        'requires_classification': sum(
            1 for e in final if e['requires_classification']),
        'never_invoked': sum(
            1 for e in final if e['invocations_known'] and e['invocations'] == 0),
        'invocations_unknown': sum(
            1 for e in final if not e['invocations_known']),
        'by_category': _tally(final, 'category'),
        'by_status': _tally(final, 'status'),
        'by_module': _tally(final, 'module'),
    }

    return {
        'schema_version': SCHEMA_VERSION,
        'artifact': 'jdk-only-missing-natives',
        'jdk_feature': jdk_feature,
        'partial': inputs.partial,
        'inputs': {k: inputs.state[k] for k in sorted(inputs.state)},
        'module_table_source': classifier.source,
        'status_vocabulary': list(STATUS_VOCABULARY),
        'classification_reference': NATIVE_REVIEW_DOC,
        'contract_reference': CONTRACT_DOC,
        'notes': list(inputs.notes),
        'registry_totals': registry_totals,
        'counts': counts,
        'entries': final,
    }


def _unresolved_entry(class_name, name, descriptor, module, call_site, source):
    return {
        'class': str(class_name or ''),
        'name': str(name or ''),
        'descriptor': str(descriptor or ''),
        'category': CAT_UNRESOLVED,
        'module': module,
        'kind': None,
        # The unresolved log records the first call site and dedupes; it does
        # not carry a count. Saying 0 here would be a fabrication, so the
        # count is explicitly marked unknown.
        'invocations': 0,
        'invocations_known': False,
        'registered_by': None,
        'overwrote': None,
        'real_declaring_method': None,
        'sample_call_site': call_site,
        'sources': [source],
        'requires_classification': False,
        'status': STATUS_OPEN,
        'status_note': None,
    }


_NATIVE_FIELD_ORDER = (
    'class', 'name', 'descriptor', 'category', 'module', 'kind',
    'invocations', 'invocations_known', 'registered_by', 'overwrote',
    'real_declaring_method', 'sample_call_site', 'sources',
    'requires_classification', 'classification_reference', 'status',
    'status_note',
)


def _ordered_native(entry):
    out = {}
    for field in _NATIVE_FIELD_ORDER:
        if field in entry:
            out[field] = entry[field]
    return out


def _tally(entries, field):
    counts = {}
    for entry in entries:
        key = entry.get(field)
        key = 'unknown' if key is None else str(key)
        counts[key] = counts.get(key, 0) + 1
    return {k: counts[k] for k in sorted(counts)}


# ---------------------------------------------------------------------------
# synthetic-dependencies artifact
# ---------------------------------------------------------------------------

def _class_key(entry):
    return (entry['category'], entry['name'])


def build_synthetic_dependencies(inputs, ledger, jdk_feature):
    blockers = {}
    allowed = {}
    origin_counts = {}
    unknown_origins = set()

    origins = inputs.data.get('class-origins')
    if origins is not None:
        rows, ok = _rows(origins, 'classes')
        if not ok:
            inputs.degrade('class-origins has no "classes" array; the '
                           'compatibility-stub inventory is empty for the '
                           'wrong reason')
        for row in rows:
            origin = str(row.get('origin') or 'unknown')
            origin_counts[origin] = origin_counts.get(origin, 0) + 1
            name = str(row.get('name') or '')
            loader_id = row.get('loader_id')
            if origin == BLOCKER_ORIGIN:
                key = (CAT_STUB_CLASS, name)
                entry = blockers.get(key)
                if entry is None:
                    entry = {
                        'name': name,
                        'category': CAT_STUB_CLASS,
                        'origin': origin,
                        'reason': row.get('reason'),
                        'real_bytes_found': bool(row.get('real_bytes_found')),
                        'requested_by': row.get('requested_by'),
                        'loader_ids': [],
                        'occurrences': 0,
                        'sources': ['class-origins'],
                        'status': STATUS_OPEN,
                        'status_note': None,
                    }
                    blockers[key] = entry
                entry['occurrences'] += 1
                if isinstance(loader_id, int) and loader_id not in entry['loader_ids']:
                    entry['loader_ids'].append(loader_id)
                if entry['reason'] in (None, '') and row.get('reason'):
                    entry['reason'] = row.get('reason')
                if entry['requested_by'] in (None, '') and row.get('requested_by'):
                    entry['requested_by'] = row.get('requested_by')
                # `real_bytes_found` on ANY row is the interesting fact: it
                # means the image does have the bytes and the fabrication is
                # gratuitous.
                entry['real_bytes_found'] = (
                    entry['real_bytes_found'] or bool(row.get('real_bytes_found')))
            elif origin in ALLOWED_GENERATED_ORIGINS:
                bucket = allowed.setdefault(origin, {'classes': set(),
                                                     'count': 0})
                bucket['count'] += 1
                bucket['classes'].add(name)
            elif origin in REAL_BYTES_ORIGINS or origin == 'vm-internal':
                pass
            else:
                unknown_origins.add(origin)

    # Classes strict mode REFUSED to fabricate never reach the class census --
    # they were never defined. They are blockers all the same, and are the only
    # evidence of them a `--jdk-only` run leaves behind.
    report = inputs.data.get('jdk-only-report')
    if report is not None:
        rows, ok = _rows(report, 'violations')
        if not ok and inputs.state.get('jdk-only-report') == Inputs.STATE_PRESENT:
            inputs.degrade('jdk-only-report has no "violations" array; '
                           'refused compatibility classes were not enumerated')
        for row in rows:
            if row.get('kind') != 'compatibility-class-requested':
                continue
            name = str(row.get('class') or '')
            key = (CAT_CLASS_REFUSED, name)
            entry = blockers.get(key)
            if entry is None:
                entry = {
                    'name': name,
                    'category': CAT_CLASS_REFUSED,
                    'origin': BLOCKER_ORIGIN,
                    'reason': row.get('reason'),
                    'real_bytes_found': False,
                    'requested_by': row.get('requester'),
                    'loader_ids': [],
                    'occurrences': 0,
                    'sources': ['jdk-only-report'],
                    'status': STATUS_OPEN,
                    'status_note': None,
                }
                blockers[key] = entry
            entry['occurrences'] += 1

    if unknown_origins:
        # An origin tag this tool has never heard of must not be silently
        # treated as allowed. Name it and degrade the result.
        inputs.degrade(
            'class-origins contains origin tag(s) %s that this tool does not '
            'classify; they were counted but placed in neither the blocker nor '
            'the allowed set. Update ALLOWED_GENERATED_ORIGINS / '
            'REAL_BYTES_ORIGINS in tools/jdk-only-blockers/blockers.py.'
            % ', '.join(sorted(unknown_origins)))

    final_blockers = []
    for key in sorted(blockers):
        entry = blockers[key]
        status, note = ledger.for_class(entry['name'])
        entry['status'] = status
        entry['status_note'] = note
        entry['loader_ids'] = sorted(entry['loader_ids'])
        entry['sources'] = sorted(entry['sources'])
        final_blockers.append(_ordered_class(entry))

    final_allowed = []
    for origin in sorted(allowed):
        bucket = allowed[origin]
        final_allowed.append({
            'origin': origin,
            'disposition': 'allowed',
            'count': bucket['count'],
            'classes': sorted(bucket['classes']),
        })

    counts = {
        'blockers_total': len(final_blockers),
        'blockers_open': sum(1 for e in final_blockers
                             if e['status'] == STATUS_OPEN),
        'blockers_closed': sum(1 for e in final_blockers
                               if e['status'] != STATUS_OPEN),
        'allowed_generated_total': sum(b['count'] for b in final_allowed),
        'by_category': _tally(final_blockers, 'category'),
        'by_status': _tally(final_blockers, 'status'),
        'by_origin': {k: origin_counts[k] for k in sorted(origin_counts)},
    }

    return {
        'schema_version': SCHEMA_VERSION,
        'artifact': 'jdk-only-synthetic-dependencies',
        'jdk_feature': jdk_feature,
        'partial': inputs.partial,
        'inputs': {k: inputs.state[k] for k in sorted(inputs.state)},
        'status_vocabulary': list(STATUS_VOCABULARY),
        'allowed_generated_origins': list(ALLOWED_GENERATED_ORIGINS),
        'blocker_origin': BLOCKER_ORIGIN,
        'contract_reference': CONTRACT_DOC,
        'notes': list(inputs.notes),
        'counts': counts,
        'blockers': final_blockers,
        'allowed': final_allowed,
    }


_CLASS_FIELD_ORDER = (
    'name', 'category', 'origin', 'reason', 'real_bytes_found',
    'requested_by', 'loader_ids', 'occurrences', 'sources', 'status',
    'status_note',
)


def _ordered_class(entry):
    return {f: entry[f] for f in _CLASS_FIELD_ORDER if f in entry}


# ---------------------------------------------------------------------------
# Ratchet
# ---------------------------------------------------------------------------

def open_native_keys(doc):
    return {
        '%s|%s.%s%s' % (e.get('category'), e.get('class'), e.get('name'),
                        e.get('descriptor'))
        for e in doc.get('entries') or []
        if e.get('status', STATUS_OPEN) == STATUS_OPEN
    }


def open_class_keys(doc):
    return {
        '%s|%s' % (e.get('category'), e.get('name'))
        for e in doc.get('blockers') or []
        if e.get('status', STATUS_OPEN) == STATUS_OPEN
    }


def compare(current, baseline, extractor):
    """Return (added, removed) open-key lists, sorted.

    Growth is measured on the open-key *set*, which contains no invocation
    count: a brand-new stub with `invocations: 0` adds a key and therefore
    fails the ratchet exactly like an invoked one. An entry that regresses from
    a closed status back to `open` also adds a key, which is the intent.
    """
    now = extractor(current)
    before = extractor(baseline)
    return sorted(now - before), sorted(before - now)


# ---------------------------------------------------------------------------
# IO
# ---------------------------------------------------------------------------

def write_json(path, doc):
    """Deterministic write: LF newlines, ASCII escapes, fixed key order."""
    text = json.dumps(doc, indent=2, ensure_ascii=True) + '\n'
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(text)


def read_json(path):
    with open(path, encoding='utf-8') as fh:
        return json.load(fh)


def artifact_names(feature):
    return ('jdk-%s-missing-natives.json' % feature,
            'jdk-%s-synthetic-dependencies.json' % feature)


# ---------------------------------------------------------------------------
# Feature-version resolution
# ---------------------------------------------------------------------------

def resolve_feature(explicit, inputs):
    if explicit is not None:
        return str(explicit), None
    report = inputs.data.get('jdk-only-report')
    if isinstance(report, dict):
        value = report.get('jdk_feature')
        if isinstance(value, int):
            return str(value), None
        if isinstance(value, str) and value.isdigit():
            return value, None
    return None, (
        'the JDK feature version could not be determined. These artifacts are '
        'only valid for one JDK image, so the version is part of the file name '
        'and cannot be guessed. Pass --jdk-feature N, or supply a '
        '--jdk-only-report dump whose "jdk_feature" is populated.')


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def build_parser():
    parser = argparse.ArgumentParser(
        prog='blockers.py',
        description='Generate (and ratchet) the per-JDK JDK-only blocker '
                    'artifacts from cratonvm runtime dumps.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='See tools/jdk-only-blockers/README.md.')
    parser.add_argument('--jdk-feature', metavar='N',
                        help='JDK feature version keying the output files. '
                             'Derived from --jdk-only-report when omitted.')
    parser.add_argument('--native-registry', metavar='FILE',
                        help='--dump-native-registry output (schema 2).')
    parser.add_argument('--missing-natives', metavar='FILE',
                        help='--dump-missing-natives output.')
    parser.add_argument('--missing-natives-grouped', metavar='FILE',
                        help='--dump-missing-natives-grouped output.')
    parser.add_argument('--class-origins', metavar='FILE',
                        help='--dump-class-origins output.')
    parser.add_argument('--jdk-only-report', metavar='FILE',
                        help='--jdk-only-report output (schema 1).')
    parser.add_argument('--out-dir', metavar='DIR',
                        default='target/jdk-only-audit',
                        help='where the two artifacts are written '
                             '(default: %(default)s).')
    parser.add_argument('--baseline-dir', metavar='DIR',
                        default='tools/jdk-only-blockers/baselines',
                        help='committed baselines (default: %(default)s).')
    parser.add_argument('--status-ledger', metavar='FILE',
                        default='tools/jdk-only-blockers/status-ledger.json',
                        help='operator closure records (default: %(default)s). '
                             'Absent means nothing has been closed yet.')
    parser.add_argument('--repo-root', metavar='DIR',
                        help='repository root, used to read the JDK module '
                             'table out of vm/src/vm/vm_init.rs. Defaults to '
                             'the checkout containing this script.')
    parser.add_argument('--check', action='store_true',
                        help='after generating, diff against the baseline and '
                             'exit non-zero if the open set grew.')
    parser.add_argument('--update-baseline', action='store_true',
                        help='copy the freshly generated artifacts into '
                             '--baseline-dir.')
    parser.add_argument('--allow-partial', action='store_true',
                        help='permit --check / --update-baseline on a partial '
                             'result. Off by default: a partial baseline bakes '
                             'in a false-clean ratchet.')
    parser.add_argument('--quiet', action='store_true',
                        help='suppress the human-readable summary.')
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    out = sys.stdout if not args.quiet else open(os.devnull, 'w')

    repo_root = args.repo_root or os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    ledger_errors = []
    ledger = StatusLedger.load(args.status_ledger, ledger_errors)
    if ledger_errors:
        for err in ledger_errors:
            print('error: %s' % err, file=sys.stderr)
        return 2

    inputs = Inputs()
    inputs.load('native-registry', args.native_registry,
                'the synthetic-stub registration inventory')
    grouped = inputs.load('missing-natives-grouped',
                          args.missing_natives_grouped,
                          'the module-attributed unresolved-native inventory')
    # The flat log is a strict subset of the grouped one (same rows, no module
    # column). Not passing it is only a gap when the grouped dump is also
    # absent -- otherwise demanding both would make every ordinary run partial.
    inputs.load('missing-natives', args.missing_natives,
                'the unresolved-native inventory',
                degrade_when_absent=grouped is None)
    inputs.load('class-origins', args.class_origins,
                'the compatibility-stub class inventory')
    inputs.load('jdk-only-report', args.jdk_only_report,
                'the dispatch-time refusal inventory')

    if all(state != Inputs.STATE_PRESENT for state in inputs.state.values()):
        print('error: no input dump could be read. Nothing was generated; an '
              'empty blocker file would falsely read as "nothing is broken".',
              file=sys.stderr)
        for note in inputs.notes:
            print('  note: %s' % note, file=sys.stderr)
        return 3

    feature, feature_error = resolve_feature(args.jdk_feature, inputs)
    if feature is None:
        print('error: %s' % feature_error, file=sys.stderr)
        return 2

    classifier = ModuleClassifier.load(repo_root)
    if classifier.source == 'fallback-table':
        inputs.note('the JDK module table could not be read from '
                    'vm/src/vm/vm_init.rs; the embedded fallback copy was used '
                    'and may have drifted.')

    natives_doc = build_missing_natives(inputs, ledger, classifier, feature)
    classes_doc = build_synthetic_dependencies(inputs, ledger, feature)
    # `build_*` may have appended notes / flipped `partial`; re-sync both docs
    # so the two artifacts always agree about the state of the run.
    for doc in (natives_doc, classes_doc):
        doc['partial'] = inputs.partial
        doc['notes'] = list(inputs.notes)

    stale = ledger.stale()
    all_notes = list(inputs.notes)
    if stale:
        all_notes.append(
            'status ledger row(s) matched nothing in this run: %s. Either the '
            'blocker is genuinely gone (drop the row) or this run did not '
            'exercise it (the ledger is not evidence on its own).'
            % ', '.join(stale))
        for doc in (natives_doc, classes_doc):
            doc['notes'] = list(all_notes)

    natives_name, classes_name = artifact_names(feature)
    natives_path = os.path.join(args.out_dir, natives_name)
    classes_path = os.path.join(args.out_dir, classes_name)
    write_json(natives_path, natives_doc)
    write_json(classes_path, classes_doc)

    print('jdk-only blockers  jdk=%s  %s' % (
        feature, 'PARTIAL' if inputs.partial else 'complete'), file=out)
    print('  wrote %s' % natives_path.replace(os.sep, '/'), file=out)
    print('  wrote %s' % classes_path.replace(os.sep, '/'), file=out)
    nc = natives_doc['counts']
    cc = classes_doc['counts']
    print('  missing natives : %d total, %d open, %d closed, %d awaiting '
          'classification' % (nc['total'], nc['open'], nc['closed'],
                              nc['requires_classification']), file=out)
    print('  synthetic deps  : %d blockers (%d open), %d allowed generated '
          'classes' % (cc['blockers_total'], cc['blockers_open'],
                       cc['allowed_generated_total']), file=out)
    for note in all_notes:
        print('  note: %s' % note, file=out)

    if inputs.partial:
        # Loud on stderr too: a partial run scrolling past in a CI log must not
        # be mistaken for a clean one.
        print('warning: PARTIAL result -- one or more input dumps were '
              'missing or malformed. The counts above are a floor, not a '
              'total.', file=sys.stderr)

    status = 0

    if args.update_baseline:
        if inputs.partial and not args.allow_partial:
            print('error: refusing to write a baseline from a partial result. '
                  'A partial baseline freezes a false-clean ratchet. Fix the '
                  'inputs, or pass --allow-partial deliberately.',
                  file=sys.stderr)
            return 3
        os.makedirs(args.baseline_dir, exist_ok=True)
        for name, doc in ((natives_name, natives_doc),
                          (classes_name, classes_doc)):
            path = os.path.join(args.baseline_dir, name)
            write_json(path, doc)
            print('  baseline updated: %s' % path.replace(os.sep, '/'),
                  file=out)

    if args.check:
        if inputs.partial and not args.allow_partial:
            print('error: refusing to ratchet a partial result -- a missing '
                  'input dump would read as a shrinking blocker set. Pass '
                  '--allow-partial only if you understand that.',
                  file=sys.stderr)
            return 3
        missing_baselines = [
            os.path.join(args.baseline_dir, n).replace(os.sep, '/')
            for n in (natives_name, classes_name)
            if not os.path.isfile(os.path.join(args.baseline_dir, n))]
        if missing_baselines:
            print('error: no committed baseline for JDK %s (%s). There is '
                  'nothing to ratchet against. Generate one with '
                  '--update-baseline and commit it.'
                  % (feature, ', '.join(missing_baselines)), file=sys.stderr)
            return 2
        for name, doc, extractor, label in (
                (natives_name, natives_doc, open_native_keys, 'missing native'),
                (classes_name, classes_doc, open_class_keys,
                 'synthetic dependency')):
            baseline_path = os.path.join(args.baseline_dir, name)
            try:
                baseline = read_json(baseline_path)
            except (OSError, ValueError) as exc:
                print('error: baseline %s could not be parsed: %s'
                      % (baseline_path.replace(os.sep, '/'), exc),
                      file=sys.stderr)
                return 2
            added, removed = compare(doc, baseline, extractor)
            if added:
                status = 1
                print('FAIL: %d new open %s blocker(s) vs the baseline:'
                      % (len(added), label), file=sys.stderr)
                for key in added:
                    print('  + %s' % key, file=sys.stderr)
            if removed:
                print('  %d %s blocker(s) closed since the baseline; refresh '
                      'it with --update-baseline:' % (len(removed), label),
                      file=out)
                for key in removed:
                    print('  - %s' % key, file=out)
            if not added and not removed:
                print('  %s ratchet: unchanged (%d open)'
                      % (label, len(extractor(doc))), file=out)
        if status == 0:
            print('  ratchet OK', file=out)
        else:
            print('error: the open blocker set grew. An entry that was never '
                  'invoked is still a blocker -- invocation counts are '
                  'deliberately not part of the ratchet key.', file=sys.stderr)

    return status


if __name__ == '__main__':
    sys.exit(main())
