[package]
name = "cratonvm-native-builtins-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Separately compiled cryptographic compatibility kernels for CratonVM"

[dependencies]
sha3 = "0.10"

[lints]
workspace = true
