[package]
name = "cratonvm-native-builtins-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Separately compiled cryptographic compatibility kernels for CratonVM"

[dependencies]
sha3 = "0.10"
rsa = "0.9"
sha1 = { version = "0.10", features = ["oid"] }
sha2 = { version = "0.10", features = ["oid"] }

[dev-dependencies]
cratonvm-native-api = { path = "../native-api" }

[lints]
workspace = true
