// JAVA21+
package cratonvm;

/**
 * Phase 84.1 & 84.2: Record runtime — canonical constructor, accessors,
 * equals, hashCode, toString.
 */
public class RecordRuntime {

    record Point(int x, int y) {}
    record Named(String name, int value) {}

    // 84.1: Canonical constructor — create record and read back components
    public static int testCanonicalCtor() {
        Point p = new Point(10, 20);
        return p.x() + p.y();  // 30
    }

    // 84.1: Compact constructor / accessor generation
    // Record accessor methods are auto-generated by javac
    public static int testAccessorGeneration() {
        Named n = new Named("hello", 42);
        return n.value();  // 42
    }

    // 84.2: equals — same components → true
    public static int testEqualsTrue() {
        Point a = new Point(3, 4);
        Point b = new Point(3, 4);
        return a.equals(b) ? 1 : 0;  // 1
    }

    // 84.2: equals — different components → false
    public static int testEqualsFalse() {
        Point a = new Point(3, 4);
        Point b = new Point(5, 6);
        return a.equals(b) ? 1 : 0;  // 0
    }

    // 84.2: equals — null → false
    public static int testEqualsNull() {
        Point a = new Point(1, 2);
        return a.equals(null) ? 1 : 0;  // 0
    }

    // 84.2: hashCode — same components produce same hash
    public static int testHashCodeConsistent() {
        Point a = new Point(7, 8);
        Point b = new Point(7, 8);
        return a.hashCode() == b.hashCode() ? 1 : 0;  // 1
    }

    // 84.2: hashCode — different components likely produce different hash
    public static int testHashCodeDifferent() {
        Point a = new Point(1, 2);
        Point b = new Point(3, 4);
        // Not guaranteed but extremely likely different
        return a.hashCode() != b.hashCode() ? 1 : 0;  // 1
    }

    // 84.2: toString — produces RecordName[field1=val1, field2=val2]
    public static int testToString() {
        Point p = new Point(5, 10);
        String s = p.toString();
        // Should be "Point[x=5, y=10]"
        return s.equals("Point[x=5, y=10]") ? 1 : 0;  // 1
    }
}
