#!/usr/bin/env python3
"""Emit probes/FrameShape.java with balanced deep expressions."""
import sys

NL = 48   # extra locals
NS = 32   # operand-stack depth


def nest(terms):
    """t0+(t1+(t2+...))  — nesting depth == len(terms)-1, so max_stack ~= len."""
    out = terms[-1]
    for t in reversed(terms[:-1]):
        out = f"{t} + ({out})"
    return out


def wrap(expr, indent, width=88):
    words, line, lines = expr.split(' '), indent, []
    for w in words:
        if len(line) + len(w) + 1 > width:
            lines.append(line)
            line = indent + '    ' + w
        else:
            line = (line + ' ' + w) if line.strip() else line + w
    lines.append(line)
    return '\n'.join(lines)


decls = []
for row in range(0, NL, 10):
    names = [f"l{i}=a" for i in range(row, min(row + 10, NL))]
    decls.append('            int ' + ','.join(names) + ';')
DECLS = '\n'.join(decls)

SUM_LOCALS = wrap('return ' + ' + '.join(f"l{i}" for i in range(NL)) + ';', '           ')
NEST_A = wrap('return ' + nest(['a'] * NS) + ';', '           ')
NEST_L = wrap('return ' + nest([f"l{i}" for i in range(NL)]) + ';', '           ')

SRC = f'''// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Craton Software Company
//
// What a BIGGER FRAME costs, holding the executed body constant.
//
// The interpreter builds a callee frame by sizing two buffers to the method's
// `max_locals` and `max_stack` and filling them. Everything else about a call
// -- the dispatch, the argument transfer, the push -- is independent of those
// two numbers. So the difference between calling a method with a small frame
// and one with a large frame, when both bodies execute the SAME bytecode, is
// the per-frame sizing and fill cost and nothing else.
//
// Each `big` arm declares its locals (or builds its deep expression) inside a
// branch that is never taken -- the caller never passes Integer.MIN_VALUE --
// so javac raises `max_locals` / `max_stack` for the whole method while the
// executed path stays the same few bytecodes as the `small` arm. Read the
// DELTA between arms, not either arm alone: the body difference (one extra
// compare) is constant across binaries and cancels.
//
// Generated by scratchpad/gen_frameshape.py so the nesting is balanced.
//
// Interleaves its arms in both directions on alternating rounds and reports
// min-of-N, like every other probe on
// docs/known-issues/perf/interpreted-invoke-cost-350ns-20260825.md.
public class FrameShape {{

    // max_locals ~= 2, max_stack ~= 2
    static int small(int a) {{
        return a;
    }}

    // max_locals ~= {NL + 2}, max_stack small. The branch never runs.
    static int locals{NL}(int a) {{
        if (a == Integer.MIN_VALUE) {{
{DECLS}
{SUM_LOCALS}
        }}
        return a;
    }}

    // max_locals ~= 2, max_stack ~= {NS + 2}: one deep expression, never evaluated.
    static int stack{NS}(int a) {{
        if (a == Integer.MIN_VALUE) {{
{NEST_A}
        }}
        return a;
    }}

    // Both, which is what an ordinary framework method looks like.
    static int both(int a) {{
        if (a == Integer.MIN_VALUE) {{
{DECLS}
{NEST_L}
        }}
        return a;
    }}

    static int cNone(int n){{int s=0;for(int i=0;i<n;i++) s+=i; return s;}}
    static int cSmall(int n){{int s=0;for(int i=0;i<n;i++) s+=small(i); return s;}}
    static int cLocals(int n){{int s=0;for(int i=0;i<n;i++) s+=locals{NL}(i); return s;}}
    static int cStack(int n){{int s=0;for(int i=0;i<n;i++) s+=stack{NS}(i); return s;}}
    static int cBoth(int n){{int s=0;for(int i=0;i<n;i++) s+=both(i); return s;}}

    public static void main(String[] a) {{
        int n = a.length > 0 ? Integer.parseInt(a[0]) : 1000000;
        int rounds = a.length > 1 ? Integer.parseInt(a[1]) : 9;
        // Optional third argument: run ONE arm only. The rdtsc phase
        // counters (CRATONVM_DBG=invoke-phases) are process-wide, so
        // isolating an arm is the only way to read a per-arm breakdown
        // out of them.
        String only = a.length > 2 ? a[2] : null;
        String[] nm = {{"nocall", "small", "locals{NL}", "stack{NS}", "both"}};
        double[] m = new double[nm.length];
        for (int i = 0; i < m.length; i++) m[i] = 1e18;
        int sink = 0; long t;
        for (int r = 0; r < rounds; r++) {{
            boolean fwd = (r & 1) == 0;
            for (int k = 0; k < nm.length; k++) {{
                int j = fwd ? k : nm.length - 1 - k;
                if (only != null && !nm[j].equals(only)) continue;
                t = System.nanoTime();
                switch (j) {{
                    case 0: sink += cNone(n); break;
                    case 1: sink += cSmall(n); break;
                    case 2: sink += cLocals(n); break;
                    case 3: sink += cStack(n); break;
                    default: sink += cBoth(n); break;
                }}
                double d = (System.nanoTime() - t) / (double) n;
                if (d < m[j]) m[j] = d;
            }}
        }}
        for (int i = 0; i < nm.length; i++) {{
            if (only != null && !nm[i].equals(only)) continue;
            System.out.println(nm[i] + "\\t" + m[i] + " ns/iter\\tdelta=" + (m[i] - m[0]));
        }}
        if (only != null) {{ if (sink == 42) System.out.println("x"); return; }}
        System.out.println("per-call frame cost, small       = " + (m[1] - m[0]));
        System.out.println("{NL} extra local slots cost        = " + (m[2] - m[1]));
        System.out.println("{NS} extra stack slots cost        = " + (m[3] - m[1]));
        System.out.println("both                             = " + (m[4] - m[1]));
        if (sink == 42) System.out.println("x");
    }}
}}
'''
open(sys.argv[1], 'w', encoding='utf-8', newline='\n').write(SRC)
print('wrote', sys.argv[1])
