// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 Craton Software Company

//! Fuzz target for **JNI / JVM descriptor and generic-signature parsing**,
//! with adversarial shapes generated by the harness rather than left to
//! chance.
//!
//! A JNI method signature is exactly a JVMS §4.3.3 method descriptor — the
//! same grammar `RegisterNatives`, `GetMethodID`, and every `.class`
//! `NameAndType` entry feed into. `fuzz_descriptor` already throws raw
//! bytes at these parsers; this target adds the *structured* shapes a
//! random mutator effectively never reaches on its own, and asserts the
//! documented limits instead of only asserting no-panic:
//!
//!   * deep array nesting (`[[[[…`) past the JVMS §4.3.2 255-dimension cap,
//!   * unterminated `L…` with no `;`,
//!   * empty class names (`L;`) and empty descriptors,
//!   * argument lists well past 255 parameters,
//!   * invalid / non-ASCII / NUL bytes inside class names,
//!   * generic-signature depth bombs on both the uncached and the cached
//!     parser path.
//!
//! Surface under test:
//!   * `cratonvm_reader::field_type::FieldType::{parse, parse_partial}`
//!     (`reader/src/field_type.rs:34` / `:52`) — enforces
//!     `MAX_ARRAY_DIMENSIONS = 255` at `reader/src/field_type.rs:89`
//!     (canonical value in `reader/src/limits.rs`).
//!   * `cratonvm_reader::method_descriptor::MethodDescriptor::parse`
//!     (`reader/src/method_descriptor.rs:24`).
//!   * `cratonvm_reader::signature::{parse_class_signature,
//!     parse_method_signature, parse_field_signature}` and their
//!     `_cached` twins (`reader/src/signature.rs:469`, `:476`, `:490`,
//!     `:705`, `:743`, `:772`) — bounded by `MAX_SIG_DEPTH = 256`
//!     (`reader/src/signature.rs:120`).
//!
//! The strongest oracle here is a **`Display` → `parse` round trip** on
//! every successfully parsed type. A panic-only oracle cannot see a decoder
//! that silently drops an array dimension or truncates a class name at an
//! unexpected delimiter; the round trip can. It is total for these types
//! because a `FieldType::Object` name can never contain `;` (the parser
//! splits on the first one) and no `FieldType` renders as a bare `V`, so
//! re-serialising is unambiguous in both directions.
//!
//! **Cross-shape cache comparison.** `reader/src/signature.rs` memoizes all
//! three signature shapes in *one* map keyed by the signature string, but
//! every verdict it stores is shape-qualified — including the rejection,
//! which is `ParsedSignature::Invalid { class, method, field }` and not a
//! bare `Invalid`. So a cached entry recorded by one entry point never
//! answers for another: on a shape mismatch a success falls through to an
//! uncached re-parse, and a rejection short-circuits only the shape that
//! recorded it.
//!
//! That was not always true, which is why this target asks the way it does.
//! An unqualified `Invalid` meant whichever shape probed a string first
//! poisoned it for the other two, and `<T:Ljava/lang/Object;>L…;` — a valid
//! *class* signature and an invalid *field* signature — then read back as
//! `None` from the class-shaped cached parser if anything had asked for it
//! as a field first. Generic type information disappeared as a function of
//! lookup order, silently. This target therefore compares **all three
//! shapes per input** against their uncached twins and rotates the order it
//! asks in, because that bug was reachable only through one ordering.
//!
//! Not covered here: JNI *symbol-name mangling* (`Java_pkg_Cls_meth__Sig`).
//! `jni_short_name` / `jni_long_name` live in `vm/src/vm/vm_object.rs:1671`
//! and `vm/src/native/jni.rs:4737`, and pulling `cratonvm-vm` into the fuzz
//! workspace would drag in the JIT, GC, and threading crates for two pure
//! string functions. See `README.md`.
//!
//! Per-input layout:
//!   * byte 0 — shape selector: `% COMPONENTS.len()` picks the component
//!     type, and the digits above that pick the order in which the
//!     cached/uncached differential visits the three signature shapes.
//!   * byte 1 — repeat scale for the unterminated-`L` case.
//!   * bytes 2.. — free-form descriptor text for the panic-only phase.
//!
//! Run with:
//!   cargo +nightly fuzz run fuzz_jni_descriptor

#![no_main]

use std::sync::{Arc, Once};

use libfuzzer_sys::fuzz_target;

use cratonvm_reader::field_type::FieldType;
use cratonvm_reader::method_descriptor::MethodDescriptor;
use cratonvm_reader::signature;

/// A `CONSTANT_Utf8` entry is `u16`-length-prefixed, so a descriptor read
/// out of a real class file is at most 64 KiB. Cap a little above that.
const MAX_INPUT: usize = 128 * 1024;

/// JVMS §4.3.2: an array type may have at most 255 dimensions. Mirrors the
/// private `FieldType::MAX_ARRAY_DIMENSIONS`.
const MAX_ARRAY_DIMENSIONS: usize = 255;

/// Dimension count used for the "must be rejected without overflowing the
/// stack" direction. Several orders of magnitude past the cap.
const ARRAY_BOMB_DIMENSIONS: usize = 100_000;

/// Nesting level for the generic-signature depth bomb. `MAX_SIG_DEPTH` is
/// 256; this is far past it while keeping the generated string ~40 KiB.
const SIGNATURE_BOMB_DEPTH: usize = 8_000;

/// Parameter count for the "many arguments" shape. JVMS §4.3.3 caps a
/// method at 255 *argument slots*, but that is a `ClassFile` structural
/// rule enforced by the verifier, not by the descriptor grammar — the
/// descriptor parser is expected to accept this and simply stay bounded.
const MANY_PARAMETERS: usize = 300;

/// Every primitive descriptor plus a few reference shapes, used to build
/// the per-input structured cases.
const COMPONENTS: [&str; 12] = [
    "B",
    "C",
    "D",
    "F",
    "I",
    "J",
    "S",
    "Z",
    "V",
    "Ljava/lang/String;",
    "L;",
    "[I",
];

/// One of the three signature grammars the cached/uncached differential
/// covers. The grammars are not nested — a string can be valid under one
/// and garbage under another — which is exactly what makes the order the
/// shapes are asked in worth varying.
#[derive(Clone, Copy)]
enum Shape {
    Class,
    Method,
    Field,
}

/// Every order the three shapes can be asked in. The cache aliasing bug
/// that motivated this differential was reachable only when the shape that
/// rejects the string was asked before the shape that accepts it, so a
/// fixed order would have missed it half the time.
const SHAPE_ORDERS: [[Shape; 3]; 6] = [
    [Shape::Class, Shape::Method, Shape::Field],
    [Shape::Class, Shape::Field, Shape::Method],
    [Shape::Method, Shape::Class, Shape::Field],
    [Shape::Method, Shape::Field, Shape::Class],
    [Shape::Field, Shape::Class, Shape::Method],
    [Shape::Field, Shape::Method, Shape::Class],
];

/// Assert that `ft` survives a `Display` → `parse` round trip.
fn assert_field_type_round_trips(ft: &FieldType) {
    let rendered = ft.to_string();
    match FieldType::parse(&rendered) {
        Ok(reparsed) => assert_eq!(
            &reparsed, ft,
            "FieldType round trip changed the type: {rendered:?}"
        ),
        Err(e) => panic!("FieldType::parse rejected its own rendering {rendered:?}: {e:?}"),
    }
}

/// Input-independent limit checks, run once per fuzzing process.
///
/// These build multi-hundred-kilobyte strings and would otherwise burn the
/// whole per-iteration budget on constant work that cannot depend on the
/// fuzzer's bytes. Running them at process start still catches a regressed
/// cap: libFuzzer reports the resulting stack overflow / failed assertion
/// exactly the same way.
fn structural_limits_self_test() {
    // ---- Array dimension cap, asserted in both directions. ----
    // Exactly at the cap is legal — this is the positive control that
    // keeps the rejection below from passing vacuously.
    let at_cap = format!("{}I", "[".repeat(MAX_ARRAY_DIMENSIONS));
    let parsed_at_cap = FieldType::parse(&at_cap);
    assert!(
        parsed_at_cap.is_ok(),
        "exactly {MAX_ARRAY_DIMENSIONS} array dimensions is legal per JVMS 4.3.2 and must parse"
    );
    if let Ok(ft) = &parsed_at_cap {
        assert_field_type_round_trips(ft);
    }

    let past_cap = format!("{}I", "[".repeat(MAX_ARRAY_DIMENSIONS + 1));
    assert!(
        FieldType::parse(&past_cap).is_err(),
        "{} array dimensions exceeds the JVMS 4.3.2 cap and must be rejected",
        MAX_ARRAY_DIMENSIONS + 1
    );

    // A dimension bomb must be *rejected*, not recursed into. If the cap
    // ever regresses this overflows the stack, which libFuzzer reports as
    // a crash — exactly the signal we want.
    let bomb = format!("{}I", "[".repeat(ARRAY_BOMB_DIMENSIONS));
    assert!(
        FieldType::parse(&bomb).is_err(),
        "{ARRAY_BOMB_DIMENSIONS} array dimensions must be rejected, not recursed into"
    );
    assert!(
        MethodDescriptor::parse(&format!("({bomb})V")).is_err(),
        "an array bomb in parameter position must be rejected too"
    );

    // ---- Generic-signature depth bomb, uncached and cached. ----
    // A prior bug let the cached path memoize a partial AST the uncached
    // path rejected; the two must always agree. Same shape on both sides,
    // and the cache is flushed first so no earlier verdict can leak in.
    let mut deep = String::with_capacity(SIGNATURE_BOMB_DEPTH * 5 + 8);
    for _ in 0..SIGNATURE_BOMB_DEPTH {
        deep.push_str("Lp<");
    }
    deep.push_str("Lp;");
    for _ in 0..SIGNATURE_BOMB_DEPTH {
        deep.push_str(">;");
    }
    signature::clear_signature_cache();
    assert!(
        signature::parse_field_signature(&deep).is_none(),
        "a generic signature nested {SIGNATURE_BOMB_DEPTH} deep must be rejected"
    );
    let deep_key: Arc<str> = Arc::from(deep.as_str());
    assert!(
        signature::parse_field_signature_cached(&deep_key).is_none(),
        "the cached signature parser must honour the depth guard the uncached one enforces"
    );
    signature::clear_signature_cache();
}

static SELF_TEST: Once = Once::new();

fuzz_target!(|data: &[u8]| {
    if data.len() < 2 || data.len() > MAX_INPUT {
        return;
    }

    SELF_TEST.call_once(structural_limits_self_test);

    let selector = data[0] as usize;
    let scale = data[1] as usize;
    let free_form = String::from_utf8_lossy(&data[2..]).into_owned();
    let component = COMPONENTS[selector % COMPONENTS.len()];

    // -------------------------------------------------------------------
    // Malformed reference descriptors.
    // -------------------------------------------------------------------
    // Unterminated `L…` (no `;` anywhere) must fail rather than run off
    // the end of the string.
    let unterminated = format!("L{}", "a".repeat(scale.max(1)));
    assert!(
        FieldType::parse(&unterminated).is_err(),
        "an unterminated L-descriptor must be rejected"
    );
    assert!(
        FieldType::parse("").is_err(),
        "the empty descriptor must be rejected"
    );
    assert!(
        MethodDescriptor::parse("").is_err(),
        "the empty method descriptor must be rejected"
    );
    // None of the component descriptors start with '(', so none of them is
    // a method descriptor.
    assert!(
        MethodDescriptor::parse(component).is_err(),
        "a method descriptor must start with '(' — {component:?} was accepted"
    );
    // An empty class name (`L;`) is legal grammar: the name is empty, not
    // absent. Whatever the parser decides, it must round trip.
    if let Ok(ft) = FieldType::parse("L;") {
        assert_field_type_round_trips(&ft);
    }
    // Invalid characters inside a class name, including NUL and non-ASCII,
    // must not disturb the `;` delimiter search.
    if let Ok(ft) = FieldType::parse("L\u{0}a/b\u{7f}\u{10ffff};") {
        assert_field_type_round_trips(&ft);
    }

    // -------------------------------------------------------------------
    // Very wide argument lists (past the 255-slot structural limit).
    // -------------------------------------------------------------------
    // `V` is only legal as a return type, so substitute it in parameter
    // position.
    let param = if component == "V" { "I" } else { component };
    let wide = format!("({}){}", param.repeat(MANY_PARAMETERS), component);
    if let Ok(md) = MethodDescriptor::parse(&wide) {
        assert_eq!(
            md.parameters.len(),
            MANY_PARAMETERS,
            "wide descriptor lost or duplicated parameters"
        );
        // Category-2 types occupy two slots; nothing occupies more.
        assert!(
            md.parameters_stack_slots() <= md.parameters.len() * 2,
            "parameter slot count exceeds 2 per parameter"
        );
        let rendered = md.to_string();
        match MethodDescriptor::parse(&rendered) {
            Ok(reparsed) => assert_eq!(
                reparsed, md,
                "MethodDescriptor round trip changed the descriptor: {rendered:?}"
            ),
            Err(e) => panic!("MethodDescriptor rejected its own rendering: {e:?}"),
        }
    }

    // -------------------------------------------------------------------
    // Free-form phase — panic-only, plus the round-trip oracle whenever a
    // parse succeeds.
    // -------------------------------------------------------------------
    if let Ok(ft) = FieldType::parse(&free_form) {
        assert_field_type_round_trips(&ft);
    }
    if let Ok((ft, rest)) = FieldType::parse_partial(&free_form) {
        // `parse_partial` must consume a non-empty prefix and hand back a
        // strict suffix of its input — never a longer or unrelated string.
        assert!(
            rest.len() < free_form.len(),
            "parse_partial consumed nothing but reported success"
        );
        assert!(
            free_form.ends_with(rest),
            "parse_partial returned a remainder that is not a suffix of its input"
        );
        assert_field_type_round_trips(&ft);
    }
    if let Ok(md) = MethodDescriptor::parse(&free_form) {
        // The parser must never manufacture parameters it did not read:
        // every parameter costs at least one descriptor character.
        assert!(
            md.parameters.len() <= free_form.len(),
            "method descriptor produced more parameters than it had characters"
        );
        for p in &md.parameters {
            assert_field_type_round_trips(p);
        }
        if let Some(rt) = &md.return_type {
            assert_field_type_round_trips(rt);
        }
    }

    // -------------------------------------------------------------------
    // Cached vs uncached signature parsers — all three shapes per input.
    //
    // Deliberately NOT flushed between the three shapes: the point is that
    // asking one shape must not change what another answers, whichever
    // order they are asked in (see the cross-shape note in the module
    // docs). The order rotates with the input so all six permutations are
    // reachable — the aliasing bug this guards against only ever fired when
    // the invalid shape was asked first.
    //
    // The oracle compares the parsed values, not just success/failure: a
    // cache that returned the right verdict but the wrong AST would satisfy
    // an `is_some()` comparison.
    // -------------------------------------------------------------------
    let key: Arc<str> = Arc::from(free_form.as_str());
    for shape in SHAPE_ORDERS[(selector / COMPONENTS.len()) % SHAPE_ORDERS.len()] {
        match shape {
            Shape::Field => assert_eq!(
                signature::parse_field_signature(&free_form).as_ref(),
                signature::parse_field_signature_cached(&key).as_deref(),
                "cached and uncached field-signature parsers disagree"
            ),
            Shape::Class => assert_eq!(
                signature::parse_class_signature(&free_form).as_ref(),
                signature::parse_class_signature_cached(&key).as_deref(),
                "cached and uncached class-signature parsers disagree"
            ),
            Shape::Method => assert_eq!(
                signature::parse_method_signature(&free_form).as_ref(),
                signature::parse_method_signature_cached(&key).as_deref(),
                "cached and uncached method-signature parsers disagree"
            ),
        }
    }
    // Flush only once the whole input is done. `SIGNATURE_CACHE_CAP` already
    // bounds the entry count, but a fuzzer input runs to `MAX_INPUT`, so
    // retaining thousands of them would let the harness's own footprint
    // dwarf the parser under test.
    signature::clear_signature_cache();
});
